// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: academic_years.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateAcademicYear = `-- name: ActivateAcademicYear :exec
UPDATE academic_years
SET is_active = true, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ActivateAcademicYear(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, activateAcademicYear, id)
	return err
}

const countAcademicYears = `-- name: CountAcademicYears :one
SELECT COUNT(*) FROM academic_years
WHERE is_active = true
`

func (q *Queries) CountAcademicYears(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAcademicYears)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStudentsByAcademicYear = `-- name: CountStudentsByAcademicYear :one
SELECT COUNT(*) FROM students
WHERE year_of_study = $1 AND deleted_at IS NULL
`

func (q *Queries) CountStudentsByAcademicYear(ctx context.Context, yearOfStudy int32) (int64, error) {
	row := q.db.QueryRow(ctx, countStudentsByAcademicYear, yearOfStudy)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAcademicYear = `-- name: CreateAcademicYear :one
INSERT INTO academic_years (name, level, description)
VALUES ($1, $2, $3)
RETURNING id, name, level, description, is_active, created_at, updated_at
`

type CreateAcademicYearParams struct {
	Name        string      `db:"name" json:"name"`
	Level       int32       `db:"level" json:"level"`
	Description pgtype.Text `db:"description" json:"description"`
}

func (q *Queries) CreateAcademicYear(ctx context.Context, arg CreateAcademicYearParams) (AcademicYear, error) {
	row := q.db.QueryRow(ctx, createAcademicYear, arg.Name, arg.Level, arg.Description)
	var i AcademicYear
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Level,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateAcademicYear = `-- name: DeactivateAcademicYear :exec
UPDATE academic_years
SET is_active = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateAcademicYear(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deactivateAcademicYear, id)
	return err
}

const deleteAcademicYear = `-- name: DeleteAcademicYear :exec
DELETE FROM academic_years
WHERE id = $1
`

func (q *Queries) DeleteAcademicYear(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAcademicYear, id)
	return err
}

const getAcademicYearByID = `-- name: GetAcademicYearByID :one
SELECT id, name, level, description, is_active, created_at, updated_at FROM academic_years
WHERE id = $1
`

func (q *Queries) GetAcademicYearByID(ctx context.Context, id int32) (AcademicYear, error) {
	row := q.db.QueryRow(ctx, getAcademicYearByID, id)
	var i AcademicYear
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Level,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAcademicYearByLevel = `-- name: GetAcademicYearByLevel :one
SELECT id, name, level, description, is_active, created_at, updated_at FROM academic_years
WHERE level = $1
`

func (q *Queries) GetAcademicYearByLevel(ctx context.Context, level int32) (AcademicYear, error) {
	row := q.db.QueryRow(ctx, getAcademicYearByLevel, level)
	var i AcademicYear
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Level,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAcademicYears = `-- name: ListAcademicYears :many
SELECT id, name, level, description, is_active, created_at, updated_at FROM academic_years
WHERE is_active = true
ORDER BY level
`

func (q *Queries) ListAcademicYears(ctx context.Context) ([]AcademicYear, error) {
	rows, err := q.db.Query(ctx, listAcademicYears)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcademicYear{}
	for rows.Next() {
		var i AcademicYear
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Level,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAcademicYears = `-- name: ListAllAcademicYears :many
SELECT id, name, level, description, is_active, created_at, updated_at FROM academic_years
ORDER BY level
`

func (q *Queries) ListAllAcademicYears(ctx context.Context) ([]AcademicYear, error) {
	rows, err := q.db.Query(ctx, listAllAcademicYears)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcademicYear{}
	for rows.Next() {
		var i AcademicYear
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Level,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAcademicYear = `-- name: UpdateAcademicYear :one
UPDATE academic_years
SET name = $2, level = $3, description = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, name, level, description, is_active, created_at, updated_at
`

type UpdateAcademicYearParams struct {
	ID          int32       `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Level       int32       `db:"level" json:"level"`
	Description pgtype.Text `db:"description" json:"description"`
}

func (q *Queries) UpdateAcademicYear(ctx context.Context, arg UpdateAcademicYearParams) (AcademicYear, error) {
	row := q.db.QueryRow(ctx, updateAcademicYear,
		arg.ID,
		arg.Name,
		arg.Level,
		arg.Description,
	)
	var i AcademicYear
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Level,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
