// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: authors.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addBookAuthor = `-- name: AddBookAuthor :exec
INSERT INTO book_authors (book_id, author_id, author_order)
VALUES ($1, $2, $3)
ON CONFLICT (book_id, author_id) DO UPDATE SET author_order = $3
`

type AddBookAuthorParams struct {
	BookID      int32       `db:"book_id" json:"book_id"`
	AuthorID    int32       `db:"author_id" json:"author_id"`
	AuthorOrder pgtype.Int4 `db:"author_order" json:"author_order"`
}

func (q *Queries) AddBookAuthor(ctx context.Context, arg AddBookAuthorParams) error {
	_, err := q.db.Exec(ctx, addBookAuthor, arg.BookID, arg.AuthorID, arg.AuthorOrder)
	return err
}

const countAuthorBooks = `-- name: CountAuthorBooks :one
SELECT COUNT(*) FROM book_authors ba
JOIN books b ON ba.book_id = b.id
WHERE ba.author_id = $1 AND b.deleted_at IS NULL
`

func (q *Queries) CountAuthorBooks(ctx context.Context, authorID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthorBooks, authorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuthors = `-- name: CountAuthors :one
SELECT COUNT(*) FROM authors
`

func (q *Queries) CountAuthors(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (name, bio)
VALUES ($1, $2)
RETURNING id, name, bio, created_at, updated_at
`

type CreateAuthorParams struct {
	Name string      `db:"name" json:"name"`
	Bio  pgtype.Text `db:"bio" json:"bio"`
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, createAuthor, arg.Name, arg.Bio)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE FROM authors
WHERE id = $1
`

func (q *Queries) DeleteAuthor(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAuthor, id)
	return err
}

const getAuthorByID = `-- name: GetAuthorByID :one
SELECT id, name, bio, created_at, updated_at FROM authors
WHERE id = $1
`

func (q *Queries) GetAuthorByID(ctx context.Context, id int32) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthorByID, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthorByName = `-- name: GetAuthorByName :one
SELECT id, name, bio, created_at, updated_at FROM authors
WHERE name = $1
`

func (q *Queries) GetAuthorByName(ctx context.Context, name string) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthorByName, name)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAuthorBooks = `-- name: ListAuthorBooks :many
SELECT b.id, b.book_id, b.isbn, b.title, b.author, b.publisher, b.published_year, b.genre, b.description, b.cover_image_url, b.total_copies, b.available_copies, b.shelf_location, b.is_active, b.deleted_at, b.created_at, b.updated_at, b.condition, b.category_id, b.series_id, b.series_number, b.language, b.page_count, b.edition, b.format, b.book_type FROM books b
JOIN book_authors ba ON b.id = ba.book_id
WHERE ba.author_id = $1 AND b.deleted_at IS NULL
ORDER BY b.title
`

func (q *Queries) ListAuthorBooks(ctx context.Context, authorID int32) ([]Book, error) {
	rows, err := q.db.Query(ctx, listAuthorBooks, authorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Isbn,
			&i.Title,
			&i.Author,
			&i.Publisher,
			&i.PublishedYear,
			&i.Genre,
			&i.Description,
			&i.CoverImageUrl,
			&i.TotalCopies,
			&i.AvailableCopies,
			&i.ShelfLocation,
			&i.IsActive,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Condition,
			&i.CategoryID,
			&i.SeriesID,
			&i.SeriesNumber,
			&i.Language,
			&i.PageCount,
			&i.Edition,
			&i.Format,
			&i.BookType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthors = `-- name: ListAuthors :many
SELECT id, name, bio, created_at, updated_at FROM authors
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListAuthorsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]Author, error) {
	rows, err := q.db.Query(ctx, listAuthors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Author{}
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bio,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookAuthors = `-- name: ListBookAuthors :many
SELECT a.id, a.name, a.bio, a.created_at, a.updated_at FROM authors a
JOIN book_authors ba ON a.id = ba.author_id
WHERE ba.book_id = $1
ORDER BY ba.author_order
`

func (q *Queries) ListBookAuthors(ctx context.Context, bookID int32) ([]Author, error) {
	rows, err := q.db.Query(ctx, listBookAuthors, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Author{}
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bio,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeBookAuthor = `-- name: RemoveBookAuthor :exec
DELETE FROM book_authors
WHERE book_id = $1 AND author_id = $2
`

type RemoveBookAuthorParams struct {
	BookID   int32 `db:"book_id" json:"book_id"`
	AuthorID int32 `db:"author_id" json:"author_id"`
}

func (q *Queries) RemoveBookAuthor(ctx context.Context, arg RemoveBookAuthorParams) error {
	_, err := q.db.Exec(ctx, removeBookAuthor, arg.BookID, arg.AuthorID)
	return err
}

const searchAuthors = `-- name: SearchAuthors :many
SELECT id, name, bio, created_at, updated_at FROM authors
WHERE name ILIKE $1
ORDER BY name
LIMIT $2 OFFSET $3
`

type SearchAuthorsParams struct {
	Name   string `db:"name" json:"name"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) SearchAuthors(ctx context.Context, arg SearchAuthorsParams) ([]Author, error) {
	rows, err := q.db.Query(ctx, searchAuthors, arg.Name, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Author{}
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bio,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthor = `-- name: UpdateAuthor :one
UPDATE authors
SET name = $2, bio = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, name, bio, created_at, updated_at
`

type UpdateAuthorParams struct {
	ID   int32       `db:"id" json:"id"`
	Name string      `db:"name" json:"name"`
	Bio  pgtype.Text `db:"bio" json:"bio"`
}

func (q *Queries) UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, updateAuthor, arg.ID, arg.Name, arg.Bio)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Bio,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
