// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: departments.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateDepartment = `-- name: ActivateDepartment :exec
UPDATE departments
SET is_active = true, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) ActivateDepartment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, activateDepartment, id)
	return err
}

const countDepartments = `-- name: CountDepartments :one
SELECT COUNT(*) FROM departments
WHERE is_active = true
`

func (q *Queries) CountDepartments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDepartments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (name, code, description)
VALUES ($1, $2, $3)
RETURNING id, name, code, description, is_active, created_at, updated_at
`

type CreateDepartmentParams struct {
	Name        string      `db:"name" json:"name"`
	Code        pgtype.Text `db:"code" json:"code"`
	Description pgtype.Text `db:"description" json:"description"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment, arg.Name, arg.Code, arg.Description)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateDepartment = `-- name: DeactivateDepartment :exec
UPDATE departments
SET is_active = false, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateDepartment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deactivateDepartment, id)
	return err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM departments
WHERE id = $1
`

func (q *Queries) DeleteDepartment(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteDepartment, id)
	return err
}

const getDepartmentByCode = `-- name: GetDepartmentByCode :one
SELECT id, name, code, description, is_active, created_at, updated_at FROM departments
WHERE code = $1
`

func (q *Queries) GetDepartmentByCode(ctx context.Context, code pgtype.Text) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByCode, code)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepartmentByID = `-- name: GetDepartmentByID :one
SELECT id, name, code, description, is_active, created_at, updated_at FROM departments
WHERE id = $1
`

func (q *Queries) GetDepartmentByID(ctx context.Context, id int32) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByID, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDepartmentByName = `-- name: GetDepartmentByName :one
SELECT id, name, code, description, is_active, created_at, updated_at FROM departments
WHERE name = $1
`

func (q *Queries) GetDepartmentByName(ctx context.Context, name string) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByName, name)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllDepartments = `-- name: ListAllDepartments :many
SELECT id, name, code, description, is_active, created_at, updated_at FROM departments
ORDER BY name
`

func (q *Queries) ListAllDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.Query(ctx, listAllDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Department{}
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, name, code, description, is_active, created_at, updated_at FROM departments
WHERE is_active = true
ORDER BY name
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Department{}
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments
SET name = $2, code = $3, description = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, name, code, description, is_active, created_at, updated_at
`

type UpdateDepartmentParams struct {
	ID          int32       `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Code        pgtype.Text `db:"code" json:"code"`
	Description pgtype.Text `db:"description" json:"description"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Description,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
