// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fines.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkPayFines = `-- name: BulkPayFines :execrows
UPDATE transactions
SET fine_paid = true,
    fine_paid_at = NOW(),
    updated_at = NOW()
WHERE id = ANY($1::int[])
    AND fine_amount > 0
    AND fine_paid = false
`

func (q *Queries) BulkPayFines(ctx context.Context, dollar_1 []int32) (int64, error) {
	result, err := q.db.Exec(ctx, bulkPayFines, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkWaiveFines = `-- name: BulkWaiveFines :execrows
UPDATE transactions
SET fine_waived = true,
    fine_waived_at = NOW(),
    fine_waived_by = $2,
    fine_waived_reason = $3,
    fine_paid = true,
    fine_paid_at = NOW(),
    updated_at = NOW()
WHERE id = ANY($1::int[])
    AND fine_amount > 0
    AND fine_paid = false
`

type BulkWaiveFinesParams struct {
	Column1          []int32     `db:"column_1" json:"column_1"`
	FineWaivedBy     pgtype.Int4 `db:"fine_waived_by" json:"fine_waived_by"`
	FineWaivedReason pgtype.Text `db:"fine_waived_reason" json:"fine_waived_reason"`
}

func (q *Queries) BulkWaiveFines(ctx context.Context, arg BulkWaiveFinesParams) (int64, error) {
	result, err := q.db.Exec(ctx, bulkWaiveFines, arg.Column1, arg.FineWaivedBy, arg.FineWaivedReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countFines = `-- name: CountFines :one
SELECT COUNT(*) FROM transactions t
INNER JOIN students s ON t.student_id = s.id
WHERE t.fine_amount > 0
    AND s.deleted_at IS NULL
    AND ($1::bool IS NULL OR t.fine_paid = $1::bool)
    AND ($2::int IS NULL OR t.student_id = $2::int)
`

type CountFinesParams struct {
	Paid      pgtype.Bool `db:"paid" json:"paid"`
	StudentID pgtype.Int4 `db:"student_id" json:"student_id"`
}

func (q *Queries) CountFines(ctx context.Context, arg CountFinesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countFines, arg.Paid, arg.StudentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStudentsWithOverdue = `-- name: CountStudentsWithOverdue :one
SELECT COUNT(DISTINCT student_id)::int
FROM transactions
WHERE due_date < NOW()
    AND returned_date IS NULL
    AND transaction_type = 'borrow'
`

func (q *Queries) CountStudentsWithOverdue(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countStudentsWithOverdue)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countStudentsWithUnpaidFines = `-- name: CountStudentsWithUnpaidFines :one
SELECT COUNT(DISTINCT student_id)::int
FROM transactions
WHERE fine_amount > 0
    AND fine_paid = false
    AND (COALESCE(fine_waived, false) = false)
`

func (q *Queries) CountStudentsWithUnpaidFines(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countStudentsWithUnpaidFines)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getFineByTransactionID = `-- name: GetFineByTransactionID :one
SELECT
    t.id as transaction_id,
    t.student_id,
    s.student_id as student_code,
    CONCAT(s.first_name, ' ', s.last_name) as student_name,
    s.email as student_email,
    t.book_id,
    b.title as book_title,
    b.author as book_author,
    t.fine_amount,
    t.fine_paid,
    t.fine_paid_at,
    COALESCE(t.fine_waived, false) as fine_waived,
    t.fine_waived_at,
    t.fine_waived_by,
    t.fine_waived_reason,
    t.due_date,
    t.returned_date,
    GREATEST(EXTRACT(DAY FROM (COALESCE(t.returned_date, NOW()) - t.due_date))::int, 0) as days_overdue,
    t.created_at
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
INNER JOIN books b ON t.book_id = b.id
WHERE t.id = $1
    AND t.fine_amount > 0
    AND s.deleted_at IS NULL
`

type GetFineByTransactionIDRow struct {
	TransactionID    int32            `db:"transaction_id" json:"transaction_id"`
	StudentID        int32            `db:"student_id" json:"student_id"`
	StudentCode      string           `db:"student_code" json:"student_code"`
	StudentName      interface{}      `db:"student_name" json:"student_name"`
	StudentEmail     pgtype.Text      `db:"student_email" json:"student_email"`
	BookID           int32            `db:"book_id" json:"book_id"`
	BookTitle        string           `db:"book_title" json:"book_title"`
	BookAuthor       string           `db:"book_author" json:"book_author"`
	FineAmount       pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid         pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	FinePaidAt       pgtype.Timestamp `db:"fine_paid_at" json:"fine_paid_at"`
	FineWaived       bool             `db:"fine_waived" json:"fine_waived"`
	FineWaivedAt     pgtype.Timestamp `db:"fine_waived_at" json:"fine_waived_at"`
	FineWaivedBy     pgtype.Int4      `db:"fine_waived_by" json:"fine_waived_by"`
	FineWaivedReason pgtype.Text      `db:"fine_waived_reason" json:"fine_waived_reason"`
	DueDate          pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate     pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	DaysOverdue      interface{}      `db:"days_overdue" json:"days_overdue"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) GetFineByTransactionID(ctx context.Context, id int32) (GetFineByTransactionIDRow, error) {
	row := q.db.QueryRow(ctx, getFineByTransactionID, id)
	var i GetFineByTransactionIDRow
	err := row.Scan(
		&i.TransactionID,
		&i.StudentID,
		&i.StudentCode,
		&i.StudentName,
		&i.StudentEmail,
		&i.BookID,
		&i.BookTitle,
		&i.BookAuthor,
		&i.FineAmount,
		&i.FinePaid,
		&i.FinePaidAt,
		&i.FineWaived,
		&i.FineWaivedAt,
		&i.FineWaivedBy,
		&i.FineWaivedReason,
		&i.DueDate,
		&i.ReturnedDate,
		&i.DaysOverdue,
		&i.CreatedAt,
	)
	return i, err
}

const getFineOverviewStats = `-- name: GetFineOverviewStats :one
SELECT
    COUNT(*) FILTER (WHERE fine_paid = false AND (COALESCE(fine_waived, false) = false))::int as unpaid_count,
    COUNT(*) FILTER (WHERE fine_paid = true)::int as paid_count,
    COUNT(*) FILTER (WHERE COALESCE(fine_waived, false) = true)::int as waived_count,
    COALESCE(SUM(fine_amount) FILTER (WHERE fine_paid = false AND (COALESCE(fine_waived, false) = false)), 0)::numeric as total_unpaid,
    COALESCE(SUM(fine_amount) FILTER (WHERE fine_paid = true AND (COALESCE(fine_waived, false) = false)), 0)::numeric as total_collected,
    COALESCE(SUM(fine_amount) FILTER (WHERE COALESCE(fine_waived, false) = true), 0)::numeric as total_waived,
    COUNT(DISTINCT student_id) FILTER (WHERE fine_paid = false AND (COALESCE(fine_waived, false) = false))::int as students_with_unpaid_fines
FROM transactions
WHERE fine_amount > 0
`

type GetFineOverviewStatsRow struct {
	UnpaidCount             int32          `db:"unpaid_count" json:"unpaid_count"`
	PaidCount               int32          `db:"paid_count" json:"paid_count"`
	WaivedCount             int32          `db:"waived_count" json:"waived_count"`
	TotalUnpaid             pgtype.Numeric `db:"total_unpaid" json:"total_unpaid"`
	TotalCollected          pgtype.Numeric `db:"total_collected" json:"total_collected"`
	TotalWaived             pgtype.Numeric `db:"total_waived" json:"total_waived"`
	StudentsWithUnpaidFines int32          `db:"students_with_unpaid_fines" json:"students_with_unpaid_fines"`
}

func (q *Queries) GetFineOverviewStats(ctx context.Context) (GetFineOverviewStatsRow, error) {
	row := q.db.QueryRow(ctx, getFineOverviewStats)
	var i GetFineOverviewStatsRow
	err := row.Scan(
		&i.UnpaidCount,
		&i.PaidCount,
		&i.WaivedCount,
		&i.TotalUnpaid,
		&i.TotalCollected,
		&i.TotalWaived,
		&i.StudentsWithUnpaidFines,
	)
	return i, err
}

const getOverdueTransactionsForFineCalculation = `-- name: GetOverdueTransactionsForFineCalculation :many
SELECT
    t.id,
    t.student_id,
    t.book_id,
    t.due_date,
    t.fine_amount,
    GREATEST(EXTRACT(DAY FROM (NOW() - t.due_date))::int, 0) as days_overdue
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
WHERE t.due_date < NOW()
    AND t.returned_date IS NULL
    AND t.transaction_type = 'borrow'
    AND s.deleted_at IS NULL
    AND s.is_active = true
`

type GetOverdueTransactionsForFineCalculationRow struct {
	ID          int32            `db:"id" json:"id"`
	StudentID   int32            `db:"student_id" json:"student_id"`
	BookID      int32            `db:"book_id" json:"book_id"`
	DueDate     pgtype.Timestamp `db:"due_date" json:"due_date"`
	FineAmount  pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	DaysOverdue interface{}      `db:"days_overdue" json:"days_overdue"`
}

func (q *Queries) GetOverdueTransactionsForFineCalculation(ctx context.Context) ([]GetOverdueTransactionsForFineCalculationRow, error) {
	rows, err := q.db.Query(ctx, getOverdueTransactionsForFineCalculation)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOverdueTransactionsForFineCalculationRow{}
	for rows.Next() {
		var i GetOverdueTransactionsForFineCalculationRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.BookID,
			&i.DueDate,
			&i.FineAmount,
			&i.DaysOverdue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentsWithHighFines = `-- name: GetStudentsWithHighFines :many
SELECT
    s.id as student_id,
    s.student_id as student_code,
    CONCAT(s.first_name, ' ', s.last_name) as student_name,
    s.email,
    COALESCE(SUM(t.fine_amount), 0)::numeric as total_fines,
    COUNT(t.id)::int as fine_count
FROM students s
INNER JOIN transactions t ON s.id = t.student_id
WHERE t.fine_amount > 0
    AND t.fine_paid = false
    AND (COALESCE(t.fine_waived, false) = false)
    AND s.deleted_at IS NULL
GROUP BY s.id, s.student_id, s.first_name, s.last_name, s.email
HAVING COALESCE(SUM(t.fine_amount), 0) >= $1
ORDER BY total_fines DESC
`

type GetStudentsWithHighFinesRow struct {
	StudentID   int32          `db:"student_id" json:"student_id"`
	StudentCode string         `db:"student_code" json:"student_code"`
	StudentName interface{}    `db:"student_name" json:"student_name"`
	Email       pgtype.Text    `db:"email" json:"email"`
	TotalFines  pgtype.Numeric `db:"total_fines" json:"total_fines"`
	FineCount   int32          `db:"fine_count" json:"fine_count"`
}

func (q *Queries) GetStudentsWithHighFines(ctx context.Context, fineAmount pgtype.Numeric) ([]GetStudentsWithHighFinesRow, error) {
	rows, err := q.db.Query(ctx, getStudentsWithHighFines, fineAmount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentsWithHighFinesRow{}
	for rows.Next() {
		var i GetStudentsWithHighFinesRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentCode,
			&i.StudentName,
			&i.Email,
			&i.TotalFines,
			&i.FineCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalUnpaidFinesByStudent = `-- name: GetTotalUnpaidFinesByStudent :one
SELECT COALESCE(SUM(fine_amount), 0)::numeric as total
FROM transactions
WHERE student_id = $1
    AND fine_amount > 0
    AND fine_paid = false
    AND (COALESCE(fine_waived, false) = false)
`

func (q *Queries) GetTotalUnpaidFinesByStudent(ctx context.Context, studentID int32) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalUnpaidFinesByStudent, studentID)
	var total pgtype.Numeric
	err := row.Scan(&total)
	return total, err
}

const getUnpaidFinesByStudent = `-- name: GetUnpaidFinesByStudent :many
SELECT
    t.id as transaction_id,
    t.book_id,
    b.title as book_title,
    b.author as book_author,
    t.fine_amount,
    t.due_date,
    t.returned_date,
    GREATEST(EXTRACT(DAY FROM (COALESCE(t.returned_date, NOW()) - t.due_date))::int, 0) as days_overdue,
    t.created_at
FROM transactions t
INNER JOIN books b ON t.book_id = b.id
WHERE t.student_id = $1
    AND t.fine_amount > 0
    AND t.fine_paid = false
    AND (COALESCE(t.fine_waived, false) = false)
    AND b.deleted_at IS NULL
ORDER BY t.due_date ASC
`

type GetUnpaidFinesByStudentRow struct {
	TransactionID int32            `db:"transaction_id" json:"transaction_id"`
	BookID        int32            `db:"book_id" json:"book_id"`
	BookTitle     string           `db:"book_title" json:"book_title"`
	BookAuthor    string           `db:"book_author" json:"book_author"`
	FineAmount    pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	DueDate       pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate  pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	DaysOverdue   interface{}      `db:"days_overdue" json:"days_overdue"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) GetUnpaidFinesByStudent(ctx context.Context, studentID int32) ([]GetUnpaidFinesByStudentRow, error) {
	rows, err := q.db.Query(ctx, getUnpaidFinesByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUnpaidFinesByStudentRow{}
	for rows.Next() {
		var i GetUnpaidFinesByStudentRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.BookID,
			&i.BookTitle,
			&i.BookAuthor,
			&i.FineAmount,
			&i.DueDate,
			&i.ReturnedDate,
			&i.DaysOverdue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFines = `-- name: ListFines :many

SELECT
    t.id as transaction_id,
    t.student_id,
    s.student_id as student_code,
    CONCAT(s.first_name, ' ', s.last_name) as student_name,
    t.book_id,
    b.title as book_title,
    b.author as book_author,
    t.fine_amount,
    t.fine_paid,
    t.fine_paid_at,
    COALESCE(t.fine_waived, false) as fine_waived,
    t.fine_waived_at,
    t.fine_waived_by,
    t.fine_waived_reason,
    t.due_date,
    t.returned_date,
    GREATEST(EXTRACT(DAY FROM (COALESCE(t.returned_date, NOW()) - t.due_date))::int, 0) as days_overdue,
    t.created_at
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
INNER JOIN books b ON t.book_id = b.id
WHERE t.fine_amount > 0
    AND s.deleted_at IS NULL
    AND b.deleted_at IS NULL
    AND ($3::bool IS NULL OR t.fine_paid = $3::bool)
    AND ($4::int IS NULL OR t.student_id = $4::int)
ORDER BY
    CASE WHEN t.fine_paid = false THEN 0 ELSE 1 END,
    t.created_at DESC
LIMIT $1 OFFSET $2
`

type ListFinesParams struct {
	Limit     int32       `db:"limit" json:"limit"`
	Offset    int32       `db:"offset" json:"offset"`
	Paid      pgtype.Bool `db:"paid" json:"paid"`
	StudentID pgtype.Int4 `db:"student_id" json:"student_id"`
}

type ListFinesRow struct {
	TransactionID    int32            `db:"transaction_id" json:"transaction_id"`
	StudentID        int32            `db:"student_id" json:"student_id"`
	StudentCode      string           `db:"student_code" json:"student_code"`
	StudentName      interface{}      `db:"student_name" json:"student_name"`
	BookID           int32            `db:"book_id" json:"book_id"`
	BookTitle        string           `db:"book_title" json:"book_title"`
	BookAuthor       string           `db:"book_author" json:"book_author"`
	FineAmount       pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid         pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	FinePaidAt       pgtype.Timestamp `db:"fine_paid_at" json:"fine_paid_at"`
	FineWaived       bool             `db:"fine_waived" json:"fine_waived"`
	FineWaivedAt     pgtype.Timestamp `db:"fine_waived_at" json:"fine_waived_at"`
	FineWaivedBy     pgtype.Int4      `db:"fine_waived_by" json:"fine_waived_by"`
	FineWaivedReason pgtype.Text      `db:"fine_waived_reason" json:"fine_waived_reason"`
	DueDate          pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate     pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	DaysOverdue      interface{}      `db:"days_overdue" json:"days_overdue"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
}

// Fines Management Queries
func (q *Queries) ListFines(ctx context.Context, arg ListFinesParams) ([]ListFinesRow, error) {
	rows, err := q.db.Query(ctx, listFines,
		arg.Limit,
		arg.Offset,
		arg.Paid,
		arg.StudentID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFinesRow{}
	for rows.Next() {
		var i ListFinesRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.StudentID,
			&i.StudentCode,
			&i.StudentName,
			&i.BookID,
			&i.BookTitle,
			&i.BookAuthor,
			&i.FineAmount,
			&i.FinePaid,
			&i.FinePaidAt,
			&i.FineWaived,
			&i.FineWaivedAt,
			&i.FineWaivedBy,
			&i.FineWaivedReason,
			&i.DueDate,
			&i.ReturnedDate,
			&i.DaysOverdue,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const payFineByTransactionID = `-- name: PayFineByTransactionID :one
UPDATE transactions
SET fine_paid = true,
    fine_paid_at = NOW(),
    updated_at = NOW()
WHERE id = $1
    AND fine_amount > 0
    AND fine_paid = false
RETURNING id, student_id, book_id, transaction_type, transaction_date, due_date, returned_date, librarian_id, fine_amount, fine_paid, notes, created_at, updated_at, return_condition, condition_notes, fine_waived, fine_waived_at, fine_waived_by, fine_waived_reason, fine_paid_at, copy_id, status, renewal_count, last_renewed_at, last_renewed_by
`

func (q *Queries) PayFineByTransactionID(ctx context.Context, id int32) (Transaction, error) {
	row := q.db.QueryRow(ctx, payFineByTransactionID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.DueDate,
		&i.ReturnedDate,
		&i.LibrarianID,
		&i.FineAmount,
		&i.FinePaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReturnCondition,
		&i.ConditionNotes,
		&i.FineWaived,
		&i.FineWaivedAt,
		&i.FineWaivedBy,
		&i.FineWaivedReason,
		&i.FinePaidAt,
		&i.CopyID,
		&i.Status,
		&i.RenewalCount,
		&i.LastRenewedAt,
		&i.LastRenewedBy,
	)
	return i, err
}

const updateFineAmount = `-- name: UpdateFineAmount :exec
UPDATE transactions
SET fine_amount = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateFineAmountParams struct {
	ID         int32          `db:"id" json:"id"`
	FineAmount pgtype.Numeric `db:"fine_amount" json:"fine_amount"`
}

func (q *Queries) UpdateFineAmount(ctx context.Context, arg UpdateFineAmountParams) error {
	_, err := q.db.Exec(ctx, updateFineAmount, arg.ID, arg.FineAmount)
	return err
}

const waiveFineByTransactionID = `-- name: WaiveFineByTransactionID :one
UPDATE transactions
SET fine_waived = true,
    fine_waived_at = NOW(),
    fine_waived_by = $2,
    fine_waived_reason = $3,
    fine_paid = true,
    fine_paid_at = NOW(),
    updated_at = NOW()
WHERE id = $1
    AND fine_amount > 0
    AND fine_paid = false
RETURNING id, student_id, book_id, transaction_type, transaction_date, due_date, returned_date, librarian_id, fine_amount, fine_paid, notes, created_at, updated_at, return_condition, condition_notes, fine_waived, fine_waived_at, fine_waived_by, fine_waived_reason, fine_paid_at, copy_id, status, renewal_count, last_renewed_at, last_renewed_by
`

type WaiveFineByTransactionIDParams struct {
	ID               int32       `db:"id" json:"id"`
	FineWaivedBy     pgtype.Int4 `db:"fine_waived_by" json:"fine_waived_by"`
	FineWaivedReason pgtype.Text `db:"fine_waived_reason" json:"fine_waived_reason"`
}

func (q *Queries) WaiveFineByTransactionID(ctx context.Context, arg WaiveFineByTransactionIDParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, waiveFineByTransactionID, arg.ID, arg.FineWaivedBy, arg.FineWaivedReason)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.DueDate,
		&i.ReturnedDate,
		&i.LibrarianID,
		&i.FineAmount,
		&i.FinePaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReturnCondition,
		&i.ConditionNotes,
		&i.FineWaived,
		&i.FineWaivedAt,
		&i.FineWaivedBy,
		&i.FineWaivedReason,
		&i.FinePaidAt,
		&i.CopyID,
		&i.Status,
		&i.RenewalCount,
		&i.LastRenewedAt,
		&i.LastRenewedBy,
	)
	return i, err
}
