// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: import_export.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredExportFiles = `-- name: CleanupExpiredExportFiles :many
DELETE FROM export_files
WHERE expires_at IS NOT NULL AND expires_at <= NOW()
RETURNING id, import_history_id, file_path, file_format, download_count, last_downloaded_at, expires_at, created_at
`

func (q *Queries) CleanupExpiredExportFiles(ctx context.Context) ([]ExportFile, error) {
	rows, err := q.db.Query(ctx, cleanupExpiredExportFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportFile{}
	for rows.Next() {
		var i ExportFile
		if err := rows.Scan(
			&i.ID,
			&i.ImportHistoryID,
			&i.FilePath,
			&i.FileFormat,
			&i.DownloadCount,
			&i.LastDownloadedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countImportHistoryByFilters = `-- name: CountImportHistoryByFilters :one
SELECT COUNT(*) FROM import_history
WHERE 
    user_id = $1
    AND ($2 = '' OR operation_type = $2)
    AND ($3 = '' OR entity_type = $3)
    AND ($4 = '' OR status = $4)
`

type CountImportHistoryByFiltersParams struct {
	UserID  int32       `db:"user_id" json:"user_id"`
	Column2 interface{} `db:"column_2" json:"column_2"`
	Column3 interface{} `db:"column_3" json:"column_3"`
	Column4 interface{} `db:"column_4" json:"column_4"`
}

func (q *Queries) CountImportHistoryByFilters(ctx context.Context, arg CountImportHistoryByFiltersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countImportHistoryByFilters,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExportFile = `-- name: CreateExportFile :one
INSERT INTO export_files (
    import_history_id,
    file_path,
    file_format,
    download_count,
    last_downloaded_at,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, import_history_id, file_path, file_format, download_count, last_downloaded_at, expires_at, created_at
`

type CreateExportFileParams struct {
	ImportHistoryID  int32            `db:"import_history_id" json:"import_history_id"`
	FilePath         string           `db:"file_path" json:"file_path"`
	FileFormat       string           `db:"file_format" json:"file_format"`
	DownloadCount    int32            `db:"download_count" json:"download_count"`
	LastDownloadedAt pgtype.Timestamp `db:"last_downloaded_at" json:"last_downloaded_at"`
	ExpiresAt        pgtype.Timestamp `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateExportFile(ctx context.Context, arg CreateExportFileParams) (ExportFile, error) {
	row := q.db.QueryRow(ctx, createExportFile,
		arg.ImportHistoryID,
		arg.FilePath,
		arg.FileFormat,
		arg.DownloadCount,
		arg.LastDownloadedAt,
		arg.ExpiresAt,
	)
	var i ExportFile
	err := row.Scan(
		&i.ID,
		&i.ImportHistoryID,
		&i.FilePath,
		&i.FileFormat,
		&i.DownloadCount,
		&i.LastDownloadedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createImportError = `-- name: CreateImportError :one
INSERT INTO import_errors (
    import_history_id,
    row_number,
    field_name,
    error_type,
    error_message,
    row_data
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, import_history_id, row_number, field_name, error_type, error_message, row_data, created_at
`

type CreateImportErrorParams struct {
	ImportHistoryID int32       `db:"import_history_id" json:"import_history_id"`
	RowNumber       int32       `db:"row_number" json:"row_number"`
	FieldName       pgtype.Text `db:"field_name" json:"field_name"`
	ErrorType       string      `db:"error_type" json:"error_type"`
	ErrorMessage    string      `db:"error_message" json:"error_message"`
	RowData         []byte      `db:"row_data" json:"row_data"`
}

func (q *Queries) CreateImportError(ctx context.Context, arg CreateImportErrorParams) (ImportError, error) {
	row := q.db.QueryRow(ctx, createImportError,
		arg.ImportHistoryID,
		arg.RowNumber,
		arg.FieldName,
		arg.ErrorType,
		arg.ErrorMessage,
		arg.RowData,
	)
	var i ImportError
	err := row.Scan(
		&i.ID,
		&i.ImportHistoryID,
		&i.RowNumber,
		&i.FieldName,
		&i.ErrorType,
		&i.ErrorMessage,
		&i.RowData,
		&i.CreatedAt,
	)
	return i, err
}

const createImportHistory = `-- name: CreateImportHistory :one
INSERT INTO import_history (
    operation_type,
    entity_type,
    filename,
    original_filename,
    file_size,
    total_records,
    processed_records,
    successful_records,
    failed_records,
    status,
    error_message,
    error_details,
    user_id,
    started_at,
    processing_duration
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
) RETURNING id, operation_type, entity_type, filename, original_filename, file_size, total_records, processed_records, successful_records, failed_records, status, error_message, error_details, user_id, started_at, completed_at, processing_duration, created_at, updated_at
`

type CreateImportHistoryParams struct {
	OperationType      string           `db:"operation_type" json:"operation_type"`
	EntityType         string           `db:"entity_type" json:"entity_type"`
	Filename           string           `db:"filename" json:"filename"`
	OriginalFilename   string           `db:"original_filename" json:"original_filename"`
	FileSize           int64            `db:"file_size" json:"file_size"`
	TotalRecords       int32            `db:"total_records" json:"total_records"`
	ProcessedRecords   int32            `db:"processed_records" json:"processed_records"`
	SuccessfulRecords  int32            `db:"successful_records" json:"successful_records"`
	FailedRecords      int32            `db:"failed_records" json:"failed_records"`
	Status             string           `db:"status" json:"status"`
	ErrorMessage       pgtype.Text      `db:"error_message" json:"error_message"`
	ErrorDetails       []byte           `db:"error_details" json:"error_details"`
	UserID             int32            `db:"user_id" json:"user_id"`
	StartedAt          pgtype.Timestamp `db:"started_at" json:"started_at"`
	ProcessingDuration pgtype.Int4      `db:"processing_duration" json:"processing_duration"`
}

func (q *Queries) CreateImportHistory(ctx context.Context, arg CreateImportHistoryParams) (ImportHistory, error) {
	row := q.db.QueryRow(ctx, createImportHistory,
		arg.OperationType,
		arg.EntityType,
		arg.Filename,
		arg.OriginalFilename,
		arg.FileSize,
		arg.TotalRecords,
		arg.ProcessedRecords,
		arg.SuccessfulRecords,
		arg.FailedRecords,
		arg.Status,
		arg.ErrorMessage,
		arg.ErrorDetails,
		arg.UserID,
		arg.StartedAt,
		arg.ProcessingDuration,
	)
	var i ImportHistory
	err := row.Scan(
		&i.ID,
		&i.OperationType,
		&i.EntityType,
		&i.Filename,
		&i.OriginalFilename,
		&i.FileSize,
		&i.TotalRecords,
		&i.ProcessedRecords,
		&i.SuccessfulRecords,
		&i.FailedRecords,
		&i.Status,
		&i.ErrorMessage,
		&i.ErrorDetails,
		&i.UserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ProcessingDuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveExportFiles = `-- name: GetActiveExportFiles :many
SELECT id, import_history_id, file_path, file_format, download_count, last_downloaded_at, expires_at, created_at FROM export_files
WHERE expires_at IS NULL OR expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) GetActiveExportFiles(ctx context.Context) ([]ExportFile, error) {
	rows, err := q.db.Query(ctx, getActiveExportFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportFile{}
	for rows.Next() {
		var i ExportFile
		if err := rows.Scan(
			&i.ID,
			&i.ImportHistoryID,
			&i.FilePath,
			&i.FileFormat,
			&i.DownloadCount,
			&i.LastDownloadedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExportFilesByHistoryID = `-- name: GetExportFilesByHistoryID :many
SELECT id, import_history_id, file_path, file_format, download_count, last_downloaded_at, expires_at, created_at FROM export_files
WHERE import_history_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetExportFilesByHistoryID(ctx context.Context, importHistoryID int32) ([]ExportFile, error) {
	rows, err := q.db.Query(ctx, getExportFilesByHistoryID, importHistoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportFile{}
	for rows.Next() {
		var i ExportFile
		if err := rows.Scan(
			&i.ID,
			&i.ImportHistoryID,
			&i.FilePath,
			&i.FileFormat,
			&i.DownloadCount,
			&i.LastDownloadedAt,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImportErrorsByHistoryID = `-- name: GetImportErrorsByHistoryID :many
SELECT id, import_history_id, row_number, field_name, error_type, error_message, row_data, created_at FROM import_errors
WHERE import_history_id = $1
ORDER BY row_number
`

func (q *Queries) GetImportErrorsByHistoryID(ctx context.Context, importHistoryID int32) ([]ImportError, error) {
	rows, err := q.db.Query(ctx, getImportErrorsByHistoryID, importHistoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportError{}
	for rows.Next() {
		var i ImportError
		if err := rows.Scan(
			&i.ID,
			&i.ImportHistoryID,
			&i.RowNumber,
			&i.FieldName,
			&i.ErrorType,
			&i.ErrorMessage,
			&i.RowData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImportHistoryByFilters = `-- name: GetImportHistoryByFilters :many
SELECT id, operation_type, entity_type, filename, original_filename, file_size, total_records, processed_records, successful_records, failed_records, status, error_message, error_details, user_id, started_at, completed_at, processing_duration, created_at, updated_at FROM import_history
WHERE 
    user_id = $1
    AND ($2 = '' OR operation_type = $2)
    AND ($3 = '' OR entity_type = $3)
    AND ($4 = '' OR status = $4)
ORDER BY created_at DESC
LIMIT $5 OFFSET $6
`

type GetImportHistoryByFiltersParams struct {
	UserID  int32       `db:"user_id" json:"user_id"`
	Column2 interface{} `db:"column_2" json:"column_2"`
	Column3 interface{} `db:"column_3" json:"column_3"`
	Column4 interface{} `db:"column_4" json:"column_4"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

func (q *Queries) GetImportHistoryByFilters(ctx context.Context, arg GetImportHistoryByFiltersParams) ([]ImportHistory, error) {
	rows, err := q.db.Query(ctx, getImportHistoryByFilters,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportHistory{}
	for rows.Next() {
		var i ImportHistory
		if err := rows.Scan(
			&i.ID,
			&i.OperationType,
			&i.EntityType,
			&i.Filename,
			&i.OriginalFilename,
			&i.FileSize,
			&i.TotalRecords,
			&i.ProcessedRecords,
			&i.SuccessfulRecords,
			&i.FailedRecords,
			&i.Status,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.UserID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ProcessingDuration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImportHistoryByID = `-- name: GetImportHistoryByID :one
SELECT id, operation_type, entity_type, filename, original_filename, file_size, total_records, processed_records, successful_records, failed_records, status, error_message, error_details, user_id, started_at, completed_at, processing_duration, created_at, updated_at FROM import_history
WHERE id = $1
`

func (q *Queries) GetImportHistoryByID(ctx context.Context, id int32) (ImportHistory, error) {
	row := q.db.QueryRow(ctx, getImportHistoryByID, id)
	var i ImportHistory
	err := row.Scan(
		&i.ID,
		&i.OperationType,
		&i.EntityType,
		&i.Filename,
		&i.OriginalFilename,
		&i.FileSize,
		&i.TotalRecords,
		&i.ProcessedRecords,
		&i.SuccessfulRecords,
		&i.FailedRecords,
		&i.Status,
		&i.ErrorMessage,
		&i.ErrorDetails,
		&i.UserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ProcessingDuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getImportHistoryByUserID = `-- name: GetImportHistoryByUserID :many
SELECT id, operation_type, entity_type, filename, original_filename, file_size, total_records, processed_records, successful_records, failed_records, status, error_message, error_details, user_id, started_at, completed_at, processing_duration, created_at, updated_at FROM import_history
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetImportHistoryByUserIDParams struct {
	UserID int32 `db:"user_id" json:"user_id"`
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) GetImportHistoryByUserID(ctx context.Context, arg GetImportHistoryByUserIDParams) ([]ImportHistory, error) {
	rows, err := q.db.Query(ctx, getImportHistoryByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImportHistory{}
	for rows.Next() {
		var i ImportHistory
		if err := rows.Scan(
			&i.ID,
			&i.OperationType,
			&i.EntityType,
			&i.Filename,
			&i.OriginalFilename,
			&i.FileSize,
			&i.TotalRecords,
			&i.ProcessedRecords,
			&i.SuccessfulRecords,
			&i.FailedRecords,
			&i.Status,
			&i.ErrorMessage,
			&i.ErrorDetails,
			&i.UserID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ProcessingDuration,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImportHistoryStats = `-- name: GetImportHistoryStats :one
SELECT 
    COUNT(*) as total_operations,
    COUNT(*) FILTER (WHERE status = 'completed') as completed_operations,
    COUNT(*) FILTER (WHERE status = 'failed') as failed_operations,
    COUNT(*) FILTER (WHERE status = 'processing') as processing_operations,
    COALESCE(SUM(successful_records), 0) as total_successful_records,
    COALESCE(SUM(failed_records), 0) as total_failed_records
FROM import_history
WHERE user_id = $1
`

type GetImportHistoryStatsRow struct {
	TotalOperations        int64       `db:"total_operations" json:"total_operations"`
	CompletedOperations    int64       `db:"completed_operations" json:"completed_operations"`
	FailedOperations       int64       `db:"failed_operations" json:"failed_operations"`
	ProcessingOperations   int64       `db:"processing_operations" json:"processing_operations"`
	TotalSuccessfulRecords interface{} `db:"total_successful_records" json:"total_successful_records"`
	TotalFailedRecords     interface{} `db:"total_failed_records" json:"total_failed_records"`
}

func (q *Queries) GetImportHistoryStats(ctx context.Context, userID int32) (GetImportHistoryStatsRow, error) {
	row := q.db.QueryRow(ctx, getImportHistoryStats, userID)
	var i GetImportHistoryStatsRow
	err := row.Scan(
		&i.TotalOperations,
		&i.CompletedOperations,
		&i.FailedOperations,
		&i.ProcessingOperations,
		&i.TotalSuccessfulRecords,
		&i.TotalFailedRecords,
	)
	return i, err
}

const updateExportFileDownload = `-- name: UpdateExportFileDownload :one
UPDATE export_files
SET 
    download_count = download_count + 1,
    last_downloaded_at = NOW()
WHERE id = $1
RETURNING id, import_history_id, file_path, file_format, download_count, last_downloaded_at, expires_at, created_at
`

func (q *Queries) UpdateExportFileDownload(ctx context.Context, id int32) (ExportFile, error) {
	row := q.db.QueryRow(ctx, updateExportFileDownload, id)
	var i ExportFile
	err := row.Scan(
		&i.ID,
		&i.ImportHistoryID,
		&i.FilePath,
		&i.FileFormat,
		&i.DownloadCount,
		&i.LastDownloadedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateImportHistory = `-- name: UpdateImportHistory :one
UPDATE import_history 
SET 
    total_records = COALESCE($2, total_records),
    processed_records = COALESCE($3, processed_records),
    successful_records = COALESCE($4, successful_records),
    failed_records = COALESCE($5, failed_records),
    status = COALESCE($6, status),
    error_message = COALESCE($7, error_message),
    error_details = COALESCE($8, error_details),
    completed_at = COALESCE($9, completed_at),
    processing_duration = COALESCE($10, processing_duration),
    updated_at = NOW()
WHERE id = $1
RETURNING id, operation_type, entity_type, filename, original_filename, file_size, total_records, processed_records, successful_records, failed_records, status, error_message, error_details, user_id, started_at, completed_at, processing_duration, created_at, updated_at
`

type UpdateImportHistoryParams struct {
	ID                 int32            `db:"id" json:"id"`
	TotalRecords       pgtype.Int4      `db:"total_records" json:"total_records"`
	ProcessedRecords   pgtype.Int4      `db:"processed_records" json:"processed_records"`
	SuccessfulRecords  pgtype.Int4      `db:"successful_records" json:"successful_records"`
	FailedRecords      pgtype.Int4      `db:"failed_records" json:"failed_records"`
	Status             pgtype.Text      `db:"status" json:"status"`
	ErrorMessage       pgtype.Text      `db:"error_message" json:"error_message"`
	ErrorDetails       []byte           `db:"error_details" json:"error_details"`
	CompletedAt        pgtype.Timestamp `db:"completed_at" json:"completed_at"`
	ProcessingDuration pgtype.Int4      `db:"processing_duration" json:"processing_duration"`
}

func (q *Queries) UpdateImportHistory(ctx context.Context, arg UpdateImportHistoryParams) (ImportHistory, error) {
	row := q.db.QueryRow(ctx, updateImportHistory,
		arg.ID,
		arg.TotalRecords,
		arg.ProcessedRecords,
		arg.SuccessfulRecords,
		arg.FailedRecords,
		arg.Status,
		arg.ErrorMessage,
		arg.ErrorDetails,
		arg.CompletedAt,
		arg.ProcessingDuration,
	)
	var i ImportHistory
	err := row.Scan(
		&i.ID,
		&i.OperationType,
		&i.EntityType,
		&i.Filename,
		&i.OriginalFilename,
		&i.FileSize,
		&i.TotalRecords,
		&i.ProcessedRecords,
		&i.SuccessfulRecords,
		&i.FailedRecords,
		&i.Status,
		&i.ErrorMessage,
		&i.ErrorDetails,
		&i.UserID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ProcessingDuration,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
