// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        int32            `db:"id" json:"id"`
	TableName string           `db:"table_name" json:"table_name"`
	RecordID  int32            `db:"record_id" json:"record_id"`
	Action    string           `db:"action" json:"action"`
	OldValues []byte           `db:"old_values" json:"old_values"`
	NewValues []byte           `db:"new_values" json:"new_values"`
	UserID    pgtype.Int4      `db:"user_id" json:"user_id"`
	UserType  pgtype.Text      `db:"user_type" json:"user_type"`
	IpAddress *netip.Addr      `db:"ip_address" json:"ip_address"`
	UserAgent pgtype.Text      `db:"user_agent" json:"user_agent"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Book struct {
	ID              int32            `db:"id" json:"id"`
	BookID          string           `db:"book_id" json:"book_id"`
	Isbn            pgtype.Text      `db:"isbn" json:"isbn"`
	Title           string           `db:"title" json:"title"`
	Author          string           `db:"author" json:"author"`
	Publisher       pgtype.Text      `db:"publisher" json:"publisher"`
	PublishedYear   pgtype.Int4      `db:"published_year" json:"published_year"`
	Genre           pgtype.Text      `db:"genre" json:"genre"`
	Description     pgtype.Text      `db:"description" json:"description"`
	CoverImageUrl   pgtype.Text      `db:"cover_image_url" json:"cover_image_url"`
	TotalCopies     pgtype.Int4      `db:"total_copies" json:"total_copies"`
	AvailableCopies pgtype.Int4      `db:"available_copies" json:"available_copies"`
	ShelfLocation   pgtype.Text      `db:"shelf_location" json:"shelf_location"`
	IsActive        pgtype.Bool      `db:"is_active" json:"is_active"`
	DeletedAt       pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Notification struct {
	ID            int32            `db:"id" json:"id"`
	RecipientID   int32            `db:"recipient_id" json:"recipient_id"`
	RecipientType string           `db:"recipient_type" json:"recipient_type"`
	Type          string           `db:"type" json:"type"`
	Title         string           `db:"title" json:"title"`
	Message       string           `db:"message" json:"message"`
	IsRead        pgtype.Bool      `db:"is_read" json:"is_read"`
	SentAt        pgtype.Timestamp `db:"sent_at" json:"sent_at"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Reservation struct {
	ID          int32            `db:"id" json:"id"`
	StudentID   int32            `db:"student_id" json:"student_id"`
	BookID      int32            `db:"book_id" json:"book_id"`
	ReservedAt  pgtype.Timestamp `db:"reserved_at" json:"reserved_at"`
	ExpiresAt   pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	Status      pgtype.Text      `db:"status" json:"status"`
	FulfilledAt pgtype.Timestamp `db:"fulfilled_at" json:"fulfilled_at"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Student struct {
	ID             int32            `db:"id" json:"id"`
	StudentID      string           `db:"student_id" json:"student_id"`
	FirstName      string           `db:"first_name" json:"first_name"`
	LastName       string           `db:"last_name" json:"last_name"`
	Email          pgtype.Text      `db:"email" json:"email"`
	Phone          pgtype.Text      `db:"phone" json:"phone"`
	YearOfStudy    int32            `db:"year_of_study" json:"year_of_study"`
	Department     pgtype.Text      `db:"department" json:"department"`
	EnrollmentDate pgtype.Date      `db:"enrollment_date" json:"enrollment_date"`
	PasswordHash   pgtype.Text      `db:"password_hash" json:"password_hash"`
	IsActive       pgtype.Bool      `db:"is_active" json:"is_active"`
	DeletedAt      pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Transaction struct {
	ID              int32            `db:"id" json:"id"`
	StudentID       int32            `db:"student_id" json:"student_id"`
	BookID          int32            `db:"book_id" json:"book_id"`
	TransactionType string           `db:"transaction_type" json:"transaction_type"`
	TransactionDate pgtype.Timestamp `db:"transaction_date" json:"transaction_date"`
	DueDate         pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate    pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	LibrarianID     pgtype.Int4      `db:"librarian_id" json:"librarian_id"`
	FineAmount      pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid        pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	Notes           pgtype.Text      `db:"notes" json:"notes"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID           int32            `db:"id" json:"id"`
	Username     string           `db:"username" json:"username"`
	Email        string           `db:"email" json:"email"`
	PasswordHash string           `db:"password_hash" json:"password_hash"`
	Role         pgtype.Text      `db:"role" json:"role"`
	IsActive     pgtype.Bool      `db:"is_active" json:"is_active"`
	LastLogin    pgtype.Timestamp `db:"last_login" json:"last_login"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
