// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        int32            `db:"id" json:"id"`
	TableName string           `db:"table_name" json:"table_name"`
	RecordID  int32            `db:"record_id" json:"record_id"`
	Action    string           `db:"action" json:"action"`
	OldValues []byte           `db:"old_values" json:"old_values"`
	NewValues []byte           `db:"new_values" json:"new_values"`
	UserID    pgtype.Int4      `db:"user_id" json:"user_id"`
	UserType  pgtype.Text      `db:"user_type" json:"user_type"`
	IpAddress *netip.Addr      `db:"ip_address" json:"ip_address"`
	UserAgent pgtype.Text      `db:"user_agent" json:"user_agent"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Author struct {
	ID        int32            `db:"id" json:"id"`
	Name      string           `db:"name" json:"name"`
	Bio       pgtype.Text      `db:"bio" json:"bio"`
	CreatedAt pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Book struct {
	ID              int32            `db:"id" json:"id"`
	BookID          string           `db:"book_id" json:"book_id"`
	Isbn            pgtype.Text      `db:"isbn" json:"isbn"`
	Title           string           `db:"title" json:"title"`
	Author          string           `db:"author" json:"author"`
	Publisher       pgtype.Text      `db:"publisher" json:"publisher"`
	PublishedYear   pgtype.Int4      `db:"published_year" json:"published_year"`
	Genre           pgtype.Text      `db:"genre" json:"genre"`
	Description     pgtype.Text      `db:"description" json:"description"`
	CoverImageUrl   pgtype.Text      `db:"cover_image_url" json:"cover_image_url"`
	TotalCopies     pgtype.Int4      `db:"total_copies" json:"total_copies"`
	AvailableCopies pgtype.Int4      `db:"available_copies" json:"available_copies"`
	ShelfLocation   pgtype.Text      `db:"shelf_location" json:"shelf_location"`
	IsActive        pgtype.Bool      `db:"is_active" json:"is_active"`
	DeletedAt       pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	Condition       pgtype.Text      `db:"condition" json:"condition"`
	CategoryID      pgtype.Int4      `db:"category_id" json:"category_id"`
	SeriesID        pgtype.Int4      `db:"series_id" json:"series_id"`
	SeriesNumber    pgtype.Int4      `db:"series_number" json:"series_number"`
	Language        pgtype.Text      `db:"language" json:"language"`
	PageCount       pgtype.Int4      `db:"page_count" json:"page_count"`
	Edition         pgtype.Text      `db:"edition" json:"edition"`
	Format          pgtype.Text      `db:"format" json:"format"`
}

type BookAuthor struct {
	BookID      int32       `db:"book_id" json:"book_id"`
	AuthorID    int32       `db:"author_id" json:"author_id"`
	AuthorOrder pgtype.Int4 `db:"author_order" json:"author_order"`
}

type BookCopy struct {
	ID              int32            `db:"id" json:"id"`
	BookID          int32            `db:"book_id" json:"book_id"`
	CopyNumber      string           `db:"copy_number" json:"copy_number"`
	Barcode         pgtype.Text      `db:"barcode" json:"barcode"`
	Condition       pgtype.Text      `db:"condition" json:"condition"`
	AcquisitionDate pgtype.Date      `db:"acquisition_date" json:"acquisition_date"`
	Status          pgtype.Text      `db:"status" json:"status"`
	Notes           pgtype.Text      `db:"notes" json:"notes"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type BookSeries struct {
	ID          int32            `db:"id" json:"id"`
	Name        string           `db:"name" json:"name"`
	Description pgtype.Text      `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Category struct {
	ID          int32            `db:"id" json:"id"`
	Name        string           `db:"name" json:"name"`
	Description pgtype.Text      `db:"description" json:"description"`
	IsActive    pgtype.Bool      `db:"is_active" json:"is_active"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

// Tracks email delivery status and attempts for notifications
type EmailDelivery struct {
	ID             int32  `db:"id" json:"id"`
	NotificationID int32  `db:"notification_id" json:"notification_id"`
	EmailAddress   string `db:"email_address" json:"email_address"`
	// Email delivery status: pending, sent, delivered, failed, bounced
	Status       string           `db:"status" json:"status"`
	SentAt       pgtype.Timestamp `db:"sent_at" json:"sent_at"`
	DeliveredAt  pgtype.Timestamp `db:"delivered_at" json:"delivered_at"`
	FailedAt     pgtype.Timestamp `db:"failed_at" json:"failed_at"`
	ErrorMessage pgtype.Text      `db:"error_message" json:"error_message"`
	// Number of delivery attempts made
	RetryCount pgtype.Int4 `db:"retry_count" json:"retry_count"`
	MaxRetries pgtype.Int4 `db:"max_retries" json:"max_retries"`
	// External email provider message ID for tracking
	ProviderMessageID pgtype.Text `db:"provider_message_id" json:"provider_message_id"`
	// Additional delivery information in JSON format
	DeliveryMetadata []byte           `db:"delivery_metadata" json:"delivery_metadata"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

// Queue for processing email notifications with priority and retry support
type EmailQueue struct {
	ID             int32 `db:"id" json:"id"`
	NotificationID int32 `db:"notification_id" json:"notification_id"`
	// Processing priority: 1 (highest) to 10 (lowest)
	Priority     pgtype.Int4      `db:"priority" json:"priority"`
	ScheduledFor pgtype.Timestamp `db:"scheduled_for" json:"scheduled_for"`
	Attempts     pgtype.Int4      `db:"attempts" json:"attempts"`
	MaxAttempts  pgtype.Int4      `db:"max_attempts" json:"max_attempts"`
	// Queue item status: pending, processing, completed, failed, cancelled
	Status                pgtype.Text      `db:"status" json:"status"`
	ErrorMessage          pgtype.Text      `db:"error_message" json:"error_message"`
	ProcessingStartedAt   pgtype.Timestamp `db:"processing_started_at" json:"processing_started_at"`
	ProcessingCompletedAt pgtype.Timestamp `db:"processing_completed_at" json:"processing_completed_at"`
	// ID of worker processing this queue item
	WorkerID pgtype.Text `db:"worker_id" json:"worker_id"`
	// Additional queue processing information in JSON format
	QueueMetadata []byte           `db:"queue_metadata" json:"queue_metadata"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type ExportFile struct {
	ID               int32            `db:"id" json:"id"`
	ImportHistoryID  int32            `db:"import_history_id" json:"import_history_id"`
	FilePath         string           `db:"file_path" json:"file_path"`
	FileFormat       string           `db:"file_format" json:"file_format"`
	DownloadCount    int32            `db:"download_count" json:"download_count"`
	LastDownloadedAt pgtype.Timestamp `db:"last_downloaded_at" json:"last_downloaded_at"`
	ExpiresAt        pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type ImportError struct {
	ID              int32            `db:"id" json:"id"`
	ImportHistoryID int32            `db:"import_history_id" json:"import_history_id"`
	RowNumber       int32            `db:"row_number" json:"row_number"`
	FieldName       pgtype.Text      `db:"field_name" json:"field_name"`
	ErrorType       string           `db:"error_type" json:"error_type"`
	ErrorMessage    string           `db:"error_message" json:"error_message"`
	RowData         []byte           `db:"row_data" json:"row_data"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type ImportHistory struct {
	ID                 int32            `db:"id" json:"id"`
	OperationType      string           `db:"operation_type" json:"operation_type"`
	EntityType         string           `db:"entity_type" json:"entity_type"`
	Filename           string           `db:"filename" json:"filename"`
	OriginalFilename   string           `db:"original_filename" json:"original_filename"`
	FileSize           int64            `db:"file_size" json:"file_size"`
	TotalRecords       int32            `db:"total_records" json:"total_records"`
	ProcessedRecords   int32            `db:"processed_records" json:"processed_records"`
	SuccessfulRecords  int32            `db:"successful_records" json:"successful_records"`
	FailedRecords      int32            `db:"failed_records" json:"failed_records"`
	Status             string           `db:"status" json:"status"`
	ErrorMessage       pgtype.Text      `db:"error_message" json:"error_message"`
	ErrorDetails       []byte           `db:"error_details" json:"error_details"`
	UserID             int32            `db:"user_id" json:"user_id"`
	StartedAt          pgtype.Timestamp `db:"started_at" json:"started_at"`
	CompletedAt        pgtype.Timestamp `db:"completed_at" json:"completed_at"`
	ProcessingDuration pgtype.Int4      `db:"processing_duration" json:"processing_duration"`
	CreatedAt          pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt          pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Notification struct {
	ID            int32            `db:"id" json:"id"`
	RecipientID   int32            `db:"recipient_id" json:"recipient_id"`
	RecipientType string           `db:"recipient_type" json:"recipient_type"`
	Type          string           `db:"type" json:"type"`
	Title         string           `db:"title" json:"title"`
	Message       string           `db:"message" json:"message"`
	IsRead        pgtype.Bool      `db:"is_read" json:"is_read"`
	SentAt        pgtype.Timestamp `db:"sent_at" json:"sent_at"`
	CreatedAt     pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Permission struct {
	ID          int32            `db:"id" json:"id"`
	Code        string           `db:"code" json:"code"`
	Name        string           `db:"name" json:"name"`
	Description pgtype.Text      `db:"description" json:"description"`
	Category    string           `db:"category" json:"category"`
	IsSystem    pgtype.Bool      `db:"is_system" json:"is_system"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type Reservation struct {
	ID          int32            `db:"id" json:"id"`
	StudentID   int32            `db:"student_id" json:"student_id"`
	BookID      int32            `db:"book_id" json:"book_id"`
	ReservedAt  pgtype.Timestamp `db:"reserved_at" json:"reserved_at"`
	ExpiresAt   pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	Status      pgtype.Text      `db:"status" json:"status"`
	FulfilledAt pgtype.Timestamp `db:"fulfilled_at" json:"fulfilled_at"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type RolePermission struct {
	ID           int32            `db:"id" json:"id"`
	Role         string           `db:"role" json:"role"`
	PermissionID int32            `db:"permission_id" json:"permission_id"`
	GrantedBy    pgtype.Int4      `db:"granted_by" json:"granted_by"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
}

type Student struct {
	ID             int32            `db:"id" json:"id"`
	StudentID      string           `db:"student_id" json:"student_id"`
	FirstName      string           `db:"first_name" json:"first_name"`
	LastName       string           `db:"last_name" json:"last_name"`
	Email          pgtype.Text      `db:"email" json:"email"`
	Phone          pgtype.Text      `db:"phone" json:"phone"`
	YearOfStudy    int32            `db:"year_of_study" json:"year_of_study"`
	Department     pgtype.Text      `db:"department" json:"department"`
	EnrollmentDate pgtype.Date      `db:"enrollment_date" json:"enrollment_date"`
	PasswordHash   pgtype.Text      `db:"password_hash" json:"password_hash"`
	IsActive       pgtype.Bool      `db:"is_active" json:"is_active"`
	DeletedAt      pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	// Maximum number of books this student can borrow at once
	MaxBooks         int32            `db:"max_books" json:"max_books"`
	Status           pgtype.Text      `db:"status" json:"status"`
	SuspensionReason pgtype.Text      `db:"suspension_reason" json:"suspension_reason"`
	GraduatedAt      pgtype.Timestamp `db:"graduated_at" json:"graduated_at"`
	AdminNotes       pgtype.Text      `db:"admin_notes" json:"admin_notes"`
}

type Transaction struct {
	ID               int32            `db:"id" json:"id"`
	StudentID        int32            `db:"student_id" json:"student_id"`
	BookID           int32            `db:"book_id" json:"book_id"`
	TransactionType  string           `db:"transaction_type" json:"transaction_type"`
	TransactionDate  pgtype.Timestamp `db:"transaction_date" json:"transaction_date"`
	DueDate          pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate     pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	LibrarianID      pgtype.Int4      `db:"librarian_id" json:"librarian_id"`
	FineAmount       pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid         pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	Notes            pgtype.Text      `db:"notes" json:"notes"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ReturnCondition  pgtype.Text      `db:"return_condition" json:"return_condition"`
	ConditionNotes   pgtype.Text      `db:"condition_notes" json:"condition_notes"`
	FineWaived       pgtype.Bool      `db:"fine_waived" json:"fine_waived"`
	FineWaivedAt     pgtype.Timestamp `db:"fine_waived_at" json:"fine_waived_at"`
	FineWaivedBy     pgtype.Int4      `db:"fine_waived_by" json:"fine_waived_by"`
	FineWaivedReason pgtype.Text      `db:"fine_waived_reason" json:"fine_waived_reason"`
	FinePaidAt       pgtype.Timestamp `db:"fine_paid_at" json:"fine_paid_at"`
}

type User struct {
	ID           int32            `db:"id" json:"id"`
	Username     string           `db:"username" json:"username"`
	Email        string           `db:"email" json:"email"`
	PasswordHash pgtype.Text      `db:"password_hash" json:"password_hash"`
	Role         pgtype.Text      `db:"role" json:"role"`
	IsActive     pgtype.Bool      `db:"is_active" json:"is_active"`
	LastLogin    pgtype.Timestamp `db:"last_login" json:"last_login"`
	DeletedAt    pgtype.Timestamp `db:"deleted_at" json:"deleted_at"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	InvitedBy    pgtype.Int4      `db:"invited_by" json:"invited_by"`
}

type UserInvite struct {
	ID          int32            `db:"id" json:"id"`
	Email       string           `db:"email" json:"email"`
	Name        string           `db:"name" json:"name"`
	Role        string           `db:"role" json:"role"`
	InviteToken string           `db:"invite_token" json:"invite_token"`
	InvitedBy   int32            `db:"invited_by" json:"invited_by"`
	ExpiresAt   pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	AcceptedAt  pgtype.Timestamp `db:"accepted_at" json:"accepted_at"`
	UserID      pgtype.Int4      `db:"user_id" json:"user_id"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type UserPermissionOverride struct {
	ID           int32            `db:"id" json:"id"`
	UserID       int32            `db:"user_id" json:"user_id"`
	PermissionID int32            `db:"permission_id" json:"permission_id"`
	OverrideType string           `db:"override_type" json:"override_type"`
	Reason       pgtype.Text      `db:"reason" json:"reason"`
	GrantedBy    pgtype.Int4      `db:"granted_by" json:"granted_by"`
	ExpiresAt    pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	CreatedAt    pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}
