// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActivateCategory(ctx context.Context, id int32) error
	AddBookAuthor(ctx context.Context, arg AddBookAuthorParams) error
	AddRolePermission(ctx context.Context, arg AddRolePermissionParams) error
	BulkUpdateStudentStatus(ctx context.Context, arg BulkUpdateStudentStatusParams) error
	CancelQueueItem(ctx context.Context, id int32) (EmailQueue, error)
	CancelReservation(ctx context.Context, id int32) (Reservation, error)
	CheckEmailExists(ctx context.Context, arg CheckEmailExistsParams) (bool, error)
	CheckRoleHasPermission(ctx context.Context, arg CheckRoleHasPermissionParams) (bool, error)
	// Check if a user has a specific permission (considering role + overrides)
	CheckUserHasPermission(ctx context.Context, arg CheckUserHasPermissionParams) (bool, error)
	CheckUsernameExists(ctx context.Context, arg CheckUsernameExistsParams) (bool, error)
	CleanupExpiredExportFiles(ctx context.Context) ([]ExportFile, error)
	CleanupExpiredOverrides(ctx context.Context) error
	ClearRolePermissions(ctx context.Context, role string) error
	ClearUserOverrides(ctx context.Context, userID int32) error
	CompleteQueueItem(ctx context.Context, id int32) (EmailQueue, error)
	CountActiveBorrowingsByStudent(ctx context.Context, studentID int32) (int64, error)
	CountActiveReservationsByBook(ctx context.Context, bookID int32) (int64, error)
	CountActiveReservationsByStudent(ctx context.Context, studentID int32) (int64, error)
	CountActiveTransactionsByBook(ctx context.Context, bookID int32) (int64, error)
	CountAdminUsers(ctx context.Context) (int64, error)
	// =====================================================
	// User Invites Queries
	// =====================================================
	// Count all users including inactive ones (for setup check)
	CountAllUsers(ctx context.Context) (int64, error)
	CountAuditLogs(ctx context.Context) (int64, error)
	CountAuditLogsByTable(ctx context.Context, tableName string) (int64, error)
	CountAuthorBooks(ctx context.Context, authorID int32) (int64, error)
	CountAuthors(ctx context.Context) (int64, error)
	CountAvailableBooks(ctx context.Context) (int64, error)
	CountAvailableCopies(ctx context.Context, bookID int32) (int64, error)
	CountBookCopies(ctx context.Context, bookID int32) (int64, error)
	CountBooks(ctx context.Context) (int64, error)
	CountBooksByCategory(ctx context.Context, categoryID pgtype.Int4) (int64, error)
	CountBooksByGenre(ctx context.Context, genre pgtype.Text) (int64, error)
	CountCategories(ctx context.Context) (int64, error)
	CountFines(ctx context.Context, arg CountFinesParams) (int64, error)
	CountImportHistoryByFilters(ctx context.Context, arg CountImportHistoryByFiltersParams) (int64, error)
	CountNotificationsByType(ctx context.Context, type_ string) (int64, error)
	CountOverdueTransactions(ctx context.Context) (int64, error)
	CountPendingInvites(ctx context.Context) (int64, error)
	CountPermissions(ctx context.Context) (int64, error)
	// Renewal-related queries for Phase 6.7
	CountRenewalsByStudentAndBook(ctx context.Context, arg CountRenewalsByStudentAndBookParams) (int64, error)
	CountSearchBooks(ctx context.Context, title string) (int64, error)
	CountSearchUsers(ctx context.Context, arg CountSearchUsersParams) (int64, error)
	CountSeries(ctx context.Context) (int64, error)
	CountSeriesBooks(ctx context.Context, seriesID pgtype.Int4) (int64, error)
	CountStudents(ctx context.Context) (int64, error)
	CountStudentsByStatus(ctx context.Context, isActive pgtype.Bool) (int64, error)
	CountStudentsByYear(ctx context.Context, yearOfStudy int32) (int64, error)
	CountStudentsWithFines(ctx context.Context) (int64, error)
	CountStudentsWithOverdue(ctx context.Context) (int32, error)
	CountStudentsWithOverdueBooks(ctx context.Context) (int64, error)
	CountStudentsWithUnpaidFines(ctx context.Context) (int32, error)
	CountTodayBorrowings(ctx context.Context) (int64, error)
	CountTransactions(ctx context.Context) (int64, error)
	CountUnreadNotificationsByRecipient(ctx context.Context, arg CountUnreadNotificationsByRecipientParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreateBookCopy(ctx context.Context, arg CreateBookCopyParams) (BookCopy, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	// Email Deliveries Queries
	// Phase 7.4: Email Integration - Delivery Tracking
	CreateEmailDelivery(ctx context.Context, arg CreateEmailDeliveryParams) (EmailDelivery, error)
	// Email Queue Queries
	// Phase 7.4: Email Integration - Queue Processing
	CreateEmailQueueItem(ctx context.Context, arg CreateEmailQueueItemParams) (EmailQueue, error)
	CreateExportFile(ctx context.Context, arg CreateExportFileParams) (ExportFile, error)
	// For first-run setup when no users exist
	CreateFirstAdmin(ctx context.Context, arg CreateFirstAdminParams) (User, error)
	CreateImportError(ctx context.Context, arg CreateImportErrorParams) (ImportError, error)
	CreateImportHistory(ctx context.Context, arg CreateImportHistoryParams) (ImportHistory, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error)
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	CreateSeries(ctx context.Context, arg CreateSeriesParams) (BookSeries, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserInvite(ctx context.Context, arg CreateUserInviteParams) (UserInvite, error)
	CreateUserOverride(ctx context.Context, arg CreateUserOverrideParams) (UserPermissionOverride, error)
	CreateUserWithoutPassword(ctx context.Context, arg CreateUserWithoutPasswordParams) (User, error)
	DeactivateCategory(ctx context.Context, id int32) error
	// Atomically decrement available copies. Returns the new count, or no rows if book unavailable.
	DecrementBookAvailability(ctx context.Context, id int32) (pgtype.Int4, error)
	DeleteAuthor(ctx context.Context, id int32) error
	DeleteBookCopy(ctx context.Context, id int32) error
	DeleteCategory(ctx context.Context, id int32) error
	DeleteInvite(ctx context.Context, id int32) error
	DeleteNotification(ctx context.Context, id int32) error
	DeleteOldAuditLogs(ctx context.Context, createdAt pgtype.Timestamp) error
	DeleteOldEmailDeliveries(ctx context.Context, createdAt pgtype.Timestamp) error
	DeleteOldNotifications(ctx context.Context, createdAt pgtype.Timestamp) error
	DeleteOldQueueItems(ctx context.Context, createdAt pgtype.Timestamp) error
	DeletePermission(ctx context.Context, id int32) error
	DeleteSeries(ctx context.Context, id int32) error
	DeleteUserOverride(ctx context.Context, arg DeleteUserOverrideParams) error
	DeleteUserOverrideByCode(ctx context.Context, arg DeleteUserOverrideByCodeParams) error
	GetAcademicYearAnalytics(ctx context.Context, arg GetAcademicYearAnalyticsParams) (GetAcademicYearAnalyticsRow, error)
	GetActiveExportFiles(ctx context.Context) ([]ExportFile, error)
	GetAuthorByID(ctx context.Context, id int32) (Author, error)
	GetAuthorByName(ctx context.Context, name string) (Author, error)
	GetBookByBookID(ctx context.Context, bookID string) (Book, error)
	GetBookByID(ctx context.Context, id int32) (Book, error)
	GetBookByISBN(ctx context.Context, isbn pgtype.Text) (Book, error)
	GetBookCopyByBarcode(ctx context.Context, barcode pgtype.Text) (BookCopy, error)
	GetBookCopyByID(ctx context.Context, id int32) (BookCopy, error)
	GetBookDemandPrediction(ctx context.Context, arg GetBookDemandPredictionParams) ([]GetBookDemandPredictionRow, error)
	GetBookUtilizationReport(ctx context.Context, arg GetBookUtilizationReportParams) ([]GetBookUtilizationReportRow, error)
	GetBooksByCategory(ctx context.Context, arg GetBooksByCategoryParams) ([]Book, error)
	GetBorrowingStatistics(ctx context.Context, arg GetBorrowingStatisticsParams) ([]GetBorrowingStatisticsRow, error)
	GetBorrowingStatisticsByDepartment(ctx context.Context, arg GetBorrowingStatisticsByDepartmentParams) ([]GetBorrowingStatisticsByDepartmentRow, error)
	GetBorrowingTrends(ctx context.Context, arg GetBorrowingTrendsParams) ([]GetBorrowingTrendsRow, error)
	GetCapacityPlanningAnalysis(ctx context.Context) (GetCapacityPlanningAnalysisRow, error)
	GetCategoryByID(ctx context.Context, id int32) (Category, error)
	GetCategoryByName(ctx context.Context, name string) (Category, error)
	GetDashboardMetrics(ctx context.Context) (GetDashboardMetricsRow, error)
	GetDistinctBookGenres(ctx context.Context) ([]pgtype.Text, error)
	GetEmailDeliveriesByNotification(ctx context.Context, notificationID int32) ([]EmailDelivery, error)
	GetEmailDeliveriesByStatus(ctx context.Context, arg GetEmailDeliveriesByStatusParams) ([]EmailDelivery, error)
	GetEmailDelivery(ctx context.Context, id int32) (EmailDelivery, error)
	GetEmailDeliveryHistory(ctx context.Context, arg GetEmailDeliveryHistoryParams) ([]GetEmailDeliveryHistoryRow, error)
	GetEmailDeliveryStats(ctx context.Context, arg GetEmailDeliveryStatsParams) (GetEmailDeliveryStatsRow, error)
	GetEmailQueueItem(ctx context.Context, id int32) (EmailQueue, error)
	GetExportFilesByHistoryID(ctx context.Context, importHistoryID int32) ([]ExportFile, error)
	GetFailedEmailDeliveries(ctx context.Context, limit int32) ([]EmailDelivery, error)
	GetFineByTransactionID(ctx context.Context, id int32) (GetFineByTransactionIDRow, error)
	GetFineOverviewStats(ctx context.Context) (GetFineOverviewStatsRow, error)
	GetFineStatistics(ctx context.Context, arg GetFineStatisticsParams) (GetFineStatisticsRow, error)
	GetGenrePopularity(ctx context.Context, arg GetGenrePopularityParams) ([]GetGenrePopularityRow, error)
	GetImportErrorsByHistoryID(ctx context.Context, importHistoryID int32) ([]ImportError, error)
	GetImportHistoryByFilters(ctx context.Context, arg GetImportHistoryByFiltersParams) ([]ImportHistory, error)
	GetImportHistoryByID(ctx context.Context, id int32) (ImportHistory, error)
	GetImportHistoryByUserID(ctx context.Context, arg GetImportHistoryByUserIDParams) ([]ImportHistory, error)
	GetImportHistoryStats(ctx context.Context, userID int32) (GetImportHistoryStatsRow, error)
	GetInventoryStatus(ctx context.Context) ([]GetInventoryStatusRow, error)
	GetInviteByEmail(ctx context.Context, email string) (UserInvite, error)
	GetInviteByID(ctx context.Context, id int32) (GetInviteByIDRow, error)
	GetInviteByToken(ctx context.Context, inviteToken string) (UserInvite, error)
	GetLibraryOverview(ctx context.Context) (GetLibraryOverviewRow, error)
	GetMonthlyTrends(ctx context.Context, arg GetMonthlyTrendsParams) ([]GetMonthlyTrendsRow, error)
	GetNextQueueItems(ctx context.Context, limit int32) ([]EmailQueue, error)
	GetNextReservationForBook(ctx context.Context, bookID int32) (GetNextReservationForBookRow, error)
	GetNotificationByID(ctx context.Context, id int32) (Notification, error)
	GetOverdueBooksByYear(ctx context.Context, arg GetOverdueBooksByYearParams) ([]GetOverdueBooksByYearRow, error)
	GetOverdueTransactionsForFineCalculation(ctx context.Context) ([]GetOverdueTransactionsForFineCalculationRow, error)
	GetPendingEmailDeliveries(ctx context.Context, limit int32) ([]EmailDelivery, error)
	GetPermissionByCode(ctx context.Context, code string) (Permission, error)
	GetPermissionByID(ctx context.Context, id int32) (Permission, error)
	GetPermissionsByCategory(ctx context.Context, category string) ([]Permission, error)
	GetPopularBooks(ctx context.Context, arg GetPopularBooksParams) ([]GetPopularBooksRow, error)
	GetProcessingQueueItems(ctx context.Context, processingStartedAt pgtype.Timestamp) ([]EmailQueue, error)
	GetQueueItemsByNotification(ctx context.Context, notificationID int32) ([]EmailQueue, error)
	GetQueueItemsByStatus(ctx context.Context, arg GetQueueItemsByStatusParams) ([]EmailQueue, error)
	GetQueueStats(ctx context.Context, arg GetQueueStatsParams) (GetQueueStatsRow, error)
	GetRenewalStatisticsByStudent(ctx context.Context, studentID int32) (GetRenewalStatisticsByStudentRow, error)
	GetReservationByID(ctx context.Context, id int32) (GetReservationByIDRow, error)
	GetRiskAnalysis(ctx context.Context) ([]GetRiskAnalysisRow, error)
	GetRolePermissionCodes(ctx context.Context, role string) ([]string, error)
	GetSeasonalTrends(ctx context.Context, arg GetSeasonalTrendsParams) ([]GetSeasonalTrendsRow, error)
	GetSeriesByID(ctx context.Context, id int32) (BookSeries, error)
	GetSeriesByName(ctx context.Context, name string) (BookSeries, error)
	GetStudentActivity(ctx context.Context, arg GetStudentActivityParams) ([]GetStudentActivityRow, error)
	GetStudentBehaviorAnalysis(ctx context.Context, arg GetStudentBehaviorAnalysisParams) ([]GetStudentBehaviorAnalysisRow, error)
	GetStudentBorrowingStats(ctx context.Context) ([]GetStudentBorrowingStatsRow, error)
	GetStudentByEmail(ctx context.Context, email pgtype.Text) (Student, error)
	GetStudentByID(ctx context.Context, id int32) (Student, error)
	GetStudentByStudentID(ctx context.Context, studentID string) (Student, error)
	GetStudentCountByYearAndDepartment(ctx context.Context) ([]GetStudentCountByYearAndDepartmentRow, error)
	GetStudentEnrollmentTrends(ctx context.Context, arg GetStudentEnrollmentTrendsParams) ([]GetStudentEnrollmentTrendsRow, error)
	GetStudentFineStats(ctx context.Context, studentID int32) (GetStudentFineStatsRow, error)
	GetStudentReservationForBook(ctx context.Context, arg GetStudentReservationForBookParams) (GetStudentReservationForBookRow, error)
	GetStudentTotalBorrowed(ctx context.Context, studentID int32) (int64, error)
	GetStudentsByStatus(ctx context.Context, arg GetStudentsByStatusParams) ([]Student, error)
	GetStudentsWithHighFines(ctx context.Context, fineAmount pgtype.Numeric) ([]GetStudentsWithHighFinesRow, error)
	GetTopBorrowingStudents(ctx context.Context, arg GetTopBorrowingStudentsParams) ([]GetTopBorrowingStudentsRow, error)
	GetTotalUnpaidFinesByStudent(ctx context.Context, studentID int32) (pgtype.Numeric, error)
	GetTransactionByID(ctx context.Context, id int32) (GetTransactionByIDRow, error)
	GetUnpaidFinesByStudent(ctx context.Context, studentID int32) ([]GetUnpaidFinesByStudentRow, error)
	// Phase 8.3 - Advanced Analytics Queries
	GetUsagePatternAnalysis(ctx context.Context, arg GetUsagePatternAnalysisParams) ([]GetUsagePatternAnalysisRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserDeniedOverrides(ctx context.Context, userID int32) ([]string, error)
	// =====================================================
	// Combined Permission Check Queries
	// =====================================================
	// Get all effective permissions for a user (role permissions + grants - denials)
	GetUserEffectivePermissions(ctx context.Context, id int32) ([]string, error)
	GetUserGrantedOverrides(ctx context.Context, userID int32) ([]string, error)
	GetUserOverride(ctx context.Context, arg GetUserOverrideParams) (GetUserOverrideRow, error)
	GetYearBasedOverdueAnalysis(ctx context.Context, arg GetYearBasedOverdueAnalysisParams) ([]GetYearBasedOverdueAnalysisRow, error)
	GetYearEndSummary(ctx context.Context) (GetYearEndSummaryRow, error)
	GetYearOverYearComparison(ctx context.Context, dollar_1 []int32) ([]GetYearOverYearComparisonRow, error)
	GetYearSpecificBorrowingReport(ctx context.Context, dollar_1 int32) ([]GetYearSpecificBorrowingReportRow, error)
	GetYearlyStatistics(ctx context.Context, dollar_1 []int32) ([]GetYearlyStatisticsRow, error)
	HasActiveReservationsByOtherStudents(ctx context.Context, arg HasActiveReservationsByOtherStudentsParams) (bool, error)
	// Atomically increment available copies.
	IncrementBookAvailability(ctx context.Context, id int32) (pgtype.Int4, error)
	ListActiveBorrowings(ctx context.Context, arg ListActiveBorrowingsParams) ([]ListActiveBorrowingsRow, error)
	ListActiveReservations(ctx context.Context) ([]ListActiveReservationsRow, error)
	// Notification-related queries for Phase 7.2
	ListActiveReservationsForAvailableBook(ctx context.Context, bookID int32) ([]ListActiveReservationsForAvailableBookRow, error)
	ListActiveTransactionsByStudent(ctx context.Context, studentID int32) ([]ListActiveTransactionsByStudentRow, error)
	ListAllCategories(ctx context.Context) ([]Category, error)
	ListAllRolePermissions(ctx context.Context) ([]ListAllRolePermissionsRow, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsByAction(ctx context.Context, arg ListAuditLogsByActionParams) ([]AuditLog, error)
	ListAuditLogsByDateRange(ctx context.Context, arg ListAuditLogsByDateRangeParams) ([]AuditLog, error)
	ListAuditLogsByRecord(ctx context.Context, arg ListAuditLogsByRecordParams) ([]AuditLog, error)
	ListAuditLogsByTable(ctx context.Context, arg ListAuditLogsByTableParams) ([]AuditLog, error)
	ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error)
	ListAuthorBooks(ctx context.Context, authorID int32) ([]Book, error)
	ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]Author, error)
	ListAvailableBooks(ctx context.Context, arg ListAvailableBooksParams) ([]Book, error)
	ListBookAuthors(ctx context.Context, bookID int32) ([]Author, error)
	ListBookCopies(ctx context.Context, bookID int32) ([]BookCopy, error)
	ListBookCopiesByStatus(ctx context.Context, arg ListBookCopiesByStatusParams) ([]BookCopy, error)
	ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListExpiredReservations(ctx context.Context) ([]ListExpiredReservationsRow, error)
	// Fines Management Queries
	ListFines(ctx context.Context, arg ListFinesParams) ([]ListFinesRow, error)
	ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error)
	ListNotificationsByRecipient(ctx context.Context, arg ListNotificationsByRecipientParams) ([]Notification, error)
	ListNotificationsByType(ctx context.Context, arg ListNotificationsByTypeParams) ([]Notification, error)
	ListOverdueTransactions(ctx context.Context) ([]ListOverdueTransactionsRow, error)
	ListPendingInvites(ctx context.Context, arg ListPendingInvitesParams) ([]ListPendingInvitesRow, error)
	// =====================================================
	// Permission Queries
	// =====================================================
	ListPermissions(ctx context.Context) ([]Permission, error)
	ListRenewalsByStudentAndBook(ctx context.Context, arg ListRenewalsByStudentAndBookParams) ([]ListRenewalsByStudentAndBookRow, error)
	ListReservations(ctx context.Context, arg ListReservationsParams) ([]ListReservationsRow, error)
	ListReservationsByBook(ctx context.Context, bookID int32) ([]ListReservationsByBookRow, error)
	ListReservationsByStudent(ctx context.Context, arg ListReservationsByStudentParams) ([]ListReservationsByStudentRow, error)
	// =====================================================
	// Role Permission Queries
	// =====================================================
	ListRolePermissions(ctx context.Context, role string) ([]Permission, error)
	ListSeries(ctx context.Context, arg ListSeriesParams) ([]BookSeries, error)
	ListSeriesBooks(ctx context.Context, seriesID pgtype.Int4) ([]Book, error)
	ListStudents(ctx context.Context, arg ListStudentsParams) ([]Student, error)
	ListStudentsByYear(ctx context.Context, arg ListStudentsByYearParams) ([]Student, error)
	// Fine and Overdue Filtering Queries
	ListStudentsWithFines(ctx context.Context, arg ListStudentsWithFinesParams) ([]Student, error)
	ListStudentsWithFinesAndOverdue(ctx context.Context, arg ListStudentsWithFinesAndOverdueParams) ([]Student, error)
	ListStudentsWithOverdue(ctx context.Context, arg ListStudentsWithOverdueParams) ([]Student, error)
	ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error)
	ListTransactionsByBook(ctx context.Context, arg ListTransactionsByBookParams) ([]ListTransactionsByBookRow, error)
	ListTransactionsByStudent(ctx context.Context, arg ListTransactionsByStudentParams) ([]ListTransactionsByStudentRow, error)
	// Notification-related queries for Phase 7.2
	ListTransactionsDueSoon(ctx context.Context) ([]ListTransactionsDueSoonRow, error)
	ListTransactionsOverdue(ctx context.Context) ([]ListTransactionsOverdueRow, error)
	ListTransactionsWithUnpaidFines(ctx context.Context) ([]ListTransactionsWithUnpaidFinesRow, error)
	ListUnreadNotificationsByRecipient(ctx context.Context, arg ListUnreadNotificationsByRecipientParams) ([]Notification, error)
	ListUnsentNotifications(ctx context.Context, limit int32) ([]Notification, error)
	// =====================================================
	// User Permission Override Queries
	// =====================================================
	ListUserOverrides(ctx context.Context, userID int32) ([]ListUserOverridesRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	MarkInviteAccepted(ctx context.Context, arg MarkInviteAcceptedParams) (UserInvite, error)
	MarkNotificationAsRead(ctx context.Context, id int32) error
	MarkNotificationAsSent(ctx context.Context, id int32) error
	PayFineByTransactionID(ctx context.Context, id int32) (Transaction, error)
	PayTransactionFine(ctx context.Context, id int32) error
	RemoveBookAuthor(ctx context.Context, arg RemoveBookAuthorParams) error
	RemoveRolePermission(ctx context.Context, arg RemoveRolePermissionParams) error
	ResetStuckQueueItems(ctx context.Context, processingStartedAt pgtype.Timestamp) error
	ReturnBook(ctx context.Context, arg ReturnBookParams) (Transaction, error)
	SearchAuthors(ctx context.Context, arg SearchAuthorsParams) ([]Author, error)
	SearchBooks(ctx context.Context, arg SearchBooksParams) ([]Book, error)
	SearchBooksByGenre(ctx context.Context, arg SearchBooksByGenreParams) ([]Book, error)
	SearchSeries(ctx context.Context, arg SearchSeriesParams) ([]BookSeries, error)
	SearchStudents(ctx context.Context, arg SearchStudentsParams) ([]Student, error)
	SearchStudentsIncludingDeleted(ctx context.Context, arg SearchStudentsIncludingDeletedParams) ([]Student, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	SoftDeleteBook(ctx context.Context, id int32) error
	SoftDeleteStudent(ctx context.Context, id int32) error
	SoftDeleteUser(ctx context.Context, id int32) error
	UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error)
	UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error)
	UpdateBookAvailability(ctx context.Context, arg UpdateBookAvailabilityParams) error
	UpdateBookCategory(ctx context.Context, arg UpdateBookCategoryParams) error
	UpdateBookCondition(ctx context.Context, arg UpdateBookConditionParams) error
	UpdateBookCopy(ctx context.Context, arg UpdateBookCopyParams) (BookCopy, error)
	UpdateBookCopyCondition(ctx context.Context, arg UpdateBookCopyConditionParams) (BookCopy, error)
	UpdateBookCopyStatus(ctx context.Context, arg UpdateBookCopyStatusParams) (BookCopy, error)
	UpdateBookSeries(ctx context.Context, arg UpdateBookSeriesParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateEmailDeliveryError(ctx context.Context, arg UpdateEmailDeliveryErrorParams) (EmailDelivery, error)
	UpdateEmailDeliveryProviderInfo(ctx context.Context, arg UpdateEmailDeliveryProviderInfoParams) (EmailDelivery, error)
	UpdateEmailDeliveryStatus(ctx context.Context, arg UpdateEmailDeliveryStatusParams) (EmailDelivery, error)
	UpdateEmailDeliveryToDelivered(ctx context.Context, id int32) (EmailDelivery, error)
	UpdateEmailDeliveryToFailed(ctx context.Context, id int32) (EmailDelivery, error)
	UpdateEmailDeliveryToSent(ctx context.Context, id int32) (EmailDelivery, error)
	UpdateExportFileDownload(ctx context.Context, id int32) (ExportFile, error)
	UpdateFineAmount(ctx context.Context, arg UpdateFineAmountParams) error
	UpdateImportHistory(ctx context.Context, arg UpdateImportHistoryParams) (ImportHistory, error)
	UpdateInviteToken(ctx context.Context, arg UpdateInviteTokenParams) (UserInvite, error)
	UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (Permission, error)
	UpdateQueueItemError(ctx context.Context, arg UpdateQueueItemErrorParams) (EmailQueue, error)
	// Items processing longer than threshold
	UpdateQueueItemStatus(ctx context.Context, arg UpdateQueueItemStatusParams) (EmailQueue, error)
	UpdateQueueItemToCompleted(ctx context.Context, arg UpdateQueueItemToCompletedParams) (EmailQueue, error)
	UpdateQueueItemToFailed(ctx context.Context, arg UpdateQueueItemToFailedParams) (EmailQueue, error)
	UpdateQueueItemToProcessing(ctx context.Context, arg UpdateQueueItemToProcessingParams) (EmailQueue, error)
	UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (Reservation, error)
	UpdateSeries(ctx context.Context, arg UpdateSeriesParams) (BookSeries, error)
	UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error)
	UpdateStudentPassword(ctx context.Context, arg UpdateStudentPasswordParams) error
	// Status Management Queries
	UpdateStudentStatus(ctx context.Context, arg UpdateStudentStatusParams) (Student, error)
	UpdateTransactionFine(ctx context.Context, arg UpdateTransactionFineParams) error
	UpdateTransactionReturn(ctx context.Context, arg UpdateTransactionReturnParams) (Transaction, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id int32) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
	WaiveFineByTransactionID(ctx context.Context, arg WaiveFineByTransactionIDParams) (Transaction, error)
}

var _ Querier = (*Queries)(nil)
