// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAcademicYearAnalytics = `-- name: GetAcademicYearAnalytics :one
SELECT 
    $1::int as academic_year,
    (SELECT COUNT(DISTINCT s.id) FROM students s WHERE s.year_of_study = $1::int AND s.deleted_at IS NULL AND s.is_active = true)::int as total_students,
    (SELECT COUNT(*) FROM transactions t INNER JOIN students s ON t.student_id = s.id WHERE s.year_of_study = $1::int AND t.transaction_type = 'borrow' AND EXTRACT(YEAR FROM t.transaction_date) = $2::int)::int as total_borrows,
    (SELECT COUNT(*) FROM transactions t INNER JOIN students s ON t.student_id = s.id WHERE s.year_of_study = $1::int AND t.transaction_type = 'return' AND EXTRACT(YEAR FROM t.transaction_date) = $2::int)::int as total_returns,
    (SELECT COUNT(*) FROM transactions t INNER JOIN students s ON t.student_id = s.id WHERE s.year_of_study = $1::int AND t.due_date < NOW() AND t.returned_date IS NULL)::int as current_overdue,
    (SELECT COALESCE(SUM(t.fine_amount), 0)::text FROM transactions t INNER JOIN students s ON t.student_id = s.id WHERE s.year_of_study = $1::int AND t.fine_amount > 0)::text as total_fines,
    (SELECT 
        CASE 
            WHEN COUNT(DISTINCT s.id) > 0 THEN 
                ROUND((COUNT(*)::numeric / COUNT(DISTINCT s.id)::numeric), 2)::text
            ELSE '0.00'
        END
     FROM transactions t INNER JOIN students s ON t.student_id = s.id 
     WHERE s.year_of_study = $1::int AND t.transaction_type = 'borrow' AND EXTRACT(YEAR FROM t.transaction_date) = $2::int)::text as avg_books_per_student
`

type GetAcademicYearAnalyticsParams struct {
	Column1 int32 `db:"column_1" json:"column_1"`
	Column2 int32 `db:"column_2" json:"column_2"`
}

type GetAcademicYearAnalyticsRow struct {
	AcademicYear       int32  `db:"academic_year" json:"academic_year"`
	TotalStudents      int32  `db:"total_students" json:"total_students"`
	TotalBorrows       int32  `db:"total_borrows" json:"total_borrows"`
	TotalReturns       int32  `db:"total_returns" json:"total_returns"`
	CurrentOverdue     int32  `db:"current_overdue" json:"current_overdue"`
	TotalFines         string `db:"total_fines" json:"total_fines"`
	AvgBooksPerStudent string `db:"avg_books_per_student" json:"avg_books_per_student"`
}

func (q *Queries) GetAcademicYearAnalytics(ctx context.Context, arg GetAcademicYearAnalyticsParams) (GetAcademicYearAnalyticsRow, error) {
	row := q.db.QueryRow(ctx, getAcademicYearAnalytics, arg.Column1, arg.Column2)
	var i GetAcademicYearAnalyticsRow
	err := row.Scan(
		&i.AcademicYear,
		&i.TotalStudents,
		&i.TotalBorrows,
		&i.TotalReturns,
		&i.CurrentOverdue,
		&i.TotalFines,
		&i.AvgBooksPerStudent,
	)
	return i, err
}

const getBookDemandPrediction = `-- name: GetBookDemandPrediction :many
SELECT 
    b.id as book_id,
    b.book_id as book_code,
    b.title,
    b.author,
    b.genre,
    COUNT(t.id)::int as historical_borrows,
    COUNT(DISTINCT t.student_id)::int as unique_borrowers,
    COALESCE(AVG(EXTRACT(DAY FROM (t.returned_date - t.transaction_date))), 14)::text as avg_loan_duration,
    CASE 
        WHEN COUNT(t.id) > 0 THEN 
            ROUND((COUNT(t.id)::numeric / EXTRACT(DAY FROM ($2::timestamp - $1::timestamp)) * 30), 2)::text
        ELSE '0.00'
    END as predicted_monthly_demand,
    CASE 
        WHEN COUNT(r.id) > 0 AND b.available_copies = 0 THEN 'High'
        WHEN COUNT(t.id) > AVG(book_stats.avg_borrows) * 1.5 THEN 'High'
        WHEN COUNT(t.id) > AVG(book_stats.avg_borrows) THEN 'Medium' 
        ELSE 'Low'
    END as demand_category,
    COUNT(r.id)::int as current_reservations,
    b.available_copies,
    b.total_copies
FROM books b
LEFT JOIN transactions t ON b.id = t.book_id 
    AND t.transaction_type = 'borrow'
    AND t.transaction_date >= $1::timestamp
    AND t.transaction_date <= $2::timestamp
LEFT JOIN reservations r ON b.id = r.book_id 
    AND r.status = 'active'
CROSS JOIN (
    SELECT AVG(borrow_count) as avg_borrows
    FROM (
        SELECT COUNT(*)::int as borrow_count
        FROM transactions 
        WHERE transaction_type = 'borrow'
        AND transaction_date >= $1::timestamp
        AND transaction_date <= $2::timestamp
        GROUP BY book_id
    ) book_counts
) book_stats
WHERE b.deleted_at IS NULL
    AND b.is_active = true
    AND ($3::text IS NULL OR b.genre = $3::text)
GROUP BY b.id, b.book_id, b.title, b.author, b.genre, b.available_copies, b.total_copies, book_stats.avg_borrows
ORDER BY historical_borrows DESC, current_reservations DESC
`

type GetBookDemandPredictionParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
	Column3 string           `db:"column_3" json:"column_3"`
}

type GetBookDemandPredictionRow struct {
	BookID                 int32       `db:"book_id" json:"book_id"`
	BookCode               string      `db:"book_code" json:"book_code"`
	Title                  string      `db:"title" json:"title"`
	Author                 string      `db:"author" json:"author"`
	Genre                  pgtype.Text `db:"genre" json:"genre"`
	HistoricalBorrows      int32       `db:"historical_borrows" json:"historical_borrows"`
	UniqueBorrowers        int32       `db:"unique_borrowers" json:"unique_borrowers"`
	AvgLoanDuration        string      `db:"avg_loan_duration" json:"avg_loan_duration"`
	PredictedMonthlyDemand string      `db:"predicted_monthly_demand" json:"predicted_monthly_demand"`
	DemandCategory         string      `db:"demand_category" json:"demand_category"`
	CurrentReservations    int32       `db:"current_reservations" json:"current_reservations"`
	AvailableCopies        pgtype.Int4 `db:"available_copies" json:"available_copies"`
	TotalCopies            pgtype.Int4 `db:"total_copies" json:"total_copies"`
}

func (q *Queries) GetBookDemandPrediction(ctx context.Context, arg GetBookDemandPredictionParams) ([]GetBookDemandPredictionRow, error) {
	rows, err := q.db.Query(ctx, getBookDemandPrediction, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookDemandPredictionRow{}
	for rows.Next() {
		var i GetBookDemandPredictionRow
		if err := rows.Scan(
			&i.BookID,
			&i.BookCode,
			&i.Title,
			&i.Author,
			&i.Genre,
			&i.HistoricalBorrows,
			&i.UniqueBorrowers,
			&i.AvgLoanDuration,
			&i.PredictedMonthlyDemand,
			&i.DemandCategory,
			&i.CurrentReservations,
			&i.AvailableCopies,
			&i.TotalCopies,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBookUtilizationReport = `-- name: GetBookUtilizationReport :many
SELECT 
    b.book_id,
    b.title,
    b.author,
    b.genre,
    b.total_copies,
    b.available_copies,
    COUNT(t.id)::int as total_borrows,
    COUNT(DISTINCT t.student_id)::int as unique_borrowers,
    CASE 
        WHEN b.total_copies > 0 THEN 
            ROUND(((b.total_copies - b.available_copies)::numeric / b.total_copies::numeric) * 100, 2)::text
        ELSE '0.00'
    END as utilization_rate,
    COALESCE(MAX(t.transaction_date), b.created_at) as last_borrowed
FROM books b
LEFT JOIN transactions t ON b.id = t.book_id 
    AND t.transaction_type = 'borrow'
    AND t.transaction_date >= $1::timestamp
    AND t.transaction_date <= $2::timestamp
WHERE b.deleted_at IS NULL
    AND b.is_active = true
    AND ($3::text IS NULL OR b.genre = $3::text)
GROUP BY b.id, b.book_id, b.title, b.author, b.genre, b.total_copies, b.available_copies, b.created_at
ORDER BY total_borrows DESC, utilization_rate DESC
`

type GetBookUtilizationReportParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
	Column3 string           `db:"column_3" json:"column_3"`
}

type GetBookUtilizationReportRow struct {
	BookID          string           `db:"book_id" json:"book_id"`
	Title           string           `db:"title" json:"title"`
	Author          string           `db:"author" json:"author"`
	Genre           pgtype.Text      `db:"genre" json:"genre"`
	TotalCopies     pgtype.Int4      `db:"total_copies" json:"total_copies"`
	AvailableCopies pgtype.Int4      `db:"available_copies" json:"available_copies"`
	TotalBorrows    int32            `db:"total_borrows" json:"total_borrows"`
	UniqueBorrowers int32            `db:"unique_borrowers" json:"unique_borrowers"`
	UtilizationRate string           `db:"utilization_rate" json:"utilization_rate"`
	LastBorrowed    pgtype.Timestamp `db:"last_borrowed" json:"last_borrowed"`
}

func (q *Queries) GetBookUtilizationReport(ctx context.Context, arg GetBookUtilizationReportParams) ([]GetBookUtilizationReportRow, error) {
	rows, err := q.db.Query(ctx, getBookUtilizationReport, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBookUtilizationReportRow{}
	for rows.Next() {
		var i GetBookUtilizationReportRow
		if err := rows.Scan(
			&i.BookID,
			&i.Title,
			&i.Author,
			&i.Genre,
			&i.TotalCopies,
			&i.AvailableCopies,
			&i.TotalBorrows,
			&i.UniqueBorrowers,
			&i.UtilizationRate,
			&i.LastBorrowed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBorrowingStatistics = `-- name: GetBorrowingStatistics :many
SELECT 
    TO_CHAR(DATE_TRUNC('month', t.transaction_date), 'YYYY-MM') as month,
    COUNT(CASE WHEN t.transaction_type = 'borrow' THEN 1 END)::int as total_borrows,
    COUNT(CASE WHEN t.transaction_type = 'return' THEN 1 END)::int as total_returns,
    COUNT(CASE WHEN t.due_date < NOW() AND t.returned_date IS NULL THEN 1 END)::int as total_overdue,
    COUNT(DISTINCT t.student_id)::int as unique_students
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
WHERE t.transaction_date >= $1::timestamp
    AND t.transaction_date <= $2::timestamp
    AND ($3::int IS NULL OR s.year_of_study = $3::int)
    AND s.deleted_at IS NULL
GROUP BY DATE_TRUNC('month', t.transaction_date)
ORDER BY month
`

type GetBorrowingStatisticsParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
	Column3 int32            `db:"column_3" json:"column_3"`
}

type GetBorrowingStatisticsRow struct {
	Month          string `db:"month" json:"month"`
	TotalBorrows   int32  `db:"total_borrows" json:"total_borrows"`
	TotalReturns   int32  `db:"total_returns" json:"total_returns"`
	TotalOverdue   int32  `db:"total_overdue" json:"total_overdue"`
	UniqueStudents int32  `db:"unique_students" json:"unique_students"`
}

func (q *Queries) GetBorrowingStatistics(ctx context.Context, arg GetBorrowingStatisticsParams) ([]GetBorrowingStatisticsRow, error) {
	rows, err := q.db.Query(ctx, getBorrowingStatistics, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBorrowingStatisticsRow{}
	for rows.Next() {
		var i GetBorrowingStatisticsRow
		if err := rows.Scan(
			&i.Month,
			&i.TotalBorrows,
			&i.TotalReturns,
			&i.TotalOverdue,
			&i.UniqueStudents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBorrowingStatisticsByDepartment = `-- name: GetBorrowingStatisticsByDepartment :many
SELECT 
    s.department,
    TO_CHAR(DATE_TRUNC('month', t.transaction_date), 'YYYY-MM') as month,
    COUNT(CASE WHEN t.transaction_type = 'borrow' THEN 1 END)::int as total_borrows,
    COUNT(CASE WHEN t.transaction_type = 'return' THEN 1 END)::int as total_returns,
    COUNT(DISTINCT t.student_id)::int as unique_students
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
WHERE t.transaction_date >= $1::timestamp
    AND t.transaction_date <= $2::timestamp
    AND s.deleted_at IS NULL
    AND ($3::text IS NULL OR s.department = $3::text)
GROUP BY s.department, DATE_TRUNC('month', t.transaction_date)
ORDER BY s.department, month
`

type GetBorrowingStatisticsByDepartmentParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
	Column3 string           `db:"column_3" json:"column_3"`
}

type GetBorrowingStatisticsByDepartmentRow struct {
	Department     pgtype.Text `db:"department" json:"department"`
	Month          string      `db:"month" json:"month"`
	TotalBorrows   int32       `db:"total_borrows" json:"total_borrows"`
	TotalReturns   int32       `db:"total_returns" json:"total_returns"`
	UniqueStudents int32       `db:"unique_students" json:"unique_students"`
}

func (q *Queries) GetBorrowingStatisticsByDepartment(ctx context.Context, arg GetBorrowingStatisticsByDepartmentParams) ([]GetBorrowingStatisticsByDepartmentRow, error) {
	rows, err := q.db.Query(ctx, getBorrowingStatisticsByDepartment, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBorrowingStatisticsByDepartmentRow{}
	for rows.Next() {
		var i GetBorrowingStatisticsByDepartmentRow
		if err := rows.Scan(
			&i.Department,
			&i.Month,
			&i.TotalBorrows,
			&i.TotalReturns,
			&i.UniqueStudents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBorrowingTrends = `-- name: GetBorrowingTrends :many
SELECT 
    CASE 
        WHEN $3::text = 'day' THEN TO_CHAR(DATE_TRUNC('day', t.transaction_date), 'YYYY-MM-DD')
        WHEN $3::text = 'week' THEN TO_CHAR(DATE_TRUNC('week', t.transaction_date), 'YYYY-MM-DD')
        WHEN $3::text = 'month' THEN TO_CHAR(DATE_TRUNC('month', t.transaction_date), 'YYYY-MM')
        WHEN $3::text = 'year' THEN TO_CHAR(DATE_TRUNC('year', t.transaction_date), 'YYYY')
        ELSE TO_CHAR(DATE_TRUNC('month', t.transaction_date), 'YYYY-MM')
    END as period,
    COUNT(CASE WHEN t.transaction_type = 'borrow' THEN 1 END)::int as borrow_count,
    COUNT(CASE WHEN t.transaction_type = 'return' THEN 1 END)::int as return_count,
    COUNT(CASE WHEN t.due_date < NOW() AND t.returned_date IS NULL THEN 1 END)::int as overdue_count,
    0::int as new_students,  -- Placeholder - would need separate query for new student registrations
    COUNT(DISTINCT t.student_id)::int as total_students
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
WHERE t.transaction_date >= $1::timestamp
    AND t.transaction_date <= $2::timestamp
    AND s.deleted_at IS NULL
GROUP BY 
    CASE 
        WHEN $3::text = 'day' THEN TO_CHAR(DATE_TRUNC('day', t.transaction_date), 'YYYY-MM-DD')
        WHEN $3::text = 'week' THEN TO_CHAR(DATE_TRUNC('week', t.transaction_date), 'YYYY-MM-DD')
        WHEN $3::text = 'month' THEN TO_CHAR(DATE_TRUNC('month', t.transaction_date), 'YYYY-MM')
        WHEN $3::text = 'year' THEN TO_CHAR(DATE_TRUNC('year', t.transaction_date), 'YYYY')
        ELSE TO_CHAR(DATE_TRUNC('month', t.transaction_date), 'YYYY-MM')
    END
ORDER BY period
`

type GetBorrowingTrendsParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
	Column3 string           `db:"column_3" json:"column_3"`
}

type GetBorrowingTrendsRow struct {
	Period        interface{} `db:"period" json:"period"`
	BorrowCount   int32       `db:"borrow_count" json:"borrow_count"`
	ReturnCount   int32       `db:"return_count" json:"return_count"`
	OverdueCount  int32       `db:"overdue_count" json:"overdue_count"`
	NewStudents   int32       `db:"new_students" json:"new_students"`
	TotalStudents int32       `db:"total_students" json:"total_students"`
}

func (q *Queries) GetBorrowingTrends(ctx context.Context, arg GetBorrowingTrendsParams) ([]GetBorrowingTrendsRow, error) {
	rows, err := q.db.Query(ctx, getBorrowingTrends, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBorrowingTrendsRow{}
	for rows.Next() {
		var i GetBorrowingTrendsRow
		if err := rows.Scan(
			&i.Period,
			&i.BorrowCount,
			&i.ReturnCount,
			&i.OverdueCount,
			&i.NewStudents,
			&i.TotalStudents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCapacityPlanningAnalysis = `-- name: GetCapacityPlanningAnalysis :one
SELECT 
    (SELECT COUNT(*) FROM books WHERE deleted_at IS NULL AND is_active = true)::int as total_books_in_system,
    (SELECT SUM(total_copies) FROM books WHERE deleted_at IS NULL AND is_active = true)::int as total_book_copies,
    (SELECT SUM(available_copies) FROM books WHERE deleted_at IS NULL AND is_active = true)::int as currently_available_copies,
    (SELECT COUNT(*) FROM transactions WHERE transaction_type = 'borrow' AND returned_date IS NULL)::int as books_currently_borrowed,
    (SELECT COUNT(*) FROM reservations WHERE status = 'active' AND expires_at > NOW())::int as active_reservations,
    (SELECT COUNT(DISTINCT student_id) FROM transactions WHERE DATE(transaction_date) >= CURRENT_DATE - INTERVAL '30 days')::int as active_users_last_30_days,
    ROUND(
        (SELECT COUNT(*) FROM transactions WHERE transaction_type = 'borrow' AND returned_date IS NULL)::numeric /
        (SELECT CASE WHEN SUM(total_copies) > 0 THEN SUM(total_copies) ELSE 1 END FROM books WHERE deleted_at IS NULL AND is_active = true)::numeric * 100,
        2
    )::text as system_utilization_percent,
    CASE 
        WHEN (SELECT COUNT(*) FROM reservations WHERE status = 'active' AND expires_at > NOW()) > 
             (SELECT SUM(available_copies) FROM books WHERE deleted_at IS NULL AND is_active = true) * 0.1
        THEN 'Consider adding more copies of popular books'
        WHEN (SELECT COUNT(*) FROM transactions WHERE transaction_type = 'borrow' AND returned_date IS NULL)::numeric /
             (SELECT CASE WHEN SUM(total_copies) > 0 THEN SUM(total_copies) ELSE 1 END FROM books WHERE deleted_at IS NULL AND is_active = true)::numeric > 0.8
        THEN 'System near capacity - consider expanding collection'
        ELSE 'Capacity is adequate'
    END as capacity_recommendation
`

type GetCapacityPlanningAnalysisRow struct {
	TotalBooksInSystem       int32  `db:"total_books_in_system" json:"total_books_in_system"`
	TotalBookCopies          int32  `db:"total_book_copies" json:"total_book_copies"`
	CurrentlyAvailableCopies int32  `db:"currently_available_copies" json:"currently_available_copies"`
	BooksCurrentlyBorrowed   int32  `db:"books_currently_borrowed" json:"books_currently_borrowed"`
	ActiveReservations       int32  `db:"active_reservations" json:"active_reservations"`
	ActiveUsersLast30Days    int32  `db:"active_users_last_30_days" json:"active_users_last_30_days"`
	SystemUtilizationPercent string `db:"system_utilization_percent" json:"system_utilization_percent"`
	CapacityRecommendation   string `db:"capacity_recommendation" json:"capacity_recommendation"`
}

func (q *Queries) GetCapacityPlanningAnalysis(ctx context.Context) (GetCapacityPlanningAnalysisRow, error) {
	row := q.db.QueryRow(ctx, getCapacityPlanningAnalysis)
	var i GetCapacityPlanningAnalysisRow
	err := row.Scan(
		&i.TotalBooksInSystem,
		&i.TotalBookCopies,
		&i.CurrentlyAvailableCopies,
		&i.BooksCurrentlyBorrowed,
		&i.ActiveReservations,
		&i.ActiveUsersLast30Days,
		&i.SystemUtilizationPercent,
		&i.CapacityRecommendation,
	)
	return i, err
}

const getDashboardMetrics = `-- name: GetDashboardMetrics :one
SELECT
    (SELECT COUNT(*) FROM transactions WHERE transaction_type = 'borrow' AND DATE(transaction_date) = CURRENT_DATE)::int as today_borrows,
    (SELECT COUNT(*) FROM transactions WHERE transaction_type = 'return' AND DATE(transaction_date) = CURRENT_DATE)::int as today_returns,
    (SELECT COUNT(*) FROM transactions WHERE due_date < NOW() AND returned_date IS NULL)::int as current_overdue,
    (SELECT COUNT(*) FROM students WHERE DATE(created_at) = CURRENT_DATE AND deleted_at IS NULL)::int as new_students,
    (SELECT COUNT(DISTINCT student_id) FROM transactions WHERE DATE(transaction_date) = CURRENT_DATE)::int as active_users,
    COALESCE((SELECT SUM(available_copies) FROM books WHERE deleted_at IS NULL AND is_active = true), 0)::int as available_books,
    (SELECT COUNT(*) FROM reservations WHERE status = 'active' AND expires_at > NOW())::int as pending_reservations,
    0::int as system_alerts,  -- Placeholder for future alerts system
    NOW() as last_updated
`

type GetDashboardMetricsRow struct {
	TodayBorrows        int32       `db:"today_borrows" json:"today_borrows"`
	TodayReturns        int32       `db:"today_returns" json:"today_returns"`
	CurrentOverdue      int32       `db:"current_overdue" json:"current_overdue"`
	NewStudents         int32       `db:"new_students" json:"new_students"`
	ActiveUsers         int32       `db:"active_users" json:"active_users"`
	AvailableBooks      int32       `db:"available_books" json:"available_books"`
	PendingReservations int32       `db:"pending_reservations" json:"pending_reservations"`
	SystemAlerts        int32       `db:"system_alerts" json:"system_alerts"`
	LastUpdated         interface{} `db:"last_updated" json:"last_updated"`
}

func (q *Queries) GetDashboardMetrics(ctx context.Context) (GetDashboardMetricsRow, error) {
	row := q.db.QueryRow(ctx, getDashboardMetrics)
	var i GetDashboardMetricsRow
	err := row.Scan(
		&i.TodayBorrows,
		&i.TodayReturns,
		&i.CurrentOverdue,
		&i.NewStudents,
		&i.ActiveUsers,
		&i.AvailableBooks,
		&i.PendingReservations,
		&i.SystemAlerts,
		&i.LastUpdated,
	)
	return i, err
}

const getFinePaymentHistory = `-- name: GetFinePaymentHistory :many
SELECT
    t.id as transaction_id,
    t.fine_amount,
    t.fine_paid,
    t.fine_paid_at,
    COALESCE(t.fine_waived, false) as fine_waived,
    t.fine_waived_at,
    t.fine_waived_reason,
    t.due_date,
    t.returned_date,
    GREATEST(EXTRACT(DAY FROM (COALESCE(t.returned_date, NOW()) - t.due_date))::int, 0) as days_overdue,
    s.student_id as student_code,
    CONCAT(s.first_name, ' ', s.last_name) as student_name,
    s.department,
    b.book_id as book_code,
    b.title as book_title
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
INNER JOIN books b ON t.book_id = b.id
WHERE t.fine_amount > 0
    AND s.deleted_at IS NULL
    AND b.deleted_at IS NULL
    AND ($1::timestamp IS NULL OR t.transaction_date >= $1::timestamp)
    AND ($2::timestamp IS NULL OR t.transaction_date <= $2::timestamp)
    AND ($3::bool IS NULL OR t.fine_paid = $3::bool)
ORDER BY
    CASE WHEN t.fine_paid = false THEN 0 ELSE 1 END,
    t.fine_amount DESC
LIMIT $4 OFFSET $5
`

type GetFinePaymentHistoryParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
	Column3 bool             `db:"column_3" json:"column_3"`
	Limit   int32            `db:"limit" json:"limit"`
	Offset  int32            `db:"offset" json:"offset"`
}

type GetFinePaymentHistoryRow struct {
	TransactionID    int32            `db:"transaction_id" json:"transaction_id"`
	FineAmount       pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid         pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	FinePaidAt       pgtype.Timestamp `db:"fine_paid_at" json:"fine_paid_at"`
	FineWaived       bool             `db:"fine_waived" json:"fine_waived"`
	FineWaivedAt     pgtype.Timestamp `db:"fine_waived_at" json:"fine_waived_at"`
	FineWaivedReason pgtype.Text      `db:"fine_waived_reason" json:"fine_waived_reason"`
	DueDate          pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate     pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	DaysOverdue      interface{}      `db:"days_overdue" json:"days_overdue"`
	StudentCode      string           `db:"student_code" json:"student_code"`
	StudentName      interface{}      `db:"student_name" json:"student_name"`
	Department       pgtype.Text      `db:"department" json:"department"`
	BookCode         string           `db:"book_code" json:"book_code"`
	BookTitle        string           `db:"book_title" json:"book_title"`
}

func (q *Queries) GetFinePaymentHistory(ctx context.Context, arg GetFinePaymentHistoryParams) ([]GetFinePaymentHistoryRow, error) {
	rows, err := q.db.Query(ctx, getFinePaymentHistory,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFinePaymentHistoryRow{}
	for rows.Next() {
		var i GetFinePaymentHistoryRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.FineAmount,
			&i.FinePaid,
			&i.FinePaidAt,
			&i.FineWaived,
			&i.FineWaivedAt,
			&i.FineWaivedReason,
			&i.DueDate,
			&i.ReturnedDate,
			&i.DaysOverdue,
			&i.StudentCode,
			&i.StudentName,
			&i.Department,
			&i.BookCode,
			&i.BookTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFineStatistics = `-- name: GetFineStatistics :one
SELECT 
    COUNT(DISTINCT t.student_id)::int as students_with_fines,
    COALESCE(SUM(t.fine_amount), 0)::text as total_fines_generated,
    COALESCE(SUM(CASE WHEN t.fine_paid = true THEN t.fine_amount ELSE 0 END), 0)::text as total_fines_paid,
    COALESCE(SUM(CASE WHEN t.fine_paid = false THEN t.fine_amount ELSE 0 END), 0)::text as total_outstanding_fines,
    COALESCE(AVG(t.fine_amount), 0)::text as avg_fine_amount
FROM transactions t
WHERE t.fine_amount > 0
    AND ($1::timestamp IS NULL OR t.transaction_date >= $1::timestamp)
    AND ($2::timestamp IS NULL OR t.transaction_date <= $2::timestamp)
`

type GetFineStatisticsParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
}

type GetFineStatisticsRow struct {
	StudentsWithFines     int32  `db:"students_with_fines" json:"students_with_fines"`
	TotalFinesGenerated   string `db:"total_fines_generated" json:"total_fines_generated"`
	TotalFinesPaid        string `db:"total_fines_paid" json:"total_fines_paid"`
	TotalOutstandingFines string `db:"total_outstanding_fines" json:"total_outstanding_fines"`
	AvgFineAmount         string `db:"avg_fine_amount" json:"avg_fine_amount"`
}

func (q *Queries) GetFineStatistics(ctx context.Context, arg GetFineStatisticsParams) (GetFineStatisticsRow, error) {
	row := q.db.QueryRow(ctx, getFineStatistics, arg.Column1, arg.Column2)
	var i GetFineStatisticsRow
	err := row.Scan(
		&i.StudentsWithFines,
		&i.TotalFinesGenerated,
		&i.TotalFinesPaid,
		&i.TotalOutstandingFines,
		&i.AvgFineAmount,
	)
	return i, err
}

const getFinesByDepartment = `-- name: GetFinesByDepartment :many
SELECT
    COALESCE(s.department, 'Unknown') as department,
    COUNT(*)::int as fine_count,
    COUNT(DISTINCT s.id)::int as students_affected,
    COALESCE(SUM(t.fine_amount), 0)::text as total_fines,
    COALESCE(SUM(CASE WHEN t.fine_paid = true THEN t.fine_amount ELSE 0 END), 0)::text as paid_amount,
    COALESCE(SUM(CASE WHEN t.fine_paid = false THEN t.fine_amount ELSE 0 END), 0)::text as outstanding_amount
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
WHERE t.fine_amount > 0
    AND s.deleted_at IS NULL
    AND ($1::timestamp IS NULL OR t.transaction_date >= $1::timestamp)
    AND ($2::timestamp IS NULL OR t.transaction_date <= $2::timestamp)
GROUP BY s.department
ORDER BY total_fines DESC
`

type GetFinesByDepartmentParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
}

type GetFinesByDepartmentRow struct {
	Department        string `db:"department" json:"department"`
	FineCount         int32  `db:"fine_count" json:"fine_count"`
	StudentsAffected  int32  `db:"students_affected" json:"students_affected"`
	TotalFines        string `db:"total_fines" json:"total_fines"`
	PaidAmount        string `db:"paid_amount" json:"paid_amount"`
	OutstandingAmount string `db:"outstanding_amount" json:"outstanding_amount"`
}

func (q *Queries) GetFinesByDepartment(ctx context.Context, arg GetFinesByDepartmentParams) ([]GetFinesByDepartmentRow, error) {
	rows, err := q.db.Query(ctx, getFinesByDepartment, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFinesByDepartmentRow{}
	for rows.Next() {
		var i GetFinesByDepartmentRow
		if err := rows.Scan(
			&i.Department,
			&i.FineCount,
			&i.StudentsAffected,
			&i.TotalFines,
			&i.PaidAmount,
			&i.OutstandingAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFinesByYearOfStudy = `-- name: GetFinesByYearOfStudy :many
SELECT
    s.year_of_study,
    COUNT(*)::int as fine_count,
    COUNT(DISTINCT s.id)::int as students_affected,
    COALESCE(SUM(t.fine_amount), 0)::text as total_fines,
    COALESCE(SUM(CASE WHEN t.fine_paid = true THEN t.fine_amount ELSE 0 END), 0)::text as paid_amount,
    COALESCE(SUM(CASE WHEN t.fine_paid = false THEN t.fine_amount ELSE 0 END), 0)::text as outstanding_amount
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
WHERE t.fine_amount > 0
    AND s.deleted_at IS NULL
    AND ($1::timestamp IS NULL OR t.transaction_date >= $1::timestamp)
    AND ($2::timestamp IS NULL OR t.transaction_date <= $2::timestamp)
GROUP BY s.year_of_study
ORDER BY s.year_of_study
`

type GetFinesByYearOfStudyParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
}

type GetFinesByYearOfStudyRow struct {
	YearOfStudy       int32  `db:"year_of_study" json:"year_of_study"`
	FineCount         int32  `db:"fine_count" json:"fine_count"`
	StudentsAffected  int32  `db:"students_affected" json:"students_affected"`
	TotalFines        string `db:"total_fines" json:"total_fines"`
	PaidAmount        string `db:"paid_amount" json:"paid_amount"`
	OutstandingAmount string `db:"outstanding_amount" json:"outstanding_amount"`
}

func (q *Queries) GetFinesByYearOfStudy(ctx context.Context, arg GetFinesByYearOfStudyParams) ([]GetFinesByYearOfStudyRow, error) {
	rows, err := q.db.Query(ctx, getFinesByYearOfStudy, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFinesByYearOfStudyRow{}
	for rows.Next() {
		var i GetFinesByYearOfStudyRow
		if err := rows.Scan(
			&i.YearOfStudy,
			&i.FineCount,
			&i.StudentsAffected,
			&i.TotalFines,
			&i.PaidAmount,
			&i.OutstandingAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFinesCollectionSummary = `-- name: GetFinesCollectionSummary :one

SELECT
    COUNT(*) FILTER (WHERE t.fine_amount > 0)::int as total_fine_records,
    COUNT(DISTINCT t.student_id) FILTER (WHERE t.fine_amount > 0 AND t.fine_paid = false AND COALESCE(t.fine_waived, false) = false)::int as students_with_outstanding,
    COALESCE(SUM(t.fine_amount), 0)::text as total_fines_generated,
    COALESCE(SUM(CASE WHEN t.fine_paid = true AND COALESCE(t.fine_waived, false) = false THEN t.fine_amount ELSE 0 END), 0)::text as total_collected,
    COALESCE(SUM(CASE WHEN t.fine_paid = false AND COALESCE(t.fine_waived, false) = false THEN t.fine_amount ELSE 0 END), 0)::text as total_outstanding,
    COALESCE(SUM(CASE WHEN COALESCE(t.fine_waived, false) = true THEN t.fine_amount ELSE 0 END), 0)::text as total_waived,
    COALESCE(AVG(t.fine_amount) FILTER (WHERE t.fine_amount > 0), 0)::text as average_fine
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
WHERE s.deleted_at IS NULL
    AND ($1::timestamp IS NULL OR t.transaction_date >= $1::timestamp)
    AND ($2::timestamp IS NULL OR t.transaction_date <= $2::timestamp)
`

type GetFinesCollectionSummaryParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
}

type GetFinesCollectionSummaryRow struct {
	TotalFineRecords        int32  `db:"total_fine_records" json:"total_fine_records"`
	StudentsWithOutstanding int32  `db:"students_with_outstanding" json:"students_with_outstanding"`
	TotalFinesGenerated     string `db:"total_fines_generated" json:"total_fines_generated"`
	TotalCollected          string `db:"total_collected" json:"total_collected"`
	TotalOutstanding        string `db:"total_outstanding" json:"total_outstanding"`
	TotalWaived             string `db:"total_waived" json:"total_waived"`
	AverageFine             string `db:"average_fine" json:"average_fine"`
}

// ============================================
// Fines Collection Report Queries
// ============================================
func (q *Queries) GetFinesCollectionSummary(ctx context.Context, arg GetFinesCollectionSummaryParams) (GetFinesCollectionSummaryRow, error) {
	row := q.db.QueryRow(ctx, getFinesCollectionSummary, arg.Column1, arg.Column2)
	var i GetFinesCollectionSummaryRow
	err := row.Scan(
		&i.TotalFineRecords,
		&i.StudentsWithOutstanding,
		&i.TotalFinesGenerated,
		&i.TotalCollected,
		&i.TotalOutstanding,
		&i.TotalWaived,
		&i.AverageFine,
	)
	return i, err
}

const getFinesCollectionTrend = `-- name: GetFinesCollectionTrend :many
SELECT
    TO_CHAR(DATE_TRUNC($3::text, t.transaction_date),
        CASE
            WHEN $3::text = 'day' THEN 'YYYY-MM-DD'
            WHEN $3::text = 'week' THEN 'YYYY-"W"IW'
            WHEN $3::text = 'month' THEN 'YYYY-MM'
            WHEN $3::text = 'year' THEN 'YYYY'
            ELSE 'YYYY-MM'
        END
    ) as period,
    COUNT(*)::int as fine_count,
    COALESCE(SUM(t.fine_amount), 0)::text as generated,
    COALESCE(SUM(CASE WHEN t.fine_paid = true THEN t.fine_amount ELSE 0 END), 0)::text as collected,
    COALESCE(SUM(CASE WHEN t.fine_paid = false THEN t.fine_amount ELSE 0 END), 0)::text as outstanding
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
WHERE t.fine_amount > 0
    AND s.deleted_at IS NULL
    AND t.transaction_date >= $1::timestamp
    AND t.transaction_date <= $2::timestamp
GROUP BY DATE_TRUNC($3::text, t.transaction_date)
ORDER BY period
`

type GetFinesCollectionTrendParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
	Column3 string           `db:"column_3" json:"column_3"`
}

type GetFinesCollectionTrendRow struct {
	Period      string `db:"period" json:"period"`
	FineCount   int32  `db:"fine_count" json:"fine_count"`
	Generated   string `db:"generated" json:"generated"`
	Collected   string `db:"collected" json:"collected"`
	Outstanding string `db:"outstanding" json:"outstanding"`
}

func (q *Queries) GetFinesCollectionTrend(ctx context.Context, arg GetFinesCollectionTrendParams) ([]GetFinesCollectionTrendRow, error) {
	rows, err := q.db.Query(ctx, getFinesCollectionTrend, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFinesCollectionTrendRow{}
	for rows.Next() {
		var i GetFinesCollectionTrendRow
		if err := rows.Scan(
			&i.Period,
			&i.FineCount,
			&i.Generated,
			&i.Collected,
			&i.Outstanding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGenrePopularity = `-- name: GetGenrePopularity :many
SELECT 
    COALESCE(b.genre, 'Uncategorized') as genre,
    COUNT(t.id)::int as total_borrows,
    COUNT(DISTINCT t.student_id)::int as unique_borrowers,
    COUNT(DISTINCT b.id)::int as unique_books,
    ROUND(COUNT(t.id)::numeric / COUNT(DISTINCT b.id)::numeric, 2)::text as avg_borrows_per_book
FROM books b
INNER JOIN transactions t ON b.id = t.book_id
WHERE t.transaction_type = 'borrow'
    AND t.transaction_date >= $1::timestamp
    AND t.transaction_date <= $2::timestamp
    AND b.deleted_at IS NULL
GROUP BY b.genre
ORDER BY total_borrows DESC
`

type GetGenrePopularityParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
}

type GetGenrePopularityRow struct {
	Genre             string `db:"genre" json:"genre"`
	TotalBorrows      int32  `db:"total_borrows" json:"total_borrows"`
	UniqueBorrowers   int32  `db:"unique_borrowers" json:"unique_borrowers"`
	UniqueBooks       int32  `db:"unique_books" json:"unique_books"`
	AvgBorrowsPerBook string `db:"avg_borrows_per_book" json:"avg_borrows_per_book"`
}

func (q *Queries) GetGenrePopularity(ctx context.Context, arg GetGenrePopularityParams) ([]GetGenrePopularityRow, error) {
	rows, err := q.db.Query(ctx, getGenrePopularity, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetGenrePopularityRow{}
	for rows.Next() {
		var i GetGenrePopularityRow
		if err := rows.Scan(
			&i.Genre,
			&i.TotalBorrows,
			&i.UniqueBorrowers,
			&i.UniqueBooks,
			&i.AvgBorrowsPerBook,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndividualStudentProfile = `-- name: GetIndividualStudentProfile :one

SELECT
    s.id,
    s.student_id,
    s.first_name,
    s.last_name,
    s.email,
    s.phone,
    s.year_of_study,
    s.department,
    s.max_books,
    s.is_active,
    s.created_at as member_since,
    (SELECT COUNT(*) FROM transactions WHERE student_id = s.id AND transaction_type = 'borrow')::int as total_books_borrowed,
    (SELECT COUNT(*) FROM transactions WHERE student_id = s.id AND returned_date IS NULL)::int as currently_borrowed,
    (SELECT COUNT(*) FROM transactions WHERE student_id = s.id AND due_date < NOW() AND returned_date IS NULL)::int as overdue_count,
    COALESCE((SELECT SUM(fine_amount) FROM transactions WHERE student_id = s.id AND fine_paid = false AND COALESCE(fine_waived, false) = false), 0)::text as outstanding_fines,
    COALESCE((SELECT SUM(fine_amount) FROM transactions WHERE student_id = s.id AND fine_paid = true), 0)::text as total_fines_paid
FROM students s
WHERE s.id = $1 AND s.deleted_at IS NULL
`

type GetIndividualStudentProfileRow struct {
	ID                 int32            `db:"id" json:"id"`
	StudentID          string           `db:"student_id" json:"student_id"`
	FirstName          string           `db:"first_name" json:"first_name"`
	LastName           string           `db:"last_name" json:"last_name"`
	Email              pgtype.Text      `db:"email" json:"email"`
	Phone              pgtype.Text      `db:"phone" json:"phone"`
	YearOfStudy        int32            `db:"year_of_study" json:"year_of_study"`
	Department         pgtype.Text      `db:"department" json:"department"`
	MaxBooks           int32            `db:"max_books" json:"max_books"`
	IsActive           pgtype.Bool      `db:"is_active" json:"is_active"`
	MemberSince        pgtype.Timestamp `db:"member_since" json:"member_since"`
	TotalBooksBorrowed int32            `db:"total_books_borrowed" json:"total_books_borrowed"`
	CurrentlyBorrowed  int32            `db:"currently_borrowed" json:"currently_borrowed"`
	OverdueCount       int32            `db:"overdue_count" json:"overdue_count"`
	OutstandingFines   string           `db:"outstanding_fines" json:"outstanding_fines"`
	TotalFinesPaid     string           `db:"total_fines_paid" json:"total_fines_paid"`
}

// ============================================
// Individual Student Report Queries
// ============================================
func (q *Queries) GetIndividualStudentProfile(ctx context.Context, id int32) (GetIndividualStudentProfileRow, error) {
	row := q.db.QueryRow(ctx, getIndividualStudentProfile, id)
	var i GetIndividualStudentProfileRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.Phone,
		&i.YearOfStudy,
		&i.Department,
		&i.MaxBooks,
		&i.IsActive,
		&i.MemberSince,
		&i.TotalBooksBorrowed,
		&i.CurrentlyBorrowed,
		&i.OverdueCount,
		&i.OutstandingFines,
		&i.TotalFinesPaid,
	)
	return i, err
}

const getInventoryStatus = `-- name: GetInventoryStatus :many
SELECT 
    COALESCE(b.genre, 'Uncategorized') as genre,
    COUNT(b.id)::int as total_books,
    SUM(b.available_copies)::int as available_books,
    COUNT(DISTINCT t.id)::int as borrowed_books,
    COUNT(DISTINCT r.id)::int as reserved_books,
    CASE 
        WHEN COUNT(b.id) > 0 THEN 
            ROUND(((COUNT(DISTINCT t.id) + COUNT(DISTINCT r.id))::numeric / COUNT(b.id)::numeric) * 100, 2)::text
        ELSE '0.00'
    END as utilization_rate
FROM books b
LEFT JOIN transactions t ON b.id = t.book_id 
    AND t.transaction_type = 'borrow' 
    AND t.returned_date IS NULL
LEFT JOIN reservations r ON b.id = r.book_id 
    AND r.status = 'active' 
    AND r.expires_at > NOW()
WHERE b.deleted_at IS NULL
    AND b.is_active = true
GROUP BY b.genre
ORDER BY total_books DESC
`

type GetInventoryStatusRow struct {
	Genre           string `db:"genre" json:"genre"`
	TotalBooks      int32  `db:"total_books" json:"total_books"`
	AvailableBooks  int32  `db:"available_books" json:"available_books"`
	BorrowedBooks   int32  `db:"borrowed_books" json:"borrowed_books"`
	ReservedBooks   int32  `db:"reserved_books" json:"reserved_books"`
	UtilizationRate string `db:"utilization_rate" json:"utilization_rate"`
}

func (q *Queries) GetInventoryStatus(ctx context.Context) ([]GetInventoryStatusRow, error) {
	rows, err := q.db.Query(ctx, getInventoryStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetInventoryStatusRow{}
	for rows.Next() {
		var i GetInventoryStatusRow
		if err := rows.Scan(
			&i.Genre,
			&i.TotalBooks,
			&i.AvailableBooks,
			&i.BorrowedBooks,
			&i.ReservedBooks,
			&i.UtilizationRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLibraryOverview = `-- name: GetLibraryOverview :one
SELECT
    (SELECT COUNT(*) FROM books WHERE deleted_at IS NULL AND is_active = true)::int as total_books,
    (SELECT COUNT(*) FROM students WHERE deleted_at IS NULL AND is_active = true)::int as total_students,
    (SELECT COUNT(*) FROM transactions WHERE transaction_type = 'borrow')::int as total_borrows,
    (SELECT COUNT(*) FROM transactions WHERE transaction_type = 'borrow' AND returned_date IS NULL)::int as active_borrows,
    (SELECT COUNT(*) FROM transactions WHERE due_date < NOW() AND returned_date IS NULL)::int as overdue_books,
    (SELECT COUNT(*) FROM reservations WHERE status = 'active' AND expires_at > NOW())::int as total_reservations,
    COALESCE((SELECT SUM(available_copies) FROM books WHERE deleted_at IS NULL AND is_active = true), 0)::int as available_books,
    COALESCE((SELECT SUM(fine_amount) FROM transactions WHERE fine_paid = false), 0)::text as total_fines
`

type GetLibraryOverviewRow struct {
	TotalBooks        int32  `db:"total_books" json:"total_books"`
	TotalStudents     int32  `db:"total_students" json:"total_students"`
	TotalBorrows      int32  `db:"total_borrows" json:"total_borrows"`
	ActiveBorrows     int32  `db:"active_borrows" json:"active_borrows"`
	OverdueBooks      int32  `db:"overdue_books" json:"overdue_books"`
	TotalReservations int32  `db:"total_reservations" json:"total_reservations"`
	AvailableBooks    int32  `db:"available_books" json:"available_books"`
	TotalFines        string `db:"total_fines" json:"total_fines"`
}

func (q *Queries) GetLibraryOverview(ctx context.Context) (GetLibraryOverviewRow, error) {
	row := q.db.QueryRow(ctx, getLibraryOverview)
	var i GetLibraryOverviewRow
	err := row.Scan(
		&i.TotalBooks,
		&i.TotalStudents,
		&i.TotalBorrows,
		&i.ActiveBorrows,
		&i.OverdueBooks,
		&i.TotalReservations,
		&i.AvailableBooks,
		&i.TotalFines,
	)
	return i, err
}

const getLostBooksByCategory = `-- name: GetLostBooksByCategory :many
SELECT
    COALESCE(b.genre, 'Uncategorized') as genre,
    COUNT(*)::int as lost_count,
    COALESCE(SUM(t.fine_amount), 0)::text as total_value,
    COALESCE(AVG(t.fine_amount), 0)::text as avg_value
FROM transactions t
INNER JOIN books b ON t.book_id = b.id
WHERE t.transaction_type = 'lost'
    AND b.deleted_at IS NULL
    AND ($1::timestamp IS NULL OR t.transaction_date >= $1::timestamp)
    AND ($2::timestamp IS NULL OR t.transaction_date <= $2::timestamp)
GROUP BY b.genre
ORDER BY lost_count DESC
`

type GetLostBooksByCategoryParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
}

type GetLostBooksByCategoryRow struct {
	Genre      string `db:"genre" json:"genre"`
	LostCount  int32  `db:"lost_count" json:"lost_count"`
	TotalValue string `db:"total_value" json:"total_value"`
	AvgValue   string `db:"avg_value" json:"avg_value"`
}

func (q *Queries) GetLostBooksByCategory(ctx context.Context, arg GetLostBooksByCategoryParams) ([]GetLostBooksByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getLostBooksByCategory, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLostBooksByCategoryRow{}
	for rows.Next() {
		var i GetLostBooksByCategoryRow
		if err := rows.Scan(
			&i.Genre,
			&i.LostCount,
			&i.TotalValue,
			&i.AvgValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLostBooksByDepartment = `-- name: GetLostBooksByDepartment :many
SELECT
    COALESCE(s.department, 'Unknown') as department,
    COUNT(*)::int as lost_count,
    COALESCE(SUM(t.fine_amount), 0)::text as total_value,
    COUNT(DISTINCT s.id)::int as students_affected
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
WHERE t.transaction_type = 'lost'
    AND s.deleted_at IS NULL
    AND ($1::timestamp IS NULL OR t.transaction_date >= $1::timestamp)
    AND ($2::timestamp IS NULL OR t.transaction_date <= $2::timestamp)
GROUP BY s.department
ORDER BY lost_count DESC
`

type GetLostBooksByDepartmentParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
}

type GetLostBooksByDepartmentRow struct {
	Department       string `db:"department" json:"department"`
	LostCount        int32  `db:"lost_count" json:"lost_count"`
	TotalValue       string `db:"total_value" json:"total_value"`
	StudentsAffected int32  `db:"students_affected" json:"students_affected"`
}

func (q *Queries) GetLostBooksByDepartment(ctx context.Context, arg GetLostBooksByDepartmentParams) ([]GetLostBooksByDepartmentRow, error) {
	rows, err := q.db.Query(ctx, getLostBooksByDepartment, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLostBooksByDepartmentRow{}
	for rows.Next() {
		var i GetLostBooksByDepartmentRow
		if err := rows.Scan(
			&i.Department,
			&i.LostCount,
			&i.TotalValue,
			&i.StudentsAffected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLostBooksReport = `-- name: GetLostBooksReport :many

SELECT
    t.id as transaction_id,
    t.transaction_date as lost_date,
    t.fine_amount as replacement_cost,
    t.fine_paid,
    t.notes,
    s.student_id as student_code,
    CONCAT(s.first_name, ' ', s.last_name) as student_name,
    s.year_of_study,
    s.department,
    b.book_id as book_code,
    b.title as book_title,
    b.author as book_author,
    b.genre,
    b.isbn,
    '0.00'::text as original_price  -- price column doesn't exist in books table
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
INNER JOIN books b ON t.book_id = b.id
WHERE t.transaction_type = 'lost'
    AND s.deleted_at IS NULL
    AND b.deleted_at IS NULL
    AND ($1::timestamp IS NULL OR t.transaction_date >= $1::timestamp)
    AND ($2::timestamp IS NULL OR t.transaction_date <= $2::timestamp)
    AND ($3::text IS NULL OR $3 = '' OR s.department = $3::text)
    AND ($4::text IS NULL OR $4 = '' OR b.genre = $4::text)
ORDER BY t.transaction_date DESC
`

type GetLostBooksReportParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
	Column3 string           `db:"column_3" json:"column_3"`
	Column4 string           `db:"column_4" json:"column_4"`
}

type GetLostBooksReportRow struct {
	TransactionID   int32            `db:"transaction_id" json:"transaction_id"`
	LostDate        pgtype.Timestamp `db:"lost_date" json:"lost_date"`
	ReplacementCost pgtype.Numeric   `db:"replacement_cost" json:"replacement_cost"`
	FinePaid        pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	Notes           pgtype.Text      `db:"notes" json:"notes"`
	StudentCode     string           `db:"student_code" json:"student_code"`
	StudentName     interface{}      `db:"student_name" json:"student_name"`
	YearOfStudy     int32            `db:"year_of_study" json:"year_of_study"`
	Department      pgtype.Text      `db:"department" json:"department"`
	BookCode        string           `db:"book_code" json:"book_code"`
	BookTitle       string           `db:"book_title" json:"book_title"`
	BookAuthor      string           `db:"book_author" json:"book_author"`
	Genre           pgtype.Text      `db:"genre" json:"genre"`
	Isbn            pgtype.Text      `db:"isbn" json:"isbn"`
	OriginalPrice   string           `db:"original_price" json:"original_price"`
}

// ============================================
// Lost Books Report Queries
// ============================================
func (q *Queries) GetLostBooksReport(ctx context.Context, arg GetLostBooksReportParams) ([]GetLostBooksReportRow, error) {
	rows, err := q.db.Query(ctx, getLostBooksReport,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLostBooksReportRow{}
	for rows.Next() {
		var i GetLostBooksReportRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.LostDate,
			&i.ReplacementCost,
			&i.FinePaid,
			&i.Notes,
			&i.StudentCode,
			&i.StudentName,
			&i.YearOfStudy,
			&i.Department,
			&i.BookCode,
			&i.BookTitle,
			&i.BookAuthor,
			&i.Genre,
			&i.Isbn,
			&i.OriginalPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLostBooksSummary = `-- name: GetLostBooksSummary :one
SELECT
    COUNT(*)::int as total_lost_books,
    COALESCE(SUM(t.fine_amount), 0)::text as total_replacement_value,
    COALESCE(SUM(CASE WHEN t.fine_paid = true THEN t.fine_amount ELSE 0 END), 0)::text as collected_amount,
    COALESCE(SUM(CASE WHEN t.fine_paid = false THEN t.fine_amount ELSE 0 END), 0)::text as outstanding_amount,
    COUNT(DISTINCT t.student_id)::int as students_affected,
    COUNT(DISTINCT b.genre)::int as genres_affected
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
INNER JOIN books b ON t.book_id = b.id
WHERE t.transaction_type = 'lost'
    AND s.deleted_at IS NULL
    AND b.deleted_at IS NULL
    AND ($1::timestamp IS NULL OR t.transaction_date >= $1::timestamp)
    AND ($2::timestamp IS NULL OR t.transaction_date <= $2::timestamp)
`

type GetLostBooksSummaryParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
}

type GetLostBooksSummaryRow struct {
	TotalLostBooks        int32  `db:"total_lost_books" json:"total_lost_books"`
	TotalReplacementValue string `db:"total_replacement_value" json:"total_replacement_value"`
	CollectedAmount       string `db:"collected_amount" json:"collected_amount"`
	OutstandingAmount     string `db:"outstanding_amount" json:"outstanding_amount"`
	StudentsAffected      int32  `db:"students_affected" json:"students_affected"`
	GenresAffected        int32  `db:"genres_affected" json:"genres_affected"`
}

func (q *Queries) GetLostBooksSummary(ctx context.Context, arg GetLostBooksSummaryParams) (GetLostBooksSummaryRow, error) {
	row := q.db.QueryRow(ctx, getLostBooksSummary, arg.Column1, arg.Column2)
	var i GetLostBooksSummaryRow
	err := row.Scan(
		&i.TotalLostBooks,
		&i.TotalReplacementValue,
		&i.CollectedAmount,
		&i.OutstandingAmount,
		&i.StudentsAffected,
		&i.GenresAffected,
	)
	return i, err
}

const getLostBooksTrend = `-- name: GetLostBooksTrend :many
SELECT
    TO_CHAR(DATE_TRUNC($3::text, t.transaction_date),
        CASE
            WHEN $3::text = 'day' THEN 'YYYY-MM-DD'
            WHEN $3::text = 'week' THEN 'YYYY-"W"IW'
            WHEN $3::text = 'month' THEN 'YYYY-MM'
            WHEN $3::text = 'year' THEN 'YYYY'
            ELSE 'YYYY-MM'
        END
    ) as period,
    COUNT(*)::int as lost_count,
    COALESCE(SUM(t.fine_amount), 0)::text as replacement_value
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
WHERE t.transaction_type = 'lost'
    AND s.deleted_at IS NULL
    AND t.transaction_date >= $1::timestamp
    AND t.transaction_date <= $2::timestamp
GROUP BY DATE_TRUNC($3::text, t.transaction_date)
ORDER BY period
`

type GetLostBooksTrendParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
	Column3 string           `db:"column_3" json:"column_3"`
}

type GetLostBooksTrendRow struct {
	Period           string `db:"period" json:"period"`
	LostCount        int32  `db:"lost_count" json:"lost_count"`
	ReplacementValue string `db:"replacement_value" json:"replacement_value"`
}

func (q *Queries) GetLostBooksTrend(ctx context.Context, arg GetLostBooksTrendParams) ([]GetLostBooksTrendRow, error) {
	rows, err := q.db.Query(ctx, getLostBooksTrend, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLostBooksTrendRow{}
	for rows.Next() {
		var i GetLostBooksTrendRow
		if err := rows.Scan(&i.Period, &i.LostCount, &i.ReplacementValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMonthlyTrends = `-- name: GetMonthlyTrends :many
SELECT 
    TO_CHAR(DATE_TRUNC('month', t.transaction_date), 'YYYY-MM') as month,
    COUNT(CASE WHEN t.transaction_type = 'borrow' THEN 1 END)::int as borrows,
    COUNT(CASE WHEN t.transaction_type = 'return' THEN 1 END)::int as returns,
    COUNT(DISTINCT t.student_id)::int as active_students,
    COALESCE(AVG(EXTRACT(DAY FROM (t.returned_date - t.transaction_date))), 0)::int as avg_loan_duration_days
FROM transactions t
WHERE t.transaction_date >= $1::timestamp
    AND t.transaction_date <= $2::timestamp
GROUP BY DATE_TRUNC('month', t.transaction_date)
ORDER BY month
`

type GetMonthlyTrendsParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
}

type GetMonthlyTrendsRow struct {
	Month               string `db:"month" json:"month"`
	Borrows             int32  `db:"borrows" json:"borrows"`
	Returns             int32  `db:"returns" json:"returns"`
	ActiveStudents      int32  `db:"active_students" json:"active_students"`
	AvgLoanDurationDays int32  `db:"avg_loan_duration_days" json:"avg_loan_duration_days"`
}

func (q *Queries) GetMonthlyTrends(ctx context.Context, arg GetMonthlyTrendsParams) ([]GetMonthlyTrendsRow, error) {
	rows, err := q.db.Query(ctx, getMonthlyTrends, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMonthlyTrendsRow{}
	for rows.Next() {
		var i GetMonthlyTrendsRow
		if err := rows.Scan(
			&i.Month,
			&i.Borrows,
			&i.Returns,
			&i.ActiveStudents,
			&i.AvgLoanDurationDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverdueBooksByYear = `-- name: GetOverdueBooksByYear :many
SELECT 
    s.student_id,
    CONCAT(s.first_name, ' ', s.last_name) as student_name,
    s.year_of_study,
    s.department,
    b.title as book_title,
    b.author as book_author,
    t.due_date,
    EXTRACT(DAY FROM (NOW() - t.due_date))::int as days_overdue,
    COALESCE(t.fine_amount::text, '0.00') as fine_amount,
    t.id as transaction_id
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
INNER JOIN books b ON t.book_id = b.id
WHERE t.due_date < NOW()
    AND t.returned_date IS NULL
    AND ($1::int IS NULL OR s.year_of_study = $1::int)
    AND ($2::text IS NULL OR s.department = $2::text)
    AND s.deleted_at IS NULL
    AND b.deleted_at IS NULL
ORDER BY t.due_date ASC
`

type GetOverdueBooksByYearParams struct {
	Column1 int32  `db:"column_1" json:"column_1"`
	Column2 string `db:"column_2" json:"column_2"`
}

type GetOverdueBooksByYearRow struct {
	StudentID     string           `db:"student_id" json:"student_id"`
	StudentName   interface{}      `db:"student_name" json:"student_name"`
	YearOfStudy   int32            `db:"year_of_study" json:"year_of_study"`
	Department    pgtype.Text      `db:"department" json:"department"`
	BookTitle     string           `db:"book_title" json:"book_title"`
	BookAuthor    string           `db:"book_author" json:"book_author"`
	DueDate       pgtype.Timestamp `db:"due_date" json:"due_date"`
	DaysOverdue   int32            `db:"days_overdue" json:"days_overdue"`
	FineAmount    interface{}      `db:"fine_amount" json:"fine_amount"`
	TransactionID int32            `db:"transaction_id" json:"transaction_id"`
}

func (q *Queries) GetOverdueBooksByYear(ctx context.Context, arg GetOverdueBooksByYearParams) ([]GetOverdueBooksByYearRow, error) {
	rows, err := q.db.Query(ctx, getOverdueBooksByYear, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOverdueBooksByYearRow{}
	for rows.Next() {
		var i GetOverdueBooksByYearRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentName,
			&i.YearOfStudy,
			&i.Department,
			&i.BookTitle,
			&i.BookAuthor,
			&i.DueDate,
			&i.DaysOverdue,
			&i.FineAmount,
			&i.TransactionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPopularBooks = `-- name: GetPopularBooks :many
SELECT 
    b.book_id,
    b.title,
    b.author,
    b.genre,
    COUNT(t.id)::int as borrow_count,
    COUNT(DISTINCT t.student_id)::int as unique_users,
    '4.5' as avg_rating  -- Placeholder for future rating system
FROM books b
INNER JOIN transactions t ON b.id = t.book_id
INNER JOIN students s ON t.student_id = s.id
WHERE t.transaction_type = 'borrow'
    AND t.transaction_date >= $1::timestamp
    AND t.transaction_date <= $2::timestamp
    AND ($4::int IS NULL OR s.year_of_study = $4::int)
    AND b.deleted_at IS NULL
    AND s.deleted_at IS NULL
GROUP BY b.id, b.book_id, b.title, b.author, b.genre
ORDER BY borrow_count DESC, unique_users DESC
LIMIT $3::int
`

type GetPopularBooksParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
	Column3 int32            `db:"column_3" json:"column_3"`
	Column4 int32            `db:"column_4" json:"column_4"`
}

type GetPopularBooksRow struct {
	BookID      string      `db:"book_id" json:"book_id"`
	Title       string      `db:"title" json:"title"`
	Author      string      `db:"author" json:"author"`
	Genre       pgtype.Text `db:"genre" json:"genre"`
	BorrowCount int32       `db:"borrow_count" json:"borrow_count"`
	UniqueUsers int32       `db:"unique_users" json:"unique_users"`
	AvgRating   string      `db:"avg_rating" json:"avg_rating"`
}

func (q *Queries) GetPopularBooks(ctx context.Context, arg GetPopularBooksParams) ([]GetPopularBooksRow, error) {
	rows, err := q.db.Query(ctx, getPopularBooks,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPopularBooksRow{}
	for rows.Next() {
		var i GetPopularBooksRow
		if err := rows.Scan(
			&i.BookID,
			&i.Title,
			&i.Author,
			&i.Genre,
			&i.BorrowCount,
			&i.UniqueUsers,
			&i.AvgRating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRiskAnalysis = `-- name: GetRiskAnalysis :many
SELECT
    'overdue_books' as risk_category,
    COUNT(*)::int as risk_count,
    CASE
        WHEN COUNT(*) > 100 THEN 'High'
        WHEN COUNT(*) > 50 THEN 'Medium'
        ELSE 'Low'
    END as risk_level,
    COALESCE(SUM(fine_amount), 0)::text as financial_impact,
    'Books overdue for more than 7 days' as description
FROM transactions
WHERE due_date < NOW() - INTERVAL '7 days'
AND returned_date IS NULL

UNION ALL

SELECT
    'students_with_multiple_overdue' as risk_category,
    COUNT(DISTINCT student_id)::int as risk_count,
    CASE
        WHEN COUNT(DISTINCT student_id) > 20 THEN 'High'
        WHEN COUNT(DISTINCT student_id) > 10 THEN 'Medium'
        ELSE 'Low'
    END as risk_level,
    COALESCE(SUM(fine_amount), 0)::text as financial_impact,
    'Students with 3+ overdue books' as description
FROM transactions
WHERE due_date < NOW() AND returned_date IS NULL
GROUP BY student_id
HAVING COUNT(*) >= 3

UNION ALL

SELECT
    'high_demand_books_low_copies' as risk_category,
    COUNT(*)::int as risk_count,
    CASE
        WHEN COUNT(*) > 10 THEN 'High'
        WHEN COUNT(*) > 5 THEN 'Medium'
        ELSE 'Low'
    END as risk_level,
    '0.00' as financial_impact,
    'Books with high reservations but low total copies' as description
FROM (
    SELECT b.id
    FROM books b
    WHERE (
        SELECT COUNT(*) FROM reservations r
        WHERE r.book_id = b.id AND r.status = 'active' AND r.expires_at > NOW()
    ) >= b.total_copies * 0.5
    AND b.total_copies < 5
    AND b.deleted_at IS NULL
    AND b.is_active = true
) risky_books

UNION ALL

SELECT
    'unpaid_fines' as risk_category,
    COUNT(DISTINCT student_id)::int as risk_count,
    CASE
        WHEN COALESCE(SUM(fine_amount), 0) > 1000 THEN 'High'
        WHEN COALESCE(SUM(fine_amount), 0) > 500 THEN 'Medium'
        ELSE 'Low'
    END as risk_level,
    COALESCE(SUM(fine_amount), 0)::text as financial_impact,
    'Outstanding unpaid fines' as description
FROM transactions
WHERE fine_amount > 0 AND fine_paid = false

ORDER BY
    CASE risk_level
        WHEN 'High' THEN 1
        WHEN 'Medium' THEN 2
        ELSE 3
    END,
    risk_count DESC
`

type GetRiskAnalysisRow struct {
	RiskCategory    string `db:"risk_category" json:"risk_category"`
	RiskCount       int32  `db:"risk_count" json:"risk_count"`
	RiskLevel       string `db:"risk_level" json:"risk_level"`
	FinancialImpact string `db:"financial_impact" json:"financial_impact"`
	Description     string `db:"description" json:"description"`
}

func (q *Queries) GetRiskAnalysis(ctx context.Context) ([]GetRiskAnalysisRow, error) {
	rows, err := q.db.Query(ctx, getRiskAnalysis)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRiskAnalysisRow{}
	for rows.Next() {
		var i GetRiskAnalysisRow
		if err := rows.Scan(
			&i.RiskCategory,
			&i.RiskCount,
			&i.RiskLevel,
			&i.FinancialImpact,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeasonalTrends = `-- name: GetSeasonalTrends :many
SELECT 
    CASE 
        WHEN EXTRACT(MONTH FROM t.transaction_date) IN (12, 1, 2) THEN 'Winter'
        WHEN EXTRACT(MONTH FROM t.transaction_date) IN (3, 4, 5) THEN 'Spring'
        WHEN EXTRACT(MONTH FROM t.transaction_date) IN (6, 7, 8) THEN 'Summer'
        ELSE 'Fall'
    END as season,
    EXTRACT(YEAR FROM t.transaction_date)::int as year,
    COUNT(CASE WHEN t.transaction_type = 'borrow' THEN 1 END)::int as total_borrows,
    COUNT(CASE WHEN t.transaction_type = 'return' THEN 1 END)::int as total_returns,
    COUNT(DISTINCT t.student_id)::int as unique_students,
    COUNT(DISTINCT t.book_id)::int as unique_books,
    COALESCE(AVG(EXTRACT(DAY FROM (t.returned_date - t.transaction_date))), 0)::text as avg_loan_duration
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
WHERE t.transaction_date >= $1::timestamp
    AND t.transaction_date <= $2::timestamp
    AND s.deleted_at IS NULL
GROUP BY 
    CASE 
        WHEN EXTRACT(MONTH FROM t.transaction_date) IN (12, 1, 2) THEN 'Winter'
        WHEN EXTRACT(MONTH FROM t.transaction_date) IN (3, 4, 5) THEN 'Spring'
        WHEN EXTRACT(MONTH FROM t.transaction_date) IN (6, 7, 8) THEN 'Summer'
        ELSE 'Fall'
    END,
    EXTRACT(YEAR FROM t.transaction_date)
ORDER BY year, season
`

type GetSeasonalTrendsParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
}

type GetSeasonalTrendsRow struct {
	Season          string `db:"season" json:"season"`
	Year            int32  `db:"year" json:"year"`
	TotalBorrows    int32  `db:"total_borrows" json:"total_borrows"`
	TotalReturns    int32  `db:"total_returns" json:"total_returns"`
	UniqueStudents  int32  `db:"unique_students" json:"unique_students"`
	UniqueBooks     int32  `db:"unique_books" json:"unique_books"`
	AvgLoanDuration string `db:"avg_loan_duration" json:"avg_loan_duration"`
}

func (q *Queries) GetSeasonalTrends(ctx context.Context, arg GetSeasonalTrendsParams) ([]GetSeasonalTrendsRow, error) {
	rows, err := q.db.Query(ctx, getSeasonalTrends, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSeasonalTrendsRow{}
	for rows.Next() {
		var i GetSeasonalTrendsRow
		if err := rows.Scan(
			&i.Season,
			&i.Year,
			&i.TotalBorrows,
			&i.TotalReturns,
			&i.UniqueStudents,
			&i.UniqueBooks,
			&i.AvgLoanDuration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentActivity = `-- name: GetStudentActivity :many
SELECT 
    s.student_id,
    CONCAT(s.first_name, ' ', s.last_name) as student_name,
    s.year_of_study,
    s.department,
    COUNT(CASE WHEN t.transaction_type = 'borrow' THEN 1 END)::int as total_borrows,
    COUNT(CASE WHEN t.transaction_type = 'return' THEN 1 END)::int as total_returns,
    COUNT(CASE WHEN t.transaction_type = 'borrow' AND t.returned_date IS NULL THEN 1 END)::int as current_books,
    COUNT(CASE WHEN t.due_date < NOW() AND t.returned_date IS NULL THEN 1 END)::int as overdue_books,
    COALESCE(SUM(t.fine_amount)::text, '0.00') as total_fines,
    COALESCE(MAX(t.transaction_date), s.created_at) as last_activity
FROM students s
LEFT JOIN transactions t ON s.id = t.student_id 
    AND t.transaction_date >= $3::timestamp
    AND t.transaction_date <= $4::timestamp
WHERE ($1::int IS NULL OR s.year_of_study = $1::int)
    AND ($2::text IS NULL OR s.department = $2::text)
    AND s.deleted_at IS NULL
    AND s.is_active = true
GROUP BY s.id, s.student_id, s.first_name, s.last_name, s.year_of_study, s.department, s.created_at
HAVING COUNT(CASE WHEN t.transaction_type = 'borrow' THEN 1 END) > 0  -- Only include students with activity
ORDER BY total_borrows DESC, last_activity DESC
`

type GetStudentActivityParams struct {
	Column1 int32            `db:"column_1" json:"column_1"`
	Column2 string           `db:"column_2" json:"column_2"`
	Column3 pgtype.Timestamp `db:"column_3" json:"column_3"`
	Column4 pgtype.Timestamp `db:"column_4" json:"column_4"`
}

type GetStudentActivityRow struct {
	StudentID    string           `db:"student_id" json:"student_id"`
	StudentName  interface{}      `db:"student_name" json:"student_name"`
	YearOfStudy  int32            `db:"year_of_study" json:"year_of_study"`
	Department   pgtype.Text      `db:"department" json:"department"`
	TotalBorrows int32            `db:"total_borrows" json:"total_borrows"`
	TotalReturns int32            `db:"total_returns" json:"total_returns"`
	CurrentBooks int32            `db:"current_books" json:"current_books"`
	OverdueBooks int32            `db:"overdue_books" json:"overdue_books"`
	TotalFines   interface{}      `db:"total_fines" json:"total_fines"`
	LastActivity pgtype.Timestamp `db:"last_activity" json:"last_activity"`
}

func (q *Queries) GetStudentActivity(ctx context.Context, arg GetStudentActivityParams) ([]GetStudentActivityRow, error) {
	rows, err := q.db.Query(ctx, getStudentActivity,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentActivityRow{}
	for rows.Next() {
		var i GetStudentActivityRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentName,
			&i.YearOfStudy,
			&i.Department,
			&i.TotalBorrows,
			&i.TotalReturns,
			&i.CurrentBooks,
			&i.OverdueBooks,
			&i.TotalFines,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentBehaviorAnalysis = `-- name: GetStudentBehaviorAnalysis :many
SELECT 
    s.year_of_study,
    s.department,
    COUNT(DISTINCT s.id)::int as total_students,
    ROUND(AVG(student_stats.total_borrows), 2)::text as avg_borrows_per_student,
    ROUND(AVG(student_stats.avg_loan_duration), 2)::text as avg_loan_duration_days,
    ROUND(AVG(student_stats.overdue_rate) * 100, 2)::text as avg_overdue_rate_percent,
    COUNT(CASE WHEN student_stats.total_borrows > 10 THEN 1 END)::int as heavy_users,
    COUNT(CASE WHEN student_stats.total_borrows <= 3 THEN 1 END)::int as light_users,
    STRING_AGG(DISTINCT student_stats.favorite_genre, ', ') as popular_genres
FROM students s
INNER JOIN (
    SELECT 
        s.id,
        s.year_of_study,
        s.department,
        COUNT(CASE WHEN t.transaction_type = 'borrow' THEN 1 END)::int as total_borrows,
        COALESCE(AVG(EXTRACT(DAY FROM (t.returned_date - t.transaction_date))), 14) as avg_loan_duration,
        CASE 
            WHEN COUNT(CASE WHEN t.transaction_type = 'borrow' THEN 1 END) > 0 THEN
                COUNT(CASE WHEN t.due_date < COALESCE(t.returned_date, NOW()) THEN 1 END)::numeric / 
                COUNT(CASE WHEN t.transaction_type = 'borrow' THEN 1 END)::numeric
            ELSE 0
        END as overdue_rate,
        (
            SELECT b.genre 
            FROM transactions t2 
            INNER JOIN books b ON t2.book_id = b.id 
            WHERE t2.student_id = s.id 
            AND t2.transaction_type = 'borrow'
            AND t2.transaction_date >= $1::timestamp
            AND t2.transaction_date <= $2::timestamp
            AND b.genre IS NOT NULL
            GROUP BY b.genre 
            ORDER BY COUNT(*) DESC 
            LIMIT 1
        ) as favorite_genre
    FROM students s
    LEFT JOIN transactions t ON s.id = t.student_id
        AND t.transaction_date >= $1::timestamp
        AND t.transaction_date <= $2::timestamp
    WHERE s.deleted_at IS NULL
    AND s.is_active = true
    AND ($3::int IS NULL OR s.year_of_study = $3::int)
    AND ($4::text IS NULL OR s.department = $4::text)
    GROUP BY s.id, s.year_of_study, s.department
) student_stats ON s.id = student_stats.id
GROUP BY s.year_of_study, s.department
ORDER BY s.year_of_study, s.department
`

type GetStudentBehaviorAnalysisParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
	Column3 int32            `db:"column_3" json:"column_3"`
	Column4 string           `db:"column_4" json:"column_4"`
}

type GetStudentBehaviorAnalysisRow struct {
	YearOfStudy           int32       `db:"year_of_study" json:"year_of_study"`
	Department            pgtype.Text `db:"department" json:"department"`
	TotalStudents         int32       `db:"total_students" json:"total_students"`
	AvgBorrowsPerStudent  string      `db:"avg_borrows_per_student" json:"avg_borrows_per_student"`
	AvgLoanDurationDays   string      `db:"avg_loan_duration_days" json:"avg_loan_duration_days"`
	AvgOverdueRatePercent string      `db:"avg_overdue_rate_percent" json:"avg_overdue_rate_percent"`
	HeavyUsers            int32       `db:"heavy_users" json:"heavy_users"`
	LightUsers            int32       `db:"light_users" json:"light_users"`
	PopularGenres         []byte      `db:"popular_genres" json:"popular_genres"`
}

func (q *Queries) GetStudentBehaviorAnalysis(ctx context.Context, arg GetStudentBehaviorAnalysisParams) ([]GetStudentBehaviorAnalysisRow, error) {
	rows, err := q.db.Query(ctx, getStudentBehaviorAnalysis,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentBehaviorAnalysisRow{}
	for rows.Next() {
		var i GetStudentBehaviorAnalysisRow
		if err := rows.Scan(
			&i.YearOfStudy,
			&i.Department,
			&i.TotalStudents,
			&i.AvgBorrowsPerStudent,
			&i.AvgLoanDurationDays,
			&i.AvgOverdueRatePercent,
			&i.HeavyUsers,
			&i.LightUsers,
			&i.PopularGenres,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentMonthlyActivity = `-- name: GetStudentMonthlyActivity :many
SELECT
    TO_CHAR(DATE_TRUNC('month', t.transaction_date), 'YYYY-MM') as month,
    COUNT(CASE WHEN t.transaction_type = 'borrow' THEN 1 END)::int as borrowed,
    COUNT(CASE WHEN t.returned_date IS NOT NULL THEN 1 END)::int as returned,
    COALESCE(SUM(t.fine_amount), 0)::text as fines_incurred
FROM transactions t
WHERE t.student_id = $1
    AND t.transaction_date >= $2::timestamp
    AND t.transaction_date <= $3::timestamp
GROUP BY DATE_TRUNC('month', t.transaction_date)
ORDER BY month
`

type GetStudentMonthlyActivityParams struct {
	StudentID int32            `db:"student_id" json:"student_id"`
	Column2   pgtype.Timestamp `db:"column_2" json:"column_2"`
	Column3   pgtype.Timestamp `db:"column_3" json:"column_3"`
}

type GetStudentMonthlyActivityRow struct {
	Month         string `db:"month" json:"month"`
	Borrowed      int32  `db:"borrowed" json:"borrowed"`
	Returned      int32  `db:"returned" json:"returned"`
	FinesIncurred string `db:"fines_incurred" json:"fines_incurred"`
}

func (q *Queries) GetStudentMonthlyActivity(ctx context.Context, arg GetStudentMonthlyActivityParams) ([]GetStudentMonthlyActivityRow, error) {
	rows, err := q.db.Query(ctx, getStudentMonthlyActivity, arg.StudentID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentMonthlyActivityRow{}
	for rows.Next() {
		var i GetStudentMonthlyActivityRow
		if err := rows.Scan(
			&i.Month,
			&i.Borrowed,
			&i.Returned,
			&i.FinesIncurred,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentReadingStats = `-- name: GetStudentReadingStats :many
SELECT
    COALESCE(b.genre, 'Uncategorized') as genre,
    COUNT(t.id)::int as books_read,
    COALESCE(AVG(EXTRACT(DAY FROM (t.returned_date - t.transaction_date))), 0)::int as avg_days_held
FROM transactions t
INNER JOIN books b ON t.book_id = b.id
WHERE t.student_id = $1
    AND t.transaction_type = 'borrow'
    AND b.deleted_at IS NULL
GROUP BY b.genre
ORDER BY books_read DESC
`

type GetStudentReadingStatsRow struct {
	Genre       string `db:"genre" json:"genre"`
	BooksRead   int32  `db:"books_read" json:"books_read"`
	AvgDaysHeld int32  `db:"avg_days_held" json:"avg_days_held"`
}

func (q *Queries) GetStudentReadingStats(ctx context.Context, studentID int32) ([]GetStudentReadingStatsRow, error) {
	rows, err := q.db.Query(ctx, getStudentReadingStats, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentReadingStatsRow{}
	for rows.Next() {
		var i GetStudentReadingStatsRow
		if err := rows.Scan(&i.Genre, &i.BooksRead, &i.AvgDaysHeld); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentTransactionHistory = `-- name: GetStudentTransactionHistory :many
SELECT
    t.id as transaction_id,
    t.transaction_type,
    t.transaction_date,
    t.due_date,
    t.returned_date,
    t.fine_amount,
    t.fine_paid,
    t.renewal_count,
    b.book_id as book_code,
    b.title as book_title,
    b.author as book_author,
    b.genre,
    CASE
        WHEN t.returned_date IS NULL AND t.due_date < NOW() THEN 'overdue'
        WHEN t.returned_date IS NULL THEN 'borrowed'
        WHEN t.transaction_type = 'lost' THEN 'lost'
        ELSE 'returned'
    END as status,
    CASE
        WHEN t.returned_date IS NULL AND t.due_date < NOW() THEN
            EXTRACT(DAY FROM (NOW() - t.due_date))::int
        ELSE 0
    END as days_overdue
FROM transactions t
INNER JOIN books b ON t.book_id = b.id
WHERE t.student_id = $1
    AND b.deleted_at IS NULL
ORDER BY t.transaction_date DESC
LIMIT $2 OFFSET $3
`

type GetStudentTransactionHistoryParams struct {
	StudentID int32 `db:"student_id" json:"student_id"`
	Limit     int32 `db:"limit" json:"limit"`
	Offset    int32 `db:"offset" json:"offset"`
}

type GetStudentTransactionHistoryRow struct {
	TransactionID   int32            `db:"transaction_id" json:"transaction_id"`
	TransactionType string           `db:"transaction_type" json:"transaction_type"`
	TransactionDate pgtype.Timestamp `db:"transaction_date" json:"transaction_date"`
	DueDate         pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate    pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	FineAmount      pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid        pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	RenewalCount    pgtype.Int4      `db:"renewal_count" json:"renewal_count"`
	BookCode        string           `db:"book_code" json:"book_code"`
	BookTitle       string           `db:"book_title" json:"book_title"`
	BookAuthor      string           `db:"book_author" json:"book_author"`
	Genre           pgtype.Text      `db:"genre" json:"genre"`
	Status          string           `db:"status" json:"status"`
	DaysOverdue     int32            `db:"days_overdue" json:"days_overdue"`
}

func (q *Queries) GetStudentTransactionHistory(ctx context.Context, arg GetStudentTransactionHistoryParams) ([]GetStudentTransactionHistoryRow, error) {
	rows, err := q.db.Query(ctx, getStudentTransactionHistory, arg.StudentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentTransactionHistoryRow{}
	for rows.Next() {
		var i GetStudentTransactionHistoryRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.TransactionType,
			&i.TransactionDate,
			&i.DueDate,
			&i.ReturnedDate,
			&i.FineAmount,
			&i.FinePaid,
			&i.RenewalCount,
			&i.BookCode,
			&i.BookTitle,
			&i.BookAuthor,
			&i.Genre,
			&i.Status,
			&i.DaysOverdue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopBorrowingStudents = `-- name: GetTopBorrowingStudents :many
SELECT 
    s.student_id,
    CONCAT(s.first_name, ' ', s.last_name) as student_name,
    s.year_of_study,
    s.department,
    COUNT(t.id)::int as total_borrows,
    COUNT(CASE WHEN t.returned_date IS NULL THEN 1 END)::int as current_books,
    COUNT(CASE WHEN t.due_date < NOW() AND t.returned_date IS NULL THEN 1 END)::int as overdue_books
FROM students s
INNER JOIN transactions t ON s.id = t.student_id
WHERE t.transaction_type = 'borrow'
    AND t.transaction_date >= $1::timestamp
    AND t.transaction_date <= $2::timestamp
    AND s.deleted_at IS NULL
    AND ($3::int IS NULL OR s.year_of_study = $3::int)
GROUP BY s.id, s.student_id, s.first_name, s.last_name, s.year_of_study, s.department
ORDER BY total_borrows DESC
LIMIT $4::int
`

type GetTopBorrowingStudentsParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
	Column3 int32            `db:"column_3" json:"column_3"`
	Column4 int32            `db:"column_4" json:"column_4"`
}

type GetTopBorrowingStudentsRow struct {
	StudentID    string      `db:"student_id" json:"student_id"`
	StudentName  interface{} `db:"student_name" json:"student_name"`
	YearOfStudy  int32       `db:"year_of_study" json:"year_of_study"`
	Department   pgtype.Text `db:"department" json:"department"`
	TotalBorrows int32       `db:"total_borrows" json:"total_borrows"`
	CurrentBooks int32       `db:"current_books" json:"current_books"`
	OverdueBooks int32       `db:"overdue_books" json:"overdue_books"`
}

func (q *Queries) GetTopBorrowingStudents(ctx context.Context, arg GetTopBorrowingStudentsParams) ([]GetTopBorrowingStudentsRow, error) {
	rows, err := q.db.Query(ctx, getTopBorrowingStudents,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopBorrowingStudentsRow{}
	for rows.Next() {
		var i GetTopBorrowingStudentsRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentName,
			&i.YearOfStudy,
			&i.Department,
			&i.TotalBorrows,
			&i.CurrentBooks,
			&i.OverdueBooks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopFineDefaulters = `-- name: GetTopFineDefaulters :many
SELECT
    s.id as student_id,
    s.student_id as student_code,
    CONCAT(s.first_name, ' ', s.last_name) as student_name,
    s.year_of_study,
    s.department,
    s.email,
    COUNT(t.id)::int as fine_count,
    COALESCE(SUM(t.fine_amount), 0)::text as total_fines,
    COALESCE(SUM(CASE WHEN t.fine_paid = false THEN t.fine_amount ELSE 0 END), 0)::text as outstanding_fines
FROM students s
INNER JOIN transactions t ON s.id = t.student_id
WHERE t.fine_amount > 0
    AND t.fine_paid = false
    AND COALESCE(t.fine_waived, false) = false
    AND s.deleted_at IS NULL
GROUP BY s.id, s.student_id, s.first_name, s.last_name, s.year_of_study, s.department, s.email
ORDER BY outstanding_fines DESC
LIMIT $1
`

type GetTopFineDefaultersRow struct {
	StudentID        int32       `db:"student_id" json:"student_id"`
	StudentCode      string      `db:"student_code" json:"student_code"`
	StudentName      interface{} `db:"student_name" json:"student_name"`
	YearOfStudy      int32       `db:"year_of_study" json:"year_of_study"`
	Department       pgtype.Text `db:"department" json:"department"`
	Email            pgtype.Text `db:"email" json:"email"`
	FineCount        int32       `db:"fine_count" json:"fine_count"`
	TotalFines       string      `db:"total_fines" json:"total_fines"`
	OutstandingFines string      `db:"outstanding_fines" json:"outstanding_fines"`
}

func (q *Queries) GetTopFineDefaulters(ctx context.Context, limit int32) ([]GetTopFineDefaultersRow, error) {
	rows, err := q.db.Query(ctx, getTopFineDefaulters, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopFineDefaultersRow{}
	for rows.Next() {
		var i GetTopFineDefaultersRow
		if err := rows.Scan(
			&i.StudentID,
			&i.StudentCode,
			&i.StudentName,
			&i.YearOfStudy,
			&i.Department,
			&i.Email,
			&i.FineCount,
			&i.TotalFines,
			&i.OutstandingFines,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsagePatternAnalysis = `-- name: GetUsagePatternAnalysis :many

SELECT 
    EXTRACT(DOW FROM t.transaction_date)::int as day_of_week,  -- 0=Sunday, 6=Saturday
    EXTRACT(HOUR FROM t.transaction_date)::int as hour_of_day,
    COUNT(CASE WHEN t.transaction_type = 'borrow' THEN 1 END)::int as borrow_count,
    COUNT(CASE WHEN t.transaction_type = 'return' THEN 1 END)::int as return_count,
    COUNT(DISTINCT t.student_id)::int as unique_users,
    ROUND(AVG(EXTRACT(EPOCH FROM (t.returned_date - t.transaction_date)) / 86400), 2)::text as avg_loan_duration_days
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
WHERE t.transaction_date >= $1::timestamp
    AND t.transaction_date <= $2::timestamp
    AND s.deleted_at IS NULL
    AND ($3::int IS NULL OR s.year_of_study = $3::int)
GROUP BY EXTRACT(DOW FROM t.transaction_date), EXTRACT(HOUR FROM t.transaction_date)
ORDER BY day_of_week, hour_of_day
`

type GetUsagePatternAnalysisParams struct {
	Column1 pgtype.Timestamp `db:"column_1" json:"column_1"`
	Column2 pgtype.Timestamp `db:"column_2" json:"column_2"`
	Column3 int32            `db:"column_3" json:"column_3"`
}

type GetUsagePatternAnalysisRow struct {
	DayOfWeek           int32  `db:"day_of_week" json:"day_of_week"`
	HourOfDay           int32  `db:"hour_of_day" json:"hour_of_day"`
	BorrowCount         int32  `db:"borrow_count" json:"borrow_count"`
	ReturnCount         int32  `db:"return_count" json:"return_count"`
	UniqueUsers         int32  `db:"unique_users" json:"unique_users"`
	AvgLoanDurationDays string `db:"avg_loan_duration_days" json:"avg_loan_duration_days"`
}

// Phase 8.3 - Advanced Analytics Queries
func (q *Queries) GetUsagePatternAnalysis(ctx context.Context, arg GetUsagePatternAnalysisParams) ([]GetUsagePatternAnalysisRow, error) {
	rows, err := q.db.Query(ctx, getUsagePatternAnalysis, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsagePatternAnalysisRow{}
	for rows.Next() {
		var i GetUsagePatternAnalysisRow
		if err := rows.Scan(
			&i.DayOfWeek,
			&i.HourOfDay,
			&i.BorrowCount,
			&i.ReturnCount,
			&i.UniqueUsers,
			&i.AvgLoanDurationDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYearBasedOverdueAnalysis = `-- name: GetYearBasedOverdueAnalysis :many
SELECT 
    EXTRACT(YEAR FROM t.due_date)::int as year,
    s.year_of_study,
    COUNT(*)::int as overdue_count,
    COALESCE(AVG(EXTRACT(DAY FROM (NOW() - t.due_date))), 0)::int as avg_days_overdue,
    COALESCE(SUM(t.fine_amount), 0)::text as total_fines,
    COUNT(DISTINCT s.id)::int as affected_students
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
WHERE t.due_date < NOW()
    AND t.returned_date IS NULL
    AND ($1::int IS NULL OR EXTRACT(YEAR FROM t.due_date) = $1::int)
    AND ($2::int IS NULL OR s.year_of_study = $2::int)
    AND s.deleted_at IS NULL
GROUP BY EXTRACT(YEAR FROM t.due_date), s.year_of_study
ORDER BY year, s.year_of_study
`

type GetYearBasedOverdueAnalysisParams struct {
	Year        pgtype.Int4 `db:"year" json:"year"`
	YearOfStudy pgtype.Int4 `db:"year_of_study" json:"year_of_study"`
}

type GetYearBasedOverdueAnalysisRow struct {
	Year             int32  `db:"year" json:"year"`
	YearOfStudy      int32  `db:"year_of_study" json:"year_of_study"`
	OverdueCount     int32  `db:"overdue_count" json:"overdue_count"`
	AvgDaysOverdue   int32  `db:"avg_days_overdue" json:"avg_days_overdue"`
	TotalFines       string `db:"total_fines" json:"total_fines"`
	AffectedStudents int32  `db:"affected_students" json:"affected_students"`
}

func (q *Queries) GetYearBasedOverdueAnalysis(ctx context.Context, arg GetYearBasedOverdueAnalysisParams) ([]GetYearBasedOverdueAnalysisRow, error) {
	rows, err := q.db.Query(ctx, getYearBasedOverdueAnalysis, arg.Year, arg.YearOfStudy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetYearBasedOverdueAnalysisRow{}
	for rows.Next() {
		var i GetYearBasedOverdueAnalysisRow
		if err := rows.Scan(
			&i.Year,
			&i.YearOfStudy,
			&i.OverdueCount,
			&i.AvgDaysOverdue,
			&i.TotalFines,
			&i.AffectedStudents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYearEndSummary = `-- name: GetYearEndSummary :one
SELECT 
    EXTRACT(YEAR FROM NOW())::int as year,
    (SELECT COUNT(*) FROM students WHERE deleted_at IS NULL AND is_active = true)::int as total_students,
    (SELECT COUNT(*) FROM books WHERE deleted_at IS NULL AND is_active = true)::int as total_books,
    (SELECT COUNT(*) FROM transactions WHERE EXTRACT(YEAR FROM transaction_date) = EXTRACT(YEAR FROM NOW()) AND transaction_type = 'borrow')::int as yearly_borrows,
    (SELECT COUNT(*) FROM transactions WHERE EXTRACT(YEAR FROM transaction_date) = EXTRACT(YEAR FROM NOW()) AND transaction_type = 'return')::int as yearly_returns,
    (SELECT COUNT(*) FROM transactions WHERE due_date < NOW() AND returned_date IS NULL)::int as current_overdue,
    (SELECT COUNT(DISTINCT student_id) FROM transactions WHERE EXTRACT(YEAR FROM transaction_date) = EXTRACT(YEAR FROM NOW()))::int as active_students_this_year,
    (SELECT COALESCE(SUM(fine_amount), 0)::text FROM transactions WHERE EXTRACT(YEAR FROM transaction_date) = EXTRACT(YEAR FROM NOW()))::text as total_fines_generated,
    (SELECT COUNT(*) FROM reservations WHERE EXTRACT(YEAR FROM reserved_at) = EXTRACT(YEAR FROM NOW()))::int as yearly_reservations,
    (SELECT COALESCE(AVG(EXTRACT(DAY FROM (returned_date - transaction_date))), 0)::int FROM transactions WHERE EXTRACT(YEAR FROM transaction_date) = EXTRACT(YEAR FROM NOW()) AND returned_date IS NOT NULL)::int as avg_loan_duration_days
`

type GetYearEndSummaryRow struct {
	Year                   int32  `db:"year" json:"year"`
	TotalStudents          int32  `db:"total_students" json:"total_students"`
	TotalBooks             int32  `db:"total_books" json:"total_books"`
	YearlyBorrows          int32  `db:"yearly_borrows" json:"yearly_borrows"`
	YearlyReturns          int32  `db:"yearly_returns" json:"yearly_returns"`
	CurrentOverdue         int32  `db:"current_overdue" json:"current_overdue"`
	ActiveStudentsThisYear int32  `db:"active_students_this_year" json:"active_students_this_year"`
	TotalFinesGenerated    string `db:"total_fines_generated" json:"total_fines_generated"`
	YearlyReservations     int32  `db:"yearly_reservations" json:"yearly_reservations"`
	AvgLoanDurationDays    int32  `db:"avg_loan_duration_days" json:"avg_loan_duration_days"`
}

func (q *Queries) GetYearEndSummary(ctx context.Context) (GetYearEndSummaryRow, error) {
	row := q.db.QueryRow(ctx, getYearEndSummary)
	var i GetYearEndSummaryRow
	err := row.Scan(
		&i.Year,
		&i.TotalStudents,
		&i.TotalBooks,
		&i.YearlyBorrows,
		&i.YearlyReturns,
		&i.CurrentOverdue,
		&i.ActiveStudentsThisYear,
		&i.TotalFinesGenerated,
		&i.YearlyReservations,
		&i.AvgLoanDurationDays,
	)
	return i, err
}

const getYearOverYearComparison = `-- name: GetYearOverYearComparison :many
SELECT 
    current_year.year,
    current_year.total_borrows,
    current_year.total_returns,
    current_year.total_students,
    COALESCE(previous_year.total_borrows, 0)::int as previous_year_borrows,
    COALESCE(previous_year.total_students, 0)::int as previous_year_students,
    CASE 
        WHEN COALESCE(previous_year.total_borrows, 0) > 0 THEN 
            ROUND((((current_year.total_borrows - COALESCE(previous_year.total_borrows, 0))::numeric / COALESCE(previous_year.total_borrows, 1)::numeric) * 100), 2)::text
        ELSE '0.00'
    END as borrow_growth_rate,
    CASE 
        WHEN COALESCE(previous_year.total_students, 0) > 0 THEN 
            ROUND((((current_year.total_students - COALESCE(previous_year.total_students, 0))::numeric / COALESCE(previous_year.total_students, 1)::numeric) * 100), 2)::text
        ELSE '0.00'
    END as student_growth_rate
FROM (
    SELECT 
        EXTRACT(YEAR FROM t.transaction_date)::int as year,
        COUNT(CASE WHEN t.transaction_type = 'borrow' THEN 1 END)::int as total_borrows,
        COUNT(CASE WHEN t.transaction_type = 'return' THEN 1 END)::int as total_returns,
        COUNT(DISTINCT s.id)::int as total_students
    FROM transactions t
    INNER JOIN students s ON t.student_id = s.id
    WHERE EXTRACT(YEAR FROM t.transaction_date) = ANY($1::int[])
        AND s.deleted_at IS NULL
    GROUP BY EXTRACT(YEAR FROM t.transaction_date)
) current_year
LEFT JOIN (
    SELECT 
        EXTRACT(YEAR FROM t.transaction_date)::int as year,
        COUNT(CASE WHEN t.transaction_type = 'borrow' THEN 1 END)::int as total_borrows,
        COUNT(CASE WHEN t.transaction_type = 'return' THEN 1 END)::int as total_returns,
        COUNT(DISTINCT s.id)::int as total_students
    FROM transactions t
    INNER JOIN students s ON t.student_id = s.id
    WHERE s.deleted_at IS NULL
    GROUP BY EXTRACT(YEAR FROM t.transaction_date)
) previous_year ON current_year.year = previous_year.year + 1
ORDER BY current_year.year
`

type GetYearOverYearComparisonRow struct {
	Year                 int32  `db:"year" json:"year"`
	TotalBorrows         int32  `db:"total_borrows" json:"total_borrows"`
	TotalReturns         int32  `db:"total_returns" json:"total_returns"`
	TotalStudents        int32  `db:"total_students" json:"total_students"`
	PreviousYearBorrows  int32  `db:"previous_year_borrows" json:"previous_year_borrows"`
	PreviousYearStudents int32  `db:"previous_year_students" json:"previous_year_students"`
	BorrowGrowthRate     string `db:"borrow_growth_rate" json:"borrow_growth_rate"`
	StudentGrowthRate    string `db:"student_growth_rate" json:"student_growth_rate"`
}

func (q *Queries) GetYearOverYearComparison(ctx context.Context, dollar_1 []int32) ([]GetYearOverYearComparisonRow, error) {
	rows, err := q.db.Query(ctx, getYearOverYearComparison, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetYearOverYearComparisonRow{}
	for rows.Next() {
		var i GetYearOverYearComparisonRow
		if err := rows.Scan(
			&i.Year,
			&i.TotalBorrows,
			&i.TotalReturns,
			&i.TotalStudents,
			&i.PreviousYearBorrows,
			&i.PreviousYearStudents,
			&i.BorrowGrowthRate,
			&i.StudentGrowthRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYearSpecificBorrowingReport = `-- name: GetYearSpecificBorrowingReport :many
SELECT 
    TO_CHAR(DATE_TRUNC('month', t.transaction_date), 'YYYY-MM') as month,
    s.year_of_study,
    COUNT(CASE WHEN t.transaction_type = 'borrow' THEN 1 END)::int as total_borrows,
    COUNT(CASE WHEN t.transaction_type = 'return' THEN 1 END)::int as total_returns,
    COUNT(CASE WHEN t.due_date < NOW() AND t.returned_date IS NULL THEN 1 END)::int as total_overdue,
    COUNT(DISTINCT t.student_id)::int as unique_students,
    COALESCE(AVG(EXTRACT(DAY FROM (t.returned_date - t.transaction_date))), 0)::int as avg_loan_duration
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
WHERE EXTRACT(YEAR FROM t.transaction_date) = $1::int
    AND s.deleted_at IS NULL
GROUP BY DATE_TRUNC('month', t.transaction_date), s.year_of_study
ORDER BY month, s.year_of_study
`

type GetYearSpecificBorrowingReportRow struct {
	Month           string `db:"month" json:"month"`
	YearOfStudy     int32  `db:"year_of_study" json:"year_of_study"`
	TotalBorrows    int32  `db:"total_borrows" json:"total_borrows"`
	TotalReturns    int32  `db:"total_returns" json:"total_returns"`
	TotalOverdue    int32  `db:"total_overdue" json:"total_overdue"`
	UniqueStudents  int32  `db:"unique_students" json:"unique_students"`
	AvgLoanDuration int32  `db:"avg_loan_duration" json:"avg_loan_duration"`
}

func (q *Queries) GetYearSpecificBorrowingReport(ctx context.Context, dollar_1 int32) ([]GetYearSpecificBorrowingReportRow, error) {
	rows, err := q.db.Query(ctx, getYearSpecificBorrowingReport, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetYearSpecificBorrowingReportRow{}
	for rows.Next() {
		var i GetYearSpecificBorrowingReportRow
		if err := rows.Scan(
			&i.Month,
			&i.YearOfStudy,
			&i.TotalBorrows,
			&i.TotalReturns,
			&i.TotalOverdue,
			&i.UniqueStudents,
			&i.AvgLoanDuration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYearlyStatistics = `-- name: GetYearlyStatistics :many
SELECT 
    EXTRACT(YEAR FROM t.transaction_date)::int as year,
    COUNT(CASE WHEN t.transaction_type = 'borrow' THEN 1 END)::int as total_borrows,
    COUNT(CASE WHEN t.transaction_type = 'return' THEN 1 END)::int as total_returns,
    COUNT(CASE WHEN t.due_date < NOW() AND t.returned_date IS NULL THEN 1 END)::int as total_overdue,
    COUNT(DISTINCT s.id)::int as total_students,
    (SELECT COUNT(*) FROM books WHERE deleted_at IS NULL)::int as total_books,
    CASE 
        WHEN COUNT(DISTINCT s.id) > 0 THEN 
            ROUND(COUNT(CASE WHEN t.transaction_type = 'borrow' THEN 1 END)::numeric / COUNT(DISTINCT s.id)::numeric, 2)::text
        ELSE '0.00'
    END as avg_borrows_per_student
FROM transactions t
INNER JOIN students s ON t.student_id = s.id
WHERE EXTRACT(YEAR FROM t.transaction_date) = ANY($1::int[])
    AND s.deleted_at IS NULL
GROUP BY EXTRACT(YEAR FROM t.transaction_date)
ORDER BY year
`

type GetYearlyStatisticsRow struct {
	Year                 int32  `db:"year" json:"year"`
	TotalBorrows         int32  `db:"total_borrows" json:"total_borrows"`
	TotalReturns         int32  `db:"total_returns" json:"total_returns"`
	TotalOverdue         int32  `db:"total_overdue" json:"total_overdue"`
	TotalStudents        int32  `db:"total_students" json:"total_students"`
	TotalBooks           int32  `db:"total_books" json:"total_books"`
	AvgBorrowsPerStudent string `db:"avg_borrows_per_student" json:"avg_borrows_per_student"`
}

func (q *Queries) GetYearlyStatistics(ctx context.Context, dollar_1 []int32) ([]GetYearlyStatisticsRow, error) {
	rows, err := q.db.Query(ctx, getYearlyStatistics, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetYearlyStatisticsRow{}
	for rows.Next() {
		var i GetYearlyStatisticsRow
		if err := rows.Scan(
			&i.Year,
			&i.TotalBorrows,
			&i.TotalReturns,
			&i.TotalOverdue,
			&i.TotalStudents,
			&i.TotalBooks,
			&i.AvgBorrowsPerStudent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
