// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelRenewal = `-- name: CancelRenewal :one
UPDATE transactions
SET
    due_date = $1::timestamp,
    renewal_count = GREATEST(COALESCE(renewal_count, 0) - 1, 0),
    notes = CASE
        WHEN notes IS NULL OR notes = '' THEN '[RENEWAL CANCELLED] Due date adjusted'
        ELSE notes || E'\n\n[RENEWAL CANCELLED] Due date adjusted at ' || NOW()::text
    END,
    updated_at = NOW()
WHERE id = $2
  AND returned_date IS NULL
  AND COALESCE(renewal_count, 0) > 0
RETURNING id, student_id, book_id, transaction_type, transaction_date, due_date, returned_date, librarian_id, fine_amount, fine_paid, notes, created_at, updated_at, return_condition, condition_notes, fine_waived, fine_waived_at, fine_waived_by, fine_waived_reason, fine_paid_at, copy_id, status, renewal_count, last_renewed_at, last_renewed_by
`

type CancelRenewalParams struct {
	NewDueDate pgtype.Timestamp `db:"new_due_date" json:"new_due_date"`
	ID         int32            `db:"id" json:"id"`
}

// Cancel the last renewal by decrementing the renewal count and setting a new due date
func (q *Queries) CancelRenewal(ctx context.Context, arg CancelRenewalParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, cancelRenewal, arg.NewDueDate, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.DueDate,
		&i.ReturnedDate,
		&i.LibrarianID,
		&i.FineAmount,
		&i.FinePaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReturnCondition,
		&i.ConditionNotes,
		&i.FineWaived,
		&i.FineWaivedAt,
		&i.FineWaivedBy,
		&i.FineWaivedReason,
		&i.FinePaidAt,
		&i.CopyID,
		&i.Status,
		&i.RenewalCount,
		&i.LastRenewedAt,
		&i.LastRenewedBy,
	)
	return i, err
}

const cancelTransaction = `-- name: CancelTransaction :one
UPDATE transactions
SET
    returned_date = NOW(),
    fine_amount = 0,
    fine_paid = true,
    status = 'cancelled',
    notes = CASE
        WHEN notes IS NULL OR notes = '' THEN '[CANCELLED] ' || $1::text
        ELSE notes || E'\n\n[CANCELLED] ' || $1::text
    END,
    updated_at = NOW()
WHERE id = $2
  AND returned_date IS NULL
  AND transaction_type = 'borrow'
RETURNING id, student_id, book_id, transaction_type, transaction_date, due_date, returned_date, librarian_id, fine_amount, fine_paid, notes, created_at, updated_at, return_condition, condition_notes, fine_waived, fine_waived_at, fine_waived_by, fine_waived_reason, fine_paid_at, copy_id, status, renewal_count, last_renewed_at, last_renewed_by
`

type CancelTransactionParams struct {
	CancelReason string `db:"cancel_reason" json:"cancel_reason"`
	ID           int32  `db:"id" json:"id"`
}

// Cancel a transaction by marking it as returned with zero fine
// The notes field documents the cancellation reason
func (q *Queries) CancelTransaction(ctx context.Context, arg CancelTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, cancelTransaction, arg.CancelReason, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.DueDate,
		&i.ReturnedDate,
		&i.LibrarianID,
		&i.FineAmount,
		&i.FinePaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReturnCondition,
		&i.ConditionNotes,
		&i.FineWaived,
		&i.FineWaivedAt,
		&i.FineWaivedBy,
		&i.FineWaivedReason,
		&i.FinePaidAt,
		&i.CopyID,
		&i.Status,
		&i.RenewalCount,
		&i.LastRenewedAt,
		&i.LastRenewedBy,
	)
	return i, err
}

const countActiveBorrowingsByStudent = `-- name: CountActiveBorrowingsByStudent :one
SELECT COUNT(*) FROM transactions
WHERE student_id = $1 AND returned_date IS NULL AND transaction_type = 'borrow'
`

func (q *Queries) CountActiveBorrowingsByStudent(ctx context.Context, studentID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveBorrowingsByStudent, studentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveTransactionsByBook = `-- name: CountActiveTransactionsByBook :one
SELECT COUNT(*) FROM transactions
WHERE book_id = $1 AND returned_date IS NULL
`

func (q *Queries) CountActiveTransactionsByBook(ctx context.Context, bookID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTransactionsByBook, bookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOverdueTransactions = `-- name: CountOverdueTransactions :one
SELECT COUNT(*) FROM transactions
WHERE due_date < NOW() AND returned_date IS NULL AND transaction_type = 'borrow'
`

func (q *Queries) CountOverdueTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOverdueTransactions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOverdueTransactionsFiltered = `-- name: CountOverdueTransactionsFiltered :one
SELECT COUNT(*) FROM transactions t
JOIN students s ON t.student_id = s.id
JOIN books b ON t.book_id = b.id
WHERE t.due_date < NOW() AND t.returned_date IS NULL AND t.transaction_type = 'borrow'
  AND s.deleted_at IS NULL
  AND s.is_active = true
  AND b.deleted_at IS NULL
`

func (q *Queries) CountOverdueTransactionsFiltered(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOverdueTransactionsFiltered)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRenewalsByStudentAndBook = `-- name: CountRenewalsByStudentAndBook :one

SELECT COUNT(*) FROM transactions
WHERE student_id = $1 AND book_id = $2 AND transaction_type = 'renew'
`

type CountRenewalsByStudentAndBookParams struct {
	StudentID int32 `db:"student_id" json:"student_id"`
	BookID    int32 `db:"book_id" json:"book_id"`
}

// Renewal-related queries for Phase 6.7
func (q *Queries) CountRenewalsByStudentAndBook(ctx context.Context, arg CountRenewalsByStudentAndBookParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRenewalsByStudentAndBook, arg.StudentID, arg.BookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchTransactions = `-- name: CountSearchTransactions :one
SELECT COUNT(*)
FROM transactions t
JOIN students s ON t.student_id = s.id
JOIN books b ON t.book_id = b.id
LEFT JOIN book_copies bc ON t.copy_id = bc.id
WHERE
    ($1::text IS NULL OR $1 = '' OR
     b.title ILIKE '%' || $1 || '%' OR
     b.author ILIKE '%' || $1 || '%' OR
     s.first_name ILIKE '%' || $1 || '%' OR
     s.last_name ILIKE '%' || $1 || '%' OR
     s.student_id ILIKE '%' || $1 || '%' OR
     bc.barcode ILIKE '%' || $1 || '%')
    AND ($2::int IS NULL OR t.student_id = $2)
    AND ($3::int IS NULL OR t.book_id = $3)
    AND ($4::text IS NULL OR $4 = '' OR t.transaction_type = $4)
    AND ($5::timestamp IS NULL OR t.transaction_date >= $5)
    AND ($6::timestamp IS NULL OR t.transaction_date <= $6)
`

type CountSearchTransactionsParams struct {
	Query           pgtype.Text      `db:"query" json:"query"`
	FilterStudentID pgtype.Int4      `db:"filter_student_id" json:"filter_student_id"`
	FilterBookID    pgtype.Int4      `db:"filter_book_id" json:"filter_book_id"`
	FilterType      pgtype.Text      `db:"filter_type" json:"filter_type"`
	FromDate        pgtype.Timestamp `db:"from_date" json:"from_date"`
	ToDate          pgtype.Timestamp `db:"to_date" json:"to_date"`
}

func (q *Queries) CountSearchTransactions(ctx context.Context, arg CountSearchTransactionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchTransactions,
		arg.Query,
		arg.FilterStudentID,
		arg.FilterBookID,
		arg.FilterType,
		arg.FromDate,
		arg.ToDate,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTodayBorrowings = `-- name: CountTodayBorrowings :one
SELECT COUNT(*) FROM transactions
WHERE transaction_type = 'borrow' AND DATE(transaction_date) = CURRENT_DATE
`

func (q *Queries) CountTodayBorrowings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTodayBorrowings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*) FROM transactions
`

func (q *Queries) CountTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (student_id, book_id, transaction_type, due_date, librarian_id, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, student_id, book_id, transaction_type, transaction_date, due_date, returned_date, librarian_id, fine_amount, fine_paid, notes, created_at, updated_at, return_condition, condition_notes, fine_waived, fine_waived_at, fine_waived_by, fine_waived_reason, fine_paid_at, copy_id, status, renewal_count, last_renewed_at, last_renewed_by
`

type CreateTransactionParams struct {
	StudentID       int32            `db:"student_id" json:"student_id"`
	BookID          int32            `db:"book_id" json:"book_id"`
	TransactionType string           `db:"transaction_type" json:"transaction_type"`
	DueDate         pgtype.Timestamp `db:"due_date" json:"due_date"`
	LibrarianID     pgtype.Int4      `db:"librarian_id" json:"librarian_id"`
	Notes           pgtype.Text      `db:"notes" json:"notes"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.StudentID,
		arg.BookID,
		arg.TransactionType,
		arg.DueDate,
		arg.LibrarianID,
		arg.Notes,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.DueDate,
		&i.ReturnedDate,
		&i.LibrarianID,
		&i.FineAmount,
		&i.FinePaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReturnCondition,
		&i.ConditionNotes,
		&i.FineWaived,
		&i.FineWaivedAt,
		&i.FineWaivedBy,
		&i.FineWaivedReason,
		&i.FinePaidAt,
		&i.CopyID,
		&i.Status,
		&i.RenewalCount,
		&i.LastRenewedAt,
		&i.LastRenewedBy,
	)
	return i, err
}

const createTransactionWithCopy = `-- name: CreateTransactionWithCopy :one
INSERT INTO transactions (student_id, book_id, copy_id, transaction_type, due_date, librarian_id, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, student_id, book_id, transaction_type, transaction_date, due_date, returned_date, librarian_id, fine_amount, fine_paid, notes, created_at, updated_at, return_condition, condition_notes, fine_waived, fine_waived_at, fine_waived_by, fine_waived_reason, fine_paid_at, copy_id, status, renewal_count, last_renewed_at, last_renewed_by
`

type CreateTransactionWithCopyParams struct {
	StudentID       int32            `db:"student_id" json:"student_id"`
	BookID          int32            `db:"book_id" json:"book_id"`
	CopyID          pgtype.Int4      `db:"copy_id" json:"copy_id"`
	TransactionType string           `db:"transaction_type" json:"transaction_type"`
	DueDate         pgtype.Timestamp `db:"due_date" json:"due_date"`
	LibrarianID     pgtype.Int4      `db:"librarian_id" json:"librarian_id"`
	Notes           pgtype.Text      `db:"notes" json:"notes"`
}

func (q *Queries) CreateTransactionWithCopy(ctx context.Context, arg CreateTransactionWithCopyParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransactionWithCopy,
		arg.StudentID,
		arg.BookID,
		arg.CopyID,
		arg.TransactionType,
		arg.DueDate,
		arg.LibrarianID,
		arg.Notes,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.DueDate,
		&i.ReturnedDate,
		&i.LibrarianID,
		&i.FineAmount,
		&i.FinePaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReturnCondition,
		&i.ConditionNotes,
		&i.FineWaived,
		&i.FineWaivedAt,
		&i.FineWaivedBy,
		&i.FineWaivedReason,
		&i.FinePaidAt,
		&i.CopyID,
		&i.Status,
		&i.RenewalCount,
		&i.LastRenewedAt,
		&i.LastRenewedBy,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = $1
`

// Delete a transaction by ID (admin only)
func (q *Queries) DeleteTransaction(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

const getActiveTransactionByCopy = `-- name: GetActiveTransactionByCopy :one
SELECT t.id, t.student_id, t.book_id, t.transaction_type, t.transaction_date, t.due_date, t.returned_date, t.librarian_id, t.fine_amount, t.fine_paid, t.notes, t.created_at, t.updated_at, t.return_condition, t.condition_notes, t.fine_waived, t.fine_waived_at, t.fine_waived_by, t.fine_waived_reason, t.fine_paid_at, t.copy_id, t.status, t.renewal_count, t.last_renewed_at, t.last_renewed_by FROM transactions t
WHERE t.copy_id = $1 AND t.returned_date IS NULL
LIMIT 1
`

func (q *Queries) GetActiveTransactionByCopy(ctx context.Context, copyID pgtype.Int4) (Transaction, error) {
	row := q.db.QueryRow(ctx, getActiveTransactionByCopy, copyID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.DueDate,
		&i.ReturnedDate,
		&i.LibrarianID,
		&i.FineAmount,
		&i.FinePaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReturnCondition,
		&i.ConditionNotes,
		&i.FineWaived,
		&i.FineWaivedAt,
		&i.FineWaivedBy,
		&i.FineWaivedReason,
		&i.FinePaidAt,
		&i.CopyID,
		&i.Status,
		&i.RenewalCount,
		&i.LastRenewedAt,
		&i.LastRenewedBy,
	)
	return i, err
}

const getRenewalStatisticsByStudent = `-- name: GetRenewalStatisticsByStudent :one
SELECT 
    student_id,
    COUNT(*) as total_renewals,
    COUNT(DISTINCT book_id) as books_renewed
FROM transactions
WHERE student_id = $1 AND transaction_type = 'renew'
GROUP BY student_id
`

type GetRenewalStatisticsByStudentRow struct {
	StudentID     int32 `db:"student_id" json:"student_id"`
	TotalRenewals int64 `db:"total_renewals" json:"total_renewals"`
	BooksRenewed  int64 `db:"books_renewed" json:"books_renewed"`
}

func (q *Queries) GetRenewalStatisticsByStudent(ctx context.Context, studentID int32) (GetRenewalStatisticsByStudentRow, error) {
	row := q.db.QueryRow(ctx, getRenewalStatisticsByStudent, studentID)
	var i GetRenewalStatisticsByStudentRow
	err := row.Scan(&i.StudentID, &i.TotalRenewals, &i.BooksRenewed)
	return i, err
}

const getStudentBorrowingStats = `-- name: GetStudentBorrowingStats :many
SELECT student_id, COUNT(*) as current_books
FROM transactions
WHERE returned_date IS NULL
GROUP BY student_id
`

type GetStudentBorrowingStatsRow struct {
	StudentID    int32 `db:"student_id" json:"student_id"`
	CurrentBooks int64 `db:"current_books" json:"current_books"`
}

func (q *Queries) GetStudentBorrowingStats(ctx context.Context) ([]GetStudentBorrowingStatsRow, error) {
	rows, err := q.db.Query(ctx, getStudentBorrowingStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetStudentBorrowingStatsRow{}
	for rows.Next() {
		var i GetStudentBorrowingStatsRow
		if err := rows.Scan(&i.StudentID, &i.CurrentBooks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentFineStats = `-- name: GetStudentFineStats :one
SELECT
    COALESCE(SUM(fine_amount), 0)::numeric as total_fines,
    COALESCE(SUM(CASE WHEN fine_paid = false AND (COALESCE(fine_waived, false) = false) THEN fine_amount ELSE 0 END), 0)::numeric as unpaid_fines
FROM transactions
WHERE student_id = $1
`

type GetStudentFineStatsRow struct {
	TotalFines  pgtype.Numeric `db:"total_fines" json:"total_fines"`
	UnpaidFines pgtype.Numeric `db:"unpaid_fines" json:"unpaid_fines"`
}

func (q *Queries) GetStudentFineStats(ctx context.Context, studentID int32) (GetStudentFineStatsRow, error) {
	row := q.db.QueryRow(ctx, getStudentFineStats, studentID)
	var i GetStudentFineStatsRow
	err := row.Scan(&i.TotalFines, &i.UnpaidFines)
	return i, err
}

const getStudentTotalBorrowed = `-- name: GetStudentTotalBorrowed :one
SELECT COUNT(*) FROM transactions
WHERE student_id = $1 AND transaction_type = 'borrow'
`

func (q *Queries) GetStudentTotalBorrowed(ctx context.Context, studentID int32) (int64, error) {
	row := q.db.QueryRow(ctx, getStudentTotalBorrowed, studentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTransactionAge = `-- name: GetTransactionAge :one
SELECT EXTRACT(EPOCH FROM (NOW() - transaction_date)) / 60 as age_minutes
FROM transactions
WHERE id = $1
`

// Get transaction age in minutes (for cancel time window validation)
func (q *Queries) GetTransactionAge(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, getTransactionAge, id)
	var age_minutes int32
	err := row.Scan(&age_minutes)
	return age_minutes, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT t.id, t.student_id, t.book_id, t.transaction_type, t.transaction_date, t.due_date, t.returned_date, t.librarian_id, t.fine_amount, t.fine_paid, t.notes, t.created_at, t.updated_at, t.return_condition, t.condition_notes, t.fine_waived, t.fine_waived_at, t.fine_waived_by, t.fine_waived_reason, t.fine_paid_at, t.copy_id, t.status, t.renewal_count, t.last_renewed_at, t.last_renewed_by, s.first_name, s.last_name, s.student_id, b.title, b.author, b.book_id
FROM transactions t
JOIN students s ON t.student_id = s.id
JOIN books b ON t.book_id = b.id
WHERE t.id = $1
`

type GetTransactionByIDRow struct {
	ID               int32            `db:"id" json:"id"`
	StudentID        int32            `db:"student_id" json:"student_id"`
	BookID           int32            `db:"book_id" json:"book_id"`
	TransactionType  string           `db:"transaction_type" json:"transaction_type"`
	TransactionDate  pgtype.Timestamp `db:"transaction_date" json:"transaction_date"`
	DueDate          pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate     pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	LibrarianID      pgtype.Int4      `db:"librarian_id" json:"librarian_id"`
	FineAmount       pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid         pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	Notes            pgtype.Text      `db:"notes" json:"notes"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ReturnCondition  pgtype.Text      `db:"return_condition" json:"return_condition"`
	ConditionNotes   pgtype.Text      `db:"condition_notes" json:"condition_notes"`
	FineWaived       pgtype.Bool      `db:"fine_waived" json:"fine_waived"`
	FineWaivedAt     pgtype.Timestamp `db:"fine_waived_at" json:"fine_waived_at"`
	FineWaivedBy     pgtype.Int4      `db:"fine_waived_by" json:"fine_waived_by"`
	FineWaivedReason pgtype.Text      `db:"fine_waived_reason" json:"fine_waived_reason"`
	FinePaidAt       pgtype.Timestamp `db:"fine_paid_at" json:"fine_paid_at"`
	CopyID           pgtype.Int4      `db:"copy_id" json:"copy_id"`
	Status           pgtype.Text      `db:"status" json:"status"`
	RenewalCount     pgtype.Int4      `db:"renewal_count" json:"renewal_count"`
	LastRenewedAt    pgtype.Timestamp `db:"last_renewed_at" json:"last_renewed_at"`
	LastRenewedBy    pgtype.Int4      `db:"last_renewed_by" json:"last_renewed_by"`
	FirstName        string           `db:"first_name" json:"first_name"`
	LastName         string           `db:"last_name" json:"last_name"`
	StudentID_2      string           `db:"student_id_2" json:"student_id_2"`
	Title            string           `db:"title" json:"title"`
	Author           string           `db:"author" json:"author"`
	BookID_2         string           `db:"book_id_2" json:"book_id_2"`
}

func (q *Queries) GetTransactionByID(ctx context.Context, id int32) (GetTransactionByIDRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i GetTransactionByIDRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.DueDate,
		&i.ReturnedDate,
		&i.LibrarianID,
		&i.FineAmount,
		&i.FinePaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReturnCondition,
		&i.ConditionNotes,
		&i.FineWaived,
		&i.FineWaivedAt,
		&i.FineWaivedBy,
		&i.FineWaivedReason,
		&i.FinePaidAt,
		&i.CopyID,
		&i.Status,
		&i.RenewalCount,
		&i.LastRenewedAt,
		&i.LastRenewedBy,
		&i.FirstName,
		&i.LastName,
		&i.StudentID_2,
		&i.Title,
		&i.Author,
		&i.BookID_2,
	)
	return i, err
}

const getTransactionByIDWithCopy = `-- name: GetTransactionByIDWithCopy :one

SELECT t.id, t.student_id, t.book_id, t.transaction_type, t.transaction_date, t.due_date, t.returned_date, t.librarian_id, t.fine_amount, t.fine_paid, t.notes, t.created_at, t.updated_at, t.return_condition, t.condition_notes, t.fine_waived, t.fine_waived_at, t.fine_waived_by, t.fine_waived_reason, t.fine_paid_at, t.copy_id, t.status, t.renewal_count, t.last_renewed_at, t.last_renewed_by,
       s.first_name, s.last_name, s.student_id,
       b.title, b.author, b.book_id, b.cover_image_url,
       bc.barcode as copy_barcode, bc.condition as copy_condition,
       s.deleted_at as student_deleted_at,
       del_user.username as student_deleted_by_name
FROM transactions t
JOIN students s ON t.student_id = s.id
JOIN books b ON t.book_id = b.id
LEFT JOIN book_copies bc ON t.copy_id = bc.id
LEFT JOIN users del_user ON s.deleted_by = del_user.id
WHERE t.id = $1
`

type GetTransactionByIDWithCopyRow struct {
	ID                   int32            `db:"id" json:"id"`
	StudentID            int32            `db:"student_id" json:"student_id"`
	BookID               int32            `db:"book_id" json:"book_id"`
	TransactionType      string           `db:"transaction_type" json:"transaction_type"`
	TransactionDate      pgtype.Timestamp `db:"transaction_date" json:"transaction_date"`
	DueDate              pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate         pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	LibrarianID          pgtype.Int4      `db:"librarian_id" json:"librarian_id"`
	FineAmount           pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid             pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	Notes                pgtype.Text      `db:"notes" json:"notes"`
	CreatedAt            pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ReturnCondition      pgtype.Text      `db:"return_condition" json:"return_condition"`
	ConditionNotes       pgtype.Text      `db:"condition_notes" json:"condition_notes"`
	FineWaived           pgtype.Bool      `db:"fine_waived" json:"fine_waived"`
	FineWaivedAt         pgtype.Timestamp `db:"fine_waived_at" json:"fine_waived_at"`
	FineWaivedBy         pgtype.Int4      `db:"fine_waived_by" json:"fine_waived_by"`
	FineWaivedReason     pgtype.Text      `db:"fine_waived_reason" json:"fine_waived_reason"`
	FinePaidAt           pgtype.Timestamp `db:"fine_paid_at" json:"fine_paid_at"`
	CopyID               pgtype.Int4      `db:"copy_id" json:"copy_id"`
	Status               pgtype.Text      `db:"status" json:"status"`
	RenewalCount         pgtype.Int4      `db:"renewal_count" json:"renewal_count"`
	LastRenewedAt        pgtype.Timestamp `db:"last_renewed_at" json:"last_renewed_at"`
	LastRenewedBy        pgtype.Int4      `db:"last_renewed_by" json:"last_renewed_by"`
	FirstName            string           `db:"first_name" json:"first_name"`
	LastName             string           `db:"last_name" json:"last_name"`
	StudentID_2          string           `db:"student_id_2" json:"student_id_2"`
	Title                string           `db:"title" json:"title"`
	Author               string           `db:"author" json:"author"`
	BookID_2             string           `db:"book_id_2" json:"book_id_2"`
	CoverImageUrl        pgtype.Text      `db:"cover_image_url" json:"cover_image_url"`
	CopyBarcode          pgtype.Text      `db:"copy_barcode" json:"copy_barcode"`
	CopyCondition        pgtype.Text      `db:"copy_condition" json:"copy_condition"`
	StudentDeletedAt     pgtype.Timestamp `db:"student_deleted_at" json:"student_deleted_at"`
	StudentDeletedByName pgtype.Text      `db:"student_deleted_by_name" json:"student_deleted_by_name"`
}

// Copy-level transaction tracking queries
func (q *Queries) GetTransactionByIDWithCopy(ctx context.Context, id int32) (GetTransactionByIDWithCopyRow, error) {
	row := q.db.QueryRow(ctx, getTransactionByIDWithCopy, id)
	var i GetTransactionByIDWithCopyRow
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.DueDate,
		&i.ReturnedDate,
		&i.LibrarianID,
		&i.FineAmount,
		&i.FinePaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReturnCondition,
		&i.ConditionNotes,
		&i.FineWaived,
		&i.FineWaivedAt,
		&i.FineWaivedBy,
		&i.FineWaivedReason,
		&i.FinePaidAt,
		&i.CopyID,
		&i.Status,
		&i.RenewalCount,
		&i.LastRenewedAt,
		&i.LastRenewedBy,
		&i.FirstName,
		&i.LastName,
		&i.StudentID_2,
		&i.Title,
		&i.Author,
		&i.BookID_2,
		&i.CoverImageUrl,
		&i.CopyBarcode,
		&i.CopyCondition,
		&i.StudentDeletedAt,
		&i.StudentDeletedByName,
	)
	return i, err
}

const getTransactionRenewalCount = `-- name: GetTransactionRenewalCount :one
SELECT COALESCE(renewal_count, 0) as renewal_count
FROM transactions
WHERE id = $1
`

// Get the renewal count for a specific transaction
func (q *Queries) GetTransactionRenewalCount(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, getTransactionRenewalCount, id)
	var renewal_count int32
	err := row.Scan(&renewal_count)
	return renewal_count, err
}

const hasActiveReservationsByOtherStudents = `-- name: HasActiveReservationsByOtherStudents :one
SELECT EXISTS(
    SELECT 1 FROM reservations
    WHERE book_id = $1 AND student_id != $2 AND status IN ('active', 'ready')
)
`

type HasActiveReservationsByOtherStudentsParams struct {
	BookID    int32 `db:"book_id" json:"book_id"`
	StudentID int32 `db:"student_id" json:"student_id"`
}

func (q *Queries) HasActiveReservationsByOtherStudents(ctx context.Context, arg HasActiveReservationsByOtherStudentsParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveReservationsByOtherStudents, arg.BookID, arg.StudentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveBorrowings = `-- name: ListActiveBorrowings :many
SELECT t.id, t.student_id, t.book_id, t.transaction_type, t.transaction_date, t.due_date, t.returned_date, t.librarian_id, t.fine_amount, t.fine_paid, t.notes, t.created_at, t.updated_at, t.return_condition, t.condition_notes, t.fine_waived, t.fine_waived_at, t.fine_waived_by, t.fine_waived_reason, t.fine_paid_at, t.copy_id, t.status, t.renewal_count, t.last_renewed_at, t.last_renewed_by, s.first_name, s.last_name, s.student_id, b.title, b.author, b.book_id
FROM transactions t
JOIN students s ON t.student_id = s.id
JOIN books b ON t.book_id = b.id
WHERE t.returned_date IS NULL AND t.transaction_type = 'borrow'
ORDER BY t.due_date ASC
LIMIT $1 OFFSET $2
`

type ListActiveBorrowingsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListActiveBorrowingsRow struct {
	ID               int32            `db:"id" json:"id"`
	StudentID        int32            `db:"student_id" json:"student_id"`
	BookID           int32            `db:"book_id" json:"book_id"`
	TransactionType  string           `db:"transaction_type" json:"transaction_type"`
	TransactionDate  pgtype.Timestamp `db:"transaction_date" json:"transaction_date"`
	DueDate          pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate     pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	LibrarianID      pgtype.Int4      `db:"librarian_id" json:"librarian_id"`
	FineAmount       pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid         pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	Notes            pgtype.Text      `db:"notes" json:"notes"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ReturnCondition  pgtype.Text      `db:"return_condition" json:"return_condition"`
	ConditionNotes   pgtype.Text      `db:"condition_notes" json:"condition_notes"`
	FineWaived       pgtype.Bool      `db:"fine_waived" json:"fine_waived"`
	FineWaivedAt     pgtype.Timestamp `db:"fine_waived_at" json:"fine_waived_at"`
	FineWaivedBy     pgtype.Int4      `db:"fine_waived_by" json:"fine_waived_by"`
	FineWaivedReason pgtype.Text      `db:"fine_waived_reason" json:"fine_waived_reason"`
	FinePaidAt       pgtype.Timestamp `db:"fine_paid_at" json:"fine_paid_at"`
	CopyID           pgtype.Int4      `db:"copy_id" json:"copy_id"`
	Status           pgtype.Text      `db:"status" json:"status"`
	RenewalCount     pgtype.Int4      `db:"renewal_count" json:"renewal_count"`
	LastRenewedAt    pgtype.Timestamp `db:"last_renewed_at" json:"last_renewed_at"`
	LastRenewedBy    pgtype.Int4      `db:"last_renewed_by" json:"last_renewed_by"`
	FirstName        string           `db:"first_name" json:"first_name"`
	LastName         string           `db:"last_name" json:"last_name"`
	StudentID_2      string           `db:"student_id_2" json:"student_id_2"`
	Title            string           `db:"title" json:"title"`
	Author           string           `db:"author" json:"author"`
	BookID_2         string           `db:"book_id_2" json:"book_id_2"`
}

func (q *Queries) ListActiveBorrowings(ctx context.Context, arg ListActiveBorrowingsParams) ([]ListActiveBorrowingsRow, error) {
	rows, err := q.db.Query(ctx, listActiveBorrowings, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveBorrowingsRow{}
	for rows.Next() {
		var i ListActiveBorrowingsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.BookID,
			&i.TransactionType,
			&i.TransactionDate,
			&i.DueDate,
			&i.ReturnedDate,
			&i.LibrarianID,
			&i.FineAmount,
			&i.FinePaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReturnCondition,
			&i.ConditionNotes,
			&i.FineWaived,
			&i.FineWaivedAt,
			&i.FineWaivedBy,
			&i.FineWaivedReason,
			&i.FinePaidAt,
			&i.CopyID,
			&i.Status,
			&i.RenewalCount,
			&i.LastRenewedAt,
			&i.LastRenewedBy,
			&i.FirstName,
			&i.LastName,
			&i.StudentID_2,
			&i.Title,
			&i.Author,
			&i.BookID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTransactionsByStudent = `-- name: ListActiveTransactionsByStudent :many
SELECT t.id, t.student_id, t.book_id, t.transaction_type, t.transaction_date, t.due_date, t.returned_date, t.librarian_id, t.fine_amount, t.fine_paid, t.notes, t.created_at, t.updated_at, t.return_condition, t.condition_notes, t.fine_waived, t.fine_waived_at, t.fine_waived_by, t.fine_waived_reason, t.fine_paid_at, t.copy_id, t.status, t.renewal_count, t.last_renewed_at, t.last_renewed_by, b.title, b.author, b.book_id
FROM transactions t
JOIN books b ON t.book_id = b.id
WHERE t.student_id = $1 AND t.returned_date IS NULL
ORDER BY t.due_date ASC
`

type ListActiveTransactionsByStudentRow struct {
	ID               int32            `db:"id" json:"id"`
	StudentID        int32            `db:"student_id" json:"student_id"`
	BookID           int32            `db:"book_id" json:"book_id"`
	TransactionType  string           `db:"transaction_type" json:"transaction_type"`
	TransactionDate  pgtype.Timestamp `db:"transaction_date" json:"transaction_date"`
	DueDate          pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate     pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	LibrarianID      pgtype.Int4      `db:"librarian_id" json:"librarian_id"`
	FineAmount       pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid         pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	Notes            pgtype.Text      `db:"notes" json:"notes"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ReturnCondition  pgtype.Text      `db:"return_condition" json:"return_condition"`
	ConditionNotes   pgtype.Text      `db:"condition_notes" json:"condition_notes"`
	FineWaived       pgtype.Bool      `db:"fine_waived" json:"fine_waived"`
	FineWaivedAt     pgtype.Timestamp `db:"fine_waived_at" json:"fine_waived_at"`
	FineWaivedBy     pgtype.Int4      `db:"fine_waived_by" json:"fine_waived_by"`
	FineWaivedReason pgtype.Text      `db:"fine_waived_reason" json:"fine_waived_reason"`
	FinePaidAt       pgtype.Timestamp `db:"fine_paid_at" json:"fine_paid_at"`
	CopyID           pgtype.Int4      `db:"copy_id" json:"copy_id"`
	Status           pgtype.Text      `db:"status" json:"status"`
	RenewalCount     pgtype.Int4      `db:"renewal_count" json:"renewal_count"`
	LastRenewedAt    pgtype.Timestamp `db:"last_renewed_at" json:"last_renewed_at"`
	LastRenewedBy    pgtype.Int4      `db:"last_renewed_by" json:"last_renewed_by"`
	Title            string           `db:"title" json:"title"`
	Author           string           `db:"author" json:"author"`
	BookID_2         string           `db:"book_id_2" json:"book_id_2"`
}

func (q *Queries) ListActiveTransactionsByStudent(ctx context.Context, studentID int32) ([]ListActiveTransactionsByStudentRow, error) {
	rows, err := q.db.Query(ctx, listActiveTransactionsByStudent, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveTransactionsByStudentRow{}
	for rows.Next() {
		var i ListActiveTransactionsByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.BookID,
			&i.TransactionType,
			&i.TransactionDate,
			&i.DueDate,
			&i.ReturnedDate,
			&i.LibrarianID,
			&i.FineAmount,
			&i.FinePaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReturnCondition,
			&i.ConditionNotes,
			&i.FineWaived,
			&i.FineWaivedAt,
			&i.FineWaivedBy,
			&i.FineWaivedReason,
			&i.FinePaidAt,
			&i.CopyID,
			&i.Status,
			&i.RenewalCount,
			&i.LastRenewedAt,
			&i.LastRenewedBy,
			&i.Title,
			&i.Author,
			&i.BookID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueTransactions = `-- name: ListOverdueTransactions :many
SELECT t.id, t.student_id, t.book_id, t.transaction_type, t.transaction_date, t.due_date, t.returned_date, t.librarian_id, t.fine_amount, t.fine_paid, t.notes, t.created_at, t.updated_at, t.return_condition, t.condition_notes, t.fine_waived, t.fine_waived_at, t.fine_waived_by, t.fine_waived_reason, t.fine_paid_at, t.copy_id, t.status, t.renewal_count, t.last_renewed_at, t.last_renewed_by, s.first_name, s.last_name, s.student_id, s.email, b.title, b.author, b.book_id, b.isbn,
    EXTRACT(DAY FROM (NOW() - t.due_date))::int as days_overdue
FROM transactions t
JOIN students s ON t.student_id = s.id
JOIN books b ON t.book_id = b.id
WHERE t.due_date < NOW() AND t.returned_date IS NULL AND t.transaction_type = 'borrow'
  AND s.deleted_at IS NULL
  AND s.is_active = true
  AND b.deleted_at IS NULL
ORDER BY t.due_date ASC
LIMIT $1 OFFSET $2
`

type ListOverdueTransactionsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListOverdueTransactionsRow struct {
	ID               int32            `db:"id" json:"id"`
	StudentID        int32            `db:"student_id" json:"student_id"`
	BookID           int32            `db:"book_id" json:"book_id"`
	TransactionType  string           `db:"transaction_type" json:"transaction_type"`
	TransactionDate  pgtype.Timestamp `db:"transaction_date" json:"transaction_date"`
	DueDate          pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate     pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	LibrarianID      pgtype.Int4      `db:"librarian_id" json:"librarian_id"`
	FineAmount       pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid         pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	Notes            pgtype.Text      `db:"notes" json:"notes"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ReturnCondition  pgtype.Text      `db:"return_condition" json:"return_condition"`
	ConditionNotes   pgtype.Text      `db:"condition_notes" json:"condition_notes"`
	FineWaived       pgtype.Bool      `db:"fine_waived" json:"fine_waived"`
	FineWaivedAt     pgtype.Timestamp `db:"fine_waived_at" json:"fine_waived_at"`
	FineWaivedBy     pgtype.Int4      `db:"fine_waived_by" json:"fine_waived_by"`
	FineWaivedReason pgtype.Text      `db:"fine_waived_reason" json:"fine_waived_reason"`
	FinePaidAt       pgtype.Timestamp `db:"fine_paid_at" json:"fine_paid_at"`
	CopyID           pgtype.Int4      `db:"copy_id" json:"copy_id"`
	Status           pgtype.Text      `db:"status" json:"status"`
	RenewalCount     pgtype.Int4      `db:"renewal_count" json:"renewal_count"`
	LastRenewedAt    pgtype.Timestamp `db:"last_renewed_at" json:"last_renewed_at"`
	LastRenewedBy    pgtype.Int4      `db:"last_renewed_by" json:"last_renewed_by"`
	FirstName        string           `db:"first_name" json:"first_name"`
	LastName         string           `db:"last_name" json:"last_name"`
	StudentID_2      string           `db:"student_id_2" json:"student_id_2"`
	Email            pgtype.Text      `db:"email" json:"email"`
	Title            string           `db:"title" json:"title"`
	Author           string           `db:"author" json:"author"`
	BookID_2         string           `db:"book_id_2" json:"book_id_2"`
	Isbn             pgtype.Text      `db:"isbn" json:"isbn"`
	DaysOverdue      int32            `db:"days_overdue" json:"days_overdue"`
}

func (q *Queries) ListOverdueTransactions(ctx context.Context, arg ListOverdueTransactionsParams) ([]ListOverdueTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listOverdueTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverdueTransactionsRow{}
	for rows.Next() {
		var i ListOverdueTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.BookID,
			&i.TransactionType,
			&i.TransactionDate,
			&i.DueDate,
			&i.ReturnedDate,
			&i.LibrarianID,
			&i.FineAmount,
			&i.FinePaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReturnCondition,
			&i.ConditionNotes,
			&i.FineWaived,
			&i.FineWaivedAt,
			&i.FineWaivedBy,
			&i.FineWaivedReason,
			&i.FinePaidAt,
			&i.CopyID,
			&i.Status,
			&i.RenewalCount,
			&i.LastRenewedAt,
			&i.LastRenewedBy,
			&i.FirstName,
			&i.LastName,
			&i.StudentID_2,
			&i.Email,
			&i.Title,
			&i.Author,
			&i.BookID_2,
			&i.Isbn,
			&i.DaysOverdue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRenewalsByStudentAndBook = `-- name: ListRenewalsByStudentAndBook :many
SELECT t.id, t.student_id, t.book_id, t.transaction_type, t.transaction_date, t.due_date, t.returned_date, t.librarian_id, t.fine_amount, t.fine_paid, t.notes, t.created_at, t.updated_at, t.return_condition, t.condition_notes, t.fine_waived, t.fine_waived_at, t.fine_waived_by, t.fine_waived_reason, t.fine_paid_at, t.copy_id, t.status, t.renewal_count, t.last_renewed_at, t.last_renewed_by, b.title, b.author, b.book_id
FROM transactions t
JOIN books b ON t.book_id = b.id
WHERE t.student_id = $1 AND t.book_id = $2 AND t.transaction_type = 'renew'
ORDER BY t.transaction_date DESC
`

type ListRenewalsByStudentAndBookParams struct {
	StudentID int32 `db:"student_id" json:"student_id"`
	BookID    int32 `db:"book_id" json:"book_id"`
}

type ListRenewalsByStudentAndBookRow struct {
	ID               int32            `db:"id" json:"id"`
	StudentID        int32            `db:"student_id" json:"student_id"`
	BookID           int32            `db:"book_id" json:"book_id"`
	TransactionType  string           `db:"transaction_type" json:"transaction_type"`
	TransactionDate  pgtype.Timestamp `db:"transaction_date" json:"transaction_date"`
	DueDate          pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate     pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	LibrarianID      pgtype.Int4      `db:"librarian_id" json:"librarian_id"`
	FineAmount       pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid         pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	Notes            pgtype.Text      `db:"notes" json:"notes"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ReturnCondition  pgtype.Text      `db:"return_condition" json:"return_condition"`
	ConditionNotes   pgtype.Text      `db:"condition_notes" json:"condition_notes"`
	FineWaived       pgtype.Bool      `db:"fine_waived" json:"fine_waived"`
	FineWaivedAt     pgtype.Timestamp `db:"fine_waived_at" json:"fine_waived_at"`
	FineWaivedBy     pgtype.Int4      `db:"fine_waived_by" json:"fine_waived_by"`
	FineWaivedReason pgtype.Text      `db:"fine_waived_reason" json:"fine_waived_reason"`
	FinePaidAt       pgtype.Timestamp `db:"fine_paid_at" json:"fine_paid_at"`
	CopyID           pgtype.Int4      `db:"copy_id" json:"copy_id"`
	Status           pgtype.Text      `db:"status" json:"status"`
	RenewalCount     pgtype.Int4      `db:"renewal_count" json:"renewal_count"`
	LastRenewedAt    pgtype.Timestamp `db:"last_renewed_at" json:"last_renewed_at"`
	LastRenewedBy    pgtype.Int4      `db:"last_renewed_by" json:"last_renewed_by"`
	Title            string           `db:"title" json:"title"`
	Author           string           `db:"author" json:"author"`
	BookID_2         string           `db:"book_id_2" json:"book_id_2"`
}

func (q *Queries) ListRenewalsByStudentAndBook(ctx context.Context, arg ListRenewalsByStudentAndBookParams) ([]ListRenewalsByStudentAndBookRow, error) {
	rows, err := q.db.Query(ctx, listRenewalsByStudentAndBook, arg.StudentID, arg.BookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRenewalsByStudentAndBookRow{}
	for rows.Next() {
		var i ListRenewalsByStudentAndBookRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.BookID,
			&i.TransactionType,
			&i.TransactionDate,
			&i.DueDate,
			&i.ReturnedDate,
			&i.LibrarianID,
			&i.FineAmount,
			&i.FinePaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReturnCondition,
			&i.ConditionNotes,
			&i.FineWaived,
			&i.FineWaivedAt,
			&i.FineWaivedBy,
			&i.FineWaivedReason,
			&i.FinePaidAt,
			&i.CopyID,
			&i.Status,
			&i.RenewalCount,
			&i.LastRenewedAt,
			&i.LastRenewedBy,
			&i.Title,
			&i.Author,
			&i.BookID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactions = `-- name: ListTransactions :many
SELECT t.id, t.student_id, t.book_id, t.transaction_type, t.transaction_date, t.due_date, t.returned_date, t.librarian_id, t.fine_amount, t.fine_paid, t.notes, t.created_at, t.updated_at, t.return_condition, t.condition_notes, t.fine_waived, t.fine_waived_at, t.fine_waived_by, t.fine_waived_reason, t.fine_paid_at, t.copy_id, t.status, t.renewal_count, t.last_renewed_at, t.last_renewed_by, s.first_name, s.last_name, s.student_id, b.title, b.author, b.book_id
FROM transactions t
JOIN students s ON t.student_id = s.id
JOIN books b ON t.book_id = b.id
ORDER BY t.transaction_date DESC
LIMIT $1 OFFSET $2
`

type ListTransactionsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListTransactionsRow struct {
	ID               int32            `db:"id" json:"id"`
	StudentID        int32            `db:"student_id" json:"student_id"`
	BookID           int32            `db:"book_id" json:"book_id"`
	TransactionType  string           `db:"transaction_type" json:"transaction_type"`
	TransactionDate  pgtype.Timestamp `db:"transaction_date" json:"transaction_date"`
	DueDate          pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate     pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	LibrarianID      pgtype.Int4      `db:"librarian_id" json:"librarian_id"`
	FineAmount       pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid         pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	Notes            pgtype.Text      `db:"notes" json:"notes"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ReturnCondition  pgtype.Text      `db:"return_condition" json:"return_condition"`
	ConditionNotes   pgtype.Text      `db:"condition_notes" json:"condition_notes"`
	FineWaived       pgtype.Bool      `db:"fine_waived" json:"fine_waived"`
	FineWaivedAt     pgtype.Timestamp `db:"fine_waived_at" json:"fine_waived_at"`
	FineWaivedBy     pgtype.Int4      `db:"fine_waived_by" json:"fine_waived_by"`
	FineWaivedReason pgtype.Text      `db:"fine_waived_reason" json:"fine_waived_reason"`
	FinePaidAt       pgtype.Timestamp `db:"fine_paid_at" json:"fine_paid_at"`
	CopyID           pgtype.Int4      `db:"copy_id" json:"copy_id"`
	Status           pgtype.Text      `db:"status" json:"status"`
	RenewalCount     pgtype.Int4      `db:"renewal_count" json:"renewal_count"`
	LastRenewedAt    pgtype.Timestamp `db:"last_renewed_at" json:"last_renewed_at"`
	LastRenewedBy    pgtype.Int4      `db:"last_renewed_by" json:"last_renewed_by"`
	FirstName        string           `db:"first_name" json:"first_name"`
	LastName         string           `db:"last_name" json:"last_name"`
	StudentID_2      string           `db:"student_id_2" json:"student_id_2"`
	Title            string           `db:"title" json:"title"`
	Author           string           `db:"author" json:"author"`
	BookID_2         string           `db:"book_id_2" json:"book_id_2"`
}

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]ListTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsRow{}
	for rows.Next() {
		var i ListTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.BookID,
			&i.TransactionType,
			&i.TransactionDate,
			&i.DueDate,
			&i.ReturnedDate,
			&i.LibrarianID,
			&i.FineAmount,
			&i.FinePaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReturnCondition,
			&i.ConditionNotes,
			&i.FineWaived,
			&i.FineWaivedAt,
			&i.FineWaivedBy,
			&i.FineWaivedReason,
			&i.FinePaidAt,
			&i.CopyID,
			&i.Status,
			&i.RenewalCount,
			&i.LastRenewedAt,
			&i.LastRenewedBy,
			&i.FirstName,
			&i.LastName,
			&i.StudentID_2,
			&i.Title,
			&i.Author,
			&i.BookID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByBook = `-- name: ListTransactionsByBook :many
SELECT t.id, t.student_id, t.book_id, t.transaction_type, t.transaction_date, t.due_date, t.returned_date, t.librarian_id, t.fine_amount, t.fine_paid, t.notes, t.created_at, t.updated_at, t.return_condition, t.condition_notes, t.fine_waived, t.fine_waived_at, t.fine_waived_by, t.fine_waived_reason, t.fine_paid_at, t.copy_id, t.status, t.renewal_count, t.last_renewed_at, t.last_renewed_by, s.first_name, s.last_name, s.student_id
FROM transactions t
JOIN students s ON t.student_id = s.id
WHERE t.book_id = $1
ORDER BY t.transaction_date DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByBookParams struct {
	BookID int32 `db:"book_id" json:"book_id"`
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListTransactionsByBookRow struct {
	ID               int32            `db:"id" json:"id"`
	StudentID        int32            `db:"student_id" json:"student_id"`
	BookID           int32            `db:"book_id" json:"book_id"`
	TransactionType  string           `db:"transaction_type" json:"transaction_type"`
	TransactionDate  pgtype.Timestamp `db:"transaction_date" json:"transaction_date"`
	DueDate          pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate     pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	LibrarianID      pgtype.Int4      `db:"librarian_id" json:"librarian_id"`
	FineAmount       pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid         pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	Notes            pgtype.Text      `db:"notes" json:"notes"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ReturnCondition  pgtype.Text      `db:"return_condition" json:"return_condition"`
	ConditionNotes   pgtype.Text      `db:"condition_notes" json:"condition_notes"`
	FineWaived       pgtype.Bool      `db:"fine_waived" json:"fine_waived"`
	FineWaivedAt     pgtype.Timestamp `db:"fine_waived_at" json:"fine_waived_at"`
	FineWaivedBy     pgtype.Int4      `db:"fine_waived_by" json:"fine_waived_by"`
	FineWaivedReason pgtype.Text      `db:"fine_waived_reason" json:"fine_waived_reason"`
	FinePaidAt       pgtype.Timestamp `db:"fine_paid_at" json:"fine_paid_at"`
	CopyID           pgtype.Int4      `db:"copy_id" json:"copy_id"`
	Status           pgtype.Text      `db:"status" json:"status"`
	RenewalCount     pgtype.Int4      `db:"renewal_count" json:"renewal_count"`
	LastRenewedAt    pgtype.Timestamp `db:"last_renewed_at" json:"last_renewed_at"`
	LastRenewedBy    pgtype.Int4      `db:"last_renewed_by" json:"last_renewed_by"`
	FirstName        string           `db:"first_name" json:"first_name"`
	LastName         string           `db:"last_name" json:"last_name"`
	StudentID_2      string           `db:"student_id_2" json:"student_id_2"`
}

func (q *Queries) ListTransactionsByBook(ctx context.Context, arg ListTransactionsByBookParams) ([]ListTransactionsByBookRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByBook, arg.BookID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByBookRow{}
	for rows.Next() {
		var i ListTransactionsByBookRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.BookID,
			&i.TransactionType,
			&i.TransactionDate,
			&i.DueDate,
			&i.ReturnedDate,
			&i.LibrarianID,
			&i.FineAmount,
			&i.FinePaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReturnCondition,
			&i.ConditionNotes,
			&i.FineWaived,
			&i.FineWaivedAt,
			&i.FineWaivedBy,
			&i.FineWaivedReason,
			&i.FinePaidAt,
			&i.CopyID,
			&i.Status,
			&i.RenewalCount,
			&i.LastRenewedAt,
			&i.LastRenewedBy,
			&i.FirstName,
			&i.LastName,
			&i.StudentID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByStudent = `-- name: ListTransactionsByStudent :many
SELECT t.id, t.student_id, t.book_id, t.transaction_type, t.transaction_date, t.due_date, t.returned_date, t.librarian_id, t.fine_amount, t.fine_paid, t.notes, t.created_at, t.updated_at, t.return_condition, t.condition_notes, t.fine_waived, t.fine_waived_at, t.fine_waived_by, t.fine_waived_reason, t.fine_paid_at, t.copy_id, t.status, t.renewal_count, t.last_renewed_at, t.last_renewed_by, b.title, b.author, b.book_id
FROM transactions t
JOIN books b ON t.book_id = b.id
WHERE t.student_id = $1
ORDER BY t.transaction_date DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByStudentParams struct {
	StudentID int32 `db:"student_id" json:"student_id"`
	Limit     int32 `db:"limit" json:"limit"`
	Offset    int32 `db:"offset" json:"offset"`
}

type ListTransactionsByStudentRow struct {
	ID               int32            `db:"id" json:"id"`
	StudentID        int32            `db:"student_id" json:"student_id"`
	BookID           int32            `db:"book_id" json:"book_id"`
	TransactionType  string           `db:"transaction_type" json:"transaction_type"`
	TransactionDate  pgtype.Timestamp `db:"transaction_date" json:"transaction_date"`
	DueDate          pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate     pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	LibrarianID      pgtype.Int4      `db:"librarian_id" json:"librarian_id"`
	FineAmount       pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid         pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	Notes            pgtype.Text      `db:"notes" json:"notes"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ReturnCondition  pgtype.Text      `db:"return_condition" json:"return_condition"`
	ConditionNotes   pgtype.Text      `db:"condition_notes" json:"condition_notes"`
	FineWaived       pgtype.Bool      `db:"fine_waived" json:"fine_waived"`
	FineWaivedAt     pgtype.Timestamp `db:"fine_waived_at" json:"fine_waived_at"`
	FineWaivedBy     pgtype.Int4      `db:"fine_waived_by" json:"fine_waived_by"`
	FineWaivedReason pgtype.Text      `db:"fine_waived_reason" json:"fine_waived_reason"`
	FinePaidAt       pgtype.Timestamp `db:"fine_paid_at" json:"fine_paid_at"`
	CopyID           pgtype.Int4      `db:"copy_id" json:"copy_id"`
	Status           pgtype.Text      `db:"status" json:"status"`
	RenewalCount     pgtype.Int4      `db:"renewal_count" json:"renewal_count"`
	LastRenewedAt    pgtype.Timestamp `db:"last_renewed_at" json:"last_renewed_at"`
	LastRenewedBy    pgtype.Int4      `db:"last_renewed_by" json:"last_renewed_by"`
	Title            string           `db:"title" json:"title"`
	Author           string           `db:"author" json:"author"`
	BookID_2         string           `db:"book_id_2" json:"book_id_2"`
}

func (q *Queries) ListTransactionsByStudent(ctx context.Context, arg ListTransactionsByStudentParams) ([]ListTransactionsByStudentRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsByStudent, arg.StudentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByStudentRow{}
	for rows.Next() {
		var i ListTransactionsByStudentRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.BookID,
			&i.TransactionType,
			&i.TransactionDate,
			&i.DueDate,
			&i.ReturnedDate,
			&i.LibrarianID,
			&i.FineAmount,
			&i.FinePaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReturnCondition,
			&i.ConditionNotes,
			&i.FineWaived,
			&i.FineWaivedAt,
			&i.FineWaivedBy,
			&i.FineWaivedReason,
			&i.FinePaidAt,
			&i.CopyID,
			&i.Status,
			&i.RenewalCount,
			&i.LastRenewedAt,
			&i.LastRenewedBy,
			&i.Title,
			&i.Author,
			&i.BookID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsDueSoon = `-- name: ListTransactionsDueSoon :many

SELECT t.id, t.student_id, t.book_id, t.transaction_type, t.transaction_date, t.due_date, t.returned_date, t.librarian_id, t.fine_amount, t.fine_paid, t.notes, t.created_at, t.updated_at, t.return_condition, t.condition_notes, t.fine_waived, t.fine_waived_at, t.fine_waived_by, t.fine_waived_reason, t.fine_paid_at, t.copy_id, t.status, t.renewal_count, t.last_renewed_at, t.last_renewed_by, s.first_name, s.last_name, s.student_id, s.email, b.title, b.author, b.book_id
FROM transactions t
JOIN students s ON t.student_id = s.id
JOIN books b ON t.book_id = b.id
WHERE t.due_date >= NOW() AND t.due_date <= NOW() + INTERVAL '3 days'
  AND t.returned_date IS NULL
  AND t.transaction_type = 'borrow'
  AND s.is_active = true
  AND s.deleted_at IS NULL
ORDER BY t.due_date ASC
`

type ListTransactionsDueSoonRow struct {
	ID               int32            `db:"id" json:"id"`
	StudentID        int32            `db:"student_id" json:"student_id"`
	BookID           int32            `db:"book_id" json:"book_id"`
	TransactionType  string           `db:"transaction_type" json:"transaction_type"`
	TransactionDate  pgtype.Timestamp `db:"transaction_date" json:"transaction_date"`
	DueDate          pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate     pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	LibrarianID      pgtype.Int4      `db:"librarian_id" json:"librarian_id"`
	FineAmount       pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid         pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	Notes            pgtype.Text      `db:"notes" json:"notes"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ReturnCondition  pgtype.Text      `db:"return_condition" json:"return_condition"`
	ConditionNotes   pgtype.Text      `db:"condition_notes" json:"condition_notes"`
	FineWaived       pgtype.Bool      `db:"fine_waived" json:"fine_waived"`
	FineWaivedAt     pgtype.Timestamp `db:"fine_waived_at" json:"fine_waived_at"`
	FineWaivedBy     pgtype.Int4      `db:"fine_waived_by" json:"fine_waived_by"`
	FineWaivedReason pgtype.Text      `db:"fine_waived_reason" json:"fine_waived_reason"`
	FinePaidAt       pgtype.Timestamp `db:"fine_paid_at" json:"fine_paid_at"`
	CopyID           pgtype.Int4      `db:"copy_id" json:"copy_id"`
	Status           pgtype.Text      `db:"status" json:"status"`
	RenewalCount     pgtype.Int4      `db:"renewal_count" json:"renewal_count"`
	LastRenewedAt    pgtype.Timestamp `db:"last_renewed_at" json:"last_renewed_at"`
	LastRenewedBy    pgtype.Int4      `db:"last_renewed_by" json:"last_renewed_by"`
	FirstName        string           `db:"first_name" json:"first_name"`
	LastName         string           `db:"last_name" json:"last_name"`
	StudentID_2      string           `db:"student_id_2" json:"student_id_2"`
	Email            pgtype.Text      `db:"email" json:"email"`
	Title            string           `db:"title" json:"title"`
	Author           string           `db:"author" json:"author"`
	BookID_2         string           `db:"book_id_2" json:"book_id_2"`
}

// Notification-related queries for Phase 7.2
func (q *Queries) ListTransactionsDueSoon(ctx context.Context) ([]ListTransactionsDueSoonRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsDueSoon)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsDueSoonRow{}
	for rows.Next() {
		var i ListTransactionsDueSoonRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.BookID,
			&i.TransactionType,
			&i.TransactionDate,
			&i.DueDate,
			&i.ReturnedDate,
			&i.LibrarianID,
			&i.FineAmount,
			&i.FinePaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReturnCondition,
			&i.ConditionNotes,
			&i.FineWaived,
			&i.FineWaivedAt,
			&i.FineWaivedBy,
			&i.FineWaivedReason,
			&i.FinePaidAt,
			&i.CopyID,
			&i.Status,
			&i.RenewalCount,
			&i.LastRenewedAt,
			&i.LastRenewedBy,
			&i.FirstName,
			&i.LastName,
			&i.StudentID_2,
			&i.Email,
			&i.Title,
			&i.Author,
			&i.BookID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsOverdue = `-- name: ListTransactionsOverdue :many
SELECT t.id, t.student_id, t.book_id, t.transaction_type, t.transaction_date, t.due_date, t.returned_date, t.librarian_id, t.fine_amount, t.fine_paid, t.notes, t.created_at, t.updated_at, t.return_condition, t.condition_notes, t.fine_waived, t.fine_waived_at, t.fine_waived_by, t.fine_waived_reason, t.fine_paid_at, t.copy_id, t.status, t.renewal_count, t.last_renewed_at, t.last_renewed_by, s.first_name, s.last_name, s.student_id, s.email, b.title, b.author, b.book_id
FROM transactions t
JOIN students s ON t.student_id = s.id
JOIN books b ON t.book_id = b.id
WHERE t.due_date < NOW() AND t.returned_date IS NULL
  AND t.transaction_type = 'borrow'
  AND s.is_active = true
  AND s.deleted_at IS NULL
ORDER BY t.due_date ASC
`

type ListTransactionsOverdueRow struct {
	ID               int32            `db:"id" json:"id"`
	StudentID        int32            `db:"student_id" json:"student_id"`
	BookID           int32            `db:"book_id" json:"book_id"`
	TransactionType  string           `db:"transaction_type" json:"transaction_type"`
	TransactionDate  pgtype.Timestamp `db:"transaction_date" json:"transaction_date"`
	DueDate          pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate     pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	LibrarianID      pgtype.Int4      `db:"librarian_id" json:"librarian_id"`
	FineAmount       pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid         pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	Notes            pgtype.Text      `db:"notes" json:"notes"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ReturnCondition  pgtype.Text      `db:"return_condition" json:"return_condition"`
	ConditionNotes   pgtype.Text      `db:"condition_notes" json:"condition_notes"`
	FineWaived       pgtype.Bool      `db:"fine_waived" json:"fine_waived"`
	FineWaivedAt     pgtype.Timestamp `db:"fine_waived_at" json:"fine_waived_at"`
	FineWaivedBy     pgtype.Int4      `db:"fine_waived_by" json:"fine_waived_by"`
	FineWaivedReason pgtype.Text      `db:"fine_waived_reason" json:"fine_waived_reason"`
	FinePaidAt       pgtype.Timestamp `db:"fine_paid_at" json:"fine_paid_at"`
	CopyID           pgtype.Int4      `db:"copy_id" json:"copy_id"`
	Status           pgtype.Text      `db:"status" json:"status"`
	RenewalCount     pgtype.Int4      `db:"renewal_count" json:"renewal_count"`
	LastRenewedAt    pgtype.Timestamp `db:"last_renewed_at" json:"last_renewed_at"`
	LastRenewedBy    pgtype.Int4      `db:"last_renewed_by" json:"last_renewed_by"`
	FirstName        string           `db:"first_name" json:"first_name"`
	LastName         string           `db:"last_name" json:"last_name"`
	StudentID_2      string           `db:"student_id_2" json:"student_id_2"`
	Email            pgtype.Text      `db:"email" json:"email"`
	Title            string           `db:"title" json:"title"`
	Author           string           `db:"author" json:"author"`
	BookID_2         string           `db:"book_id_2" json:"book_id_2"`
}

func (q *Queries) ListTransactionsOverdue(ctx context.Context) ([]ListTransactionsOverdueRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsOverdue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsOverdueRow{}
	for rows.Next() {
		var i ListTransactionsOverdueRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.BookID,
			&i.TransactionType,
			&i.TransactionDate,
			&i.DueDate,
			&i.ReturnedDate,
			&i.LibrarianID,
			&i.FineAmount,
			&i.FinePaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReturnCondition,
			&i.ConditionNotes,
			&i.FineWaived,
			&i.FineWaivedAt,
			&i.FineWaivedBy,
			&i.FineWaivedReason,
			&i.FinePaidAt,
			&i.CopyID,
			&i.Status,
			&i.RenewalCount,
			&i.LastRenewedAt,
			&i.LastRenewedBy,
			&i.FirstName,
			&i.LastName,
			&i.StudentID_2,
			&i.Email,
			&i.Title,
			&i.Author,
			&i.BookID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithCopies = `-- name: ListTransactionsWithCopies :many
SELECT t.id, t.student_id, t.book_id, t.transaction_type, t.transaction_date, t.due_date, t.returned_date, t.librarian_id, t.fine_amount, t.fine_paid, t.notes, t.created_at, t.updated_at, t.return_condition, t.condition_notes, t.fine_waived, t.fine_waived_at, t.fine_waived_by, t.fine_waived_reason, t.fine_paid_at, t.copy_id, t.status, t.renewal_count, t.last_renewed_at, t.last_renewed_by,
       s.first_name, s.last_name, s.student_id,
       b.title, b.author, b.book_id, b.cover_image_url,
       bc.barcode as copy_barcode, bc.condition as copy_condition,
       s.deleted_at as student_deleted_at,
       del_user.username as student_deleted_by_name
FROM transactions t
JOIN students s ON t.student_id = s.id
JOIN books b ON t.book_id = b.id
LEFT JOIN book_copies bc ON t.copy_id = bc.id
LEFT JOIN users del_user ON s.deleted_by = del_user.id
ORDER BY t.transaction_date DESC
LIMIT $1 OFFSET $2
`

type ListTransactionsWithCopiesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListTransactionsWithCopiesRow struct {
	ID                   int32            `db:"id" json:"id"`
	StudentID            int32            `db:"student_id" json:"student_id"`
	BookID               int32            `db:"book_id" json:"book_id"`
	TransactionType      string           `db:"transaction_type" json:"transaction_type"`
	TransactionDate      pgtype.Timestamp `db:"transaction_date" json:"transaction_date"`
	DueDate              pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate         pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	LibrarianID          pgtype.Int4      `db:"librarian_id" json:"librarian_id"`
	FineAmount           pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid             pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	Notes                pgtype.Text      `db:"notes" json:"notes"`
	CreatedAt            pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ReturnCondition      pgtype.Text      `db:"return_condition" json:"return_condition"`
	ConditionNotes       pgtype.Text      `db:"condition_notes" json:"condition_notes"`
	FineWaived           pgtype.Bool      `db:"fine_waived" json:"fine_waived"`
	FineWaivedAt         pgtype.Timestamp `db:"fine_waived_at" json:"fine_waived_at"`
	FineWaivedBy         pgtype.Int4      `db:"fine_waived_by" json:"fine_waived_by"`
	FineWaivedReason     pgtype.Text      `db:"fine_waived_reason" json:"fine_waived_reason"`
	FinePaidAt           pgtype.Timestamp `db:"fine_paid_at" json:"fine_paid_at"`
	CopyID               pgtype.Int4      `db:"copy_id" json:"copy_id"`
	Status               pgtype.Text      `db:"status" json:"status"`
	RenewalCount         pgtype.Int4      `db:"renewal_count" json:"renewal_count"`
	LastRenewedAt        pgtype.Timestamp `db:"last_renewed_at" json:"last_renewed_at"`
	LastRenewedBy        pgtype.Int4      `db:"last_renewed_by" json:"last_renewed_by"`
	FirstName            string           `db:"first_name" json:"first_name"`
	LastName             string           `db:"last_name" json:"last_name"`
	StudentID_2          string           `db:"student_id_2" json:"student_id_2"`
	Title                string           `db:"title" json:"title"`
	Author               string           `db:"author" json:"author"`
	BookID_2             string           `db:"book_id_2" json:"book_id_2"`
	CoverImageUrl        pgtype.Text      `db:"cover_image_url" json:"cover_image_url"`
	CopyBarcode          pgtype.Text      `db:"copy_barcode" json:"copy_barcode"`
	CopyCondition        pgtype.Text      `db:"copy_condition" json:"copy_condition"`
	StudentDeletedAt     pgtype.Timestamp `db:"student_deleted_at" json:"student_deleted_at"`
	StudentDeletedByName pgtype.Text      `db:"student_deleted_by_name" json:"student_deleted_by_name"`
}

func (q *Queries) ListTransactionsWithCopies(ctx context.Context, arg ListTransactionsWithCopiesParams) ([]ListTransactionsWithCopiesRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsWithCopies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsWithCopiesRow{}
	for rows.Next() {
		var i ListTransactionsWithCopiesRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.BookID,
			&i.TransactionType,
			&i.TransactionDate,
			&i.DueDate,
			&i.ReturnedDate,
			&i.LibrarianID,
			&i.FineAmount,
			&i.FinePaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReturnCondition,
			&i.ConditionNotes,
			&i.FineWaived,
			&i.FineWaivedAt,
			&i.FineWaivedBy,
			&i.FineWaivedReason,
			&i.FinePaidAt,
			&i.CopyID,
			&i.Status,
			&i.RenewalCount,
			&i.LastRenewedAt,
			&i.LastRenewedBy,
			&i.FirstName,
			&i.LastName,
			&i.StudentID_2,
			&i.Title,
			&i.Author,
			&i.BookID_2,
			&i.CoverImageUrl,
			&i.CopyBarcode,
			&i.CopyCondition,
			&i.StudentDeletedAt,
			&i.StudentDeletedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsWithUnpaidFines = `-- name: ListTransactionsWithUnpaidFines :many
SELECT t.id, t.student_id, t.book_id, t.transaction_type, t.transaction_date, t.due_date, t.returned_date, t.librarian_id, t.fine_amount, t.fine_paid, t.notes, t.created_at, t.updated_at, t.return_condition, t.condition_notes, t.fine_waived, t.fine_waived_at, t.fine_waived_by, t.fine_waived_reason, t.fine_paid_at, t.copy_id, t.status, t.renewal_count, t.last_renewed_at, t.last_renewed_by, s.first_name, s.last_name, s.student_id, s.email, b.title, b.author, b.book_id
FROM transactions t
JOIN students s ON t.student_id = s.id
JOIN books b ON t.book_id = b.id
WHERE t.fine_amount > 0 AND t.fine_paid = false
  AND (COALESCE(t.fine_waived, false) = false)
  AND s.is_active = true
  AND s.deleted_at IS NULL
ORDER BY t.fine_amount DESC
`

type ListTransactionsWithUnpaidFinesRow struct {
	ID               int32            `db:"id" json:"id"`
	StudentID        int32            `db:"student_id" json:"student_id"`
	BookID           int32            `db:"book_id" json:"book_id"`
	TransactionType  string           `db:"transaction_type" json:"transaction_type"`
	TransactionDate  pgtype.Timestamp `db:"transaction_date" json:"transaction_date"`
	DueDate          pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate     pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	LibrarianID      pgtype.Int4      `db:"librarian_id" json:"librarian_id"`
	FineAmount       pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid         pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	Notes            pgtype.Text      `db:"notes" json:"notes"`
	CreatedAt        pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ReturnCondition  pgtype.Text      `db:"return_condition" json:"return_condition"`
	ConditionNotes   pgtype.Text      `db:"condition_notes" json:"condition_notes"`
	FineWaived       pgtype.Bool      `db:"fine_waived" json:"fine_waived"`
	FineWaivedAt     pgtype.Timestamp `db:"fine_waived_at" json:"fine_waived_at"`
	FineWaivedBy     pgtype.Int4      `db:"fine_waived_by" json:"fine_waived_by"`
	FineWaivedReason pgtype.Text      `db:"fine_waived_reason" json:"fine_waived_reason"`
	FinePaidAt       pgtype.Timestamp `db:"fine_paid_at" json:"fine_paid_at"`
	CopyID           pgtype.Int4      `db:"copy_id" json:"copy_id"`
	Status           pgtype.Text      `db:"status" json:"status"`
	RenewalCount     pgtype.Int4      `db:"renewal_count" json:"renewal_count"`
	LastRenewedAt    pgtype.Timestamp `db:"last_renewed_at" json:"last_renewed_at"`
	LastRenewedBy    pgtype.Int4      `db:"last_renewed_by" json:"last_renewed_by"`
	FirstName        string           `db:"first_name" json:"first_name"`
	LastName         string           `db:"last_name" json:"last_name"`
	StudentID_2      string           `db:"student_id_2" json:"student_id_2"`
	Email            pgtype.Text      `db:"email" json:"email"`
	Title            string           `db:"title" json:"title"`
	Author           string           `db:"author" json:"author"`
	BookID_2         string           `db:"book_id_2" json:"book_id_2"`
}

func (q *Queries) ListTransactionsWithUnpaidFines(ctx context.Context) ([]ListTransactionsWithUnpaidFinesRow, error) {
	rows, err := q.db.Query(ctx, listTransactionsWithUnpaidFines)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsWithUnpaidFinesRow{}
	for rows.Next() {
		var i ListTransactionsWithUnpaidFinesRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.BookID,
			&i.TransactionType,
			&i.TransactionDate,
			&i.DueDate,
			&i.ReturnedDate,
			&i.LibrarianID,
			&i.FineAmount,
			&i.FinePaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReturnCondition,
			&i.ConditionNotes,
			&i.FineWaived,
			&i.FineWaivedAt,
			&i.FineWaivedBy,
			&i.FineWaivedReason,
			&i.FinePaidAt,
			&i.CopyID,
			&i.Status,
			&i.RenewalCount,
			&i.LastRenewedAt,
			&i.LastRenewedBy,
			&i.FirstName,
			&i.LastName,
			&i.StudentID_2,
			&i.Email,
			&i.Title,
			&i.Author,
			&i.BookID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTransactionAsFound = `-- name: MarkTransactionAsFound :one
UPDATE transactions
SET
    transaction_type = 'borrow',
    status = 'completed',
    fine_waived = true,
    fine_waived_at = NOW(),
    fine_waived_by = $1,
    fine_waived_reason = 'Book found: ' || $2::text,
    fine_paid = true,
    fine_paid_at = NOW(),
    notes = CASE
        WHEN notes IS NULL OR notes = '' THEN '[FOUND] ' || $2::text || ' | Replacement fine waived'
        ELSE notes || E'\n\n[FOUND] ' || $2::text || ' | Replacement fine waived'
    END,
    updated_at = NOW()
WHERE id = $3
  AND transaction_type = 'lost'
RETURNING id, student_id, book_id, transaction_type, transaction_date, due_date, returned_date, librarian_id, fine_amount, fine_paid, notes, created_at, updated_at, return_condition, condition_notes, fine_waived, fine_waived_at, fine_waived_by, fine_waived_reason, fine_paid_at, copy_id, status, renewal_count, last_renewed_at, last_renewed_by
`

type MarkTransactionAsFoundParams struct {
	WaivedBy    pgtype.Int4 `db:"waived_by" json:"waived_by"`
	FoundReason string      `db:"found_reason" json:"found_reason"`
	ID          int32       `db:"id" json:"id"`
}

// Mark a lost transaction as found: restores transaction_type to 'borrow', sets status to 'returned', waives the replacement fine, and adds found note
func (q *Queries) MarkTransactionAsFound(ctx context.Context, arg MarkTransactionAsFoundParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, markTransactionAsFound, arg.WaivedBy, arg.FoundReason, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.DueDate,
		&i.ReturnedDate,
		&i.LibrarianID,
		&i.FineAmount,
		&i.FinePaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReturnCondition,
		&i.ConditionNotes,
		&i.FineWaived,
		&i.FineWaivedAt,
		&i.FineWaivedBy,
		&i.FineWaivedReason,
		&i.FinePaidAt,
		&i.CopyID,
		&i.Status,
		&i.RenewalCount,
		&i.LastRenewedAt,
		&i.LastRenewedBy,
	)
	return i, err
}

const markTransactionAsLost = `-- name: MarkTransactionAsLost :one
UPDATE transactions
SET
    transaction_type = 'lost',
    returned_date = NOW(),
    fine_amount = $1::numeric,
    fine_paid = false,
    status = 'lost',
    notes = CASE
        WHEN notes IS NULL OR notes = '' THEN '[LOST] ' || $2::text || ' | Replacement fine: KSH ' || $1::text
        ELSE notes || E'\n\n[LOST] ' || $2::text || ' | Replacement fine: KSH ' || $1::text
    END,
    updated_at = NOW()
WHERE id = $3
  AND returned_date IS NULL
  AND transaction_type = 'borrow'
RETURNING id, student_id, book_id, transaction_type, transaction_date, due_date, returned_date, librarian_id, fine_amount, fine_paid, notes, created_at, updated_at, return_condition, condition_notes, fine_waived, fine_waived_at, fine_waived_by, fine_waived_reason, fine_paid_at, copy_id, status, renewal_count, last_renewed_at, last_renewed_by
`

type MarkTransactionAsLostParams struct {
	ReplacementFine pgtype.Numeric `db:"replacement_fine" json:"replacement_fine"`
	LostReason      string         `db:"lost_reason" json:"lost_reason"`
	ID              int32          `db:"id" json:"id"`
}

// Mark a transaction as lost: sets transaction_type to 'lost', returned_date, applies replacement fine, and adds lost note
func (q *Queries) MarkTransactionAsLost(ctx context.Context, arg MarkTransactionAsLostParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, markTransactionAsLost, arg.ReplacementFine, arg.LostReason, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.DueDate,
		&i.ReturnedDate,
		&i.LibrarianID,
		&i.FineAmount,
		&i.FinePaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReturnCondition,
		&i.ConditionNotes,
		&i.FineWaived,
		&i.FineWaivedAt,
		&i.FineWaivedBy,
		&i.FineWaivedReason,
		&i.FinePaidAt,
		&i.CopyID,
		&i.Status,
		&i.RenewalCount,
		&i.LastRenewedAt,
		&i.LastRenewedBy,
	)
	return i, err
}

const payTransactionFine = `-- name: PayTransactionFine :one
UPDATE transactions
SET fine_paid = true, fine_paid_at = NOW(), updated_at = NOW()
WHERE id = $1
    AND fine_amount > 0
    AND fine_paid = false
RETURNING id, student_id, book_id, transaction_type, transaction_date, due_date, returned_date, librarian_id, fine_amount, fine_paid, notes, created_at, updated_at, return_condition, condition_notes, fine_waived, fine_waived_at, fine_waived_by, fine_waived_reason, fine_paid_at, copy_id, status, renewal_count, last_renewed_at, last_renewed_by
`

func (q *Queries) PayTransactionFine(ctx context.Context, id int32) (Transaction, error) {
	row := q.db.QueryRow(ctx, payTransactionFine, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.DueDate,
		&i.ReturnedDate,
		&i.LibrarianID,
		&i.FineAmount,
		&i.FinePaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReturnCondition,
		&i.ConditionNotes,
		&i.FineWaived,
		&i.FineWaivedAt,
		&i.FineWaivedBy,
		&i.FineWaivedReason,
		&i.FinePaidAt,
		&i.CopyID,
		&i.Status,
		&i.RenewalCount,
		&i.LastRenewedAt,
		&i.LastRenewedBy,
	)
	return i, err
}

const renewTransaction = `-- name: RenewTransaction :one
UPDATE transactions
SET
    due_date = $1::timestamp,
    renewal_count = COALESCE(renewal_count, 0) + 1,
    last_renewed_at = NOW(),
    last_renewed_by = $2::int,
    notes = CASE
        WHEN notes IS NULL OR notes = '' THEN '[RENEWED] Extended due date'
        ELSE notes || E'\n\n[RENEWED] Extended due date at ' || NOW()::text
    END,
    updated_at = NOW()
WHERE id = $3
  AND returned_date IS NULL
  AND transaction_type IN ('borrow', 'renew')
RETURNING id, student_id, book_id, transaction_type, transaction_date, due_date, returned_date, librarian_id, fine_amount, fine_paid, notes, created_at, updated_at, return_condition, condition_notes, fine_waived, fine_waived_at, fine_waived_by, fine_waived_reason, fine_paid_at, copy_id, status, renewal_count, last_renewed_at, last_renewed_by
`

type RenewTransactionParams struct {
	NewDueDate pgtype.Timestamp `db:"new_due_date" json:"new_due_date"`
	RenewedBy  int32            `db:"renewed_by" json:"renewed_by"`
	ID         int32            `db:"id" json:"id"`
}

// Renew a transaction by updating its due date and incrementing renewal count
// This replaces the old approach of creating a new "renew" type transaction
func (q *Queries) RenewTransaction(ctx context.Context, arg RenewTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, renewTransaction, arg.NewDueDate, arg.RenewedBy, arg.ID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.DueDate,
		&i.ReturnedDate,
		&i.LibrarianID,
		&i.FineAmount,
		&i.FinePaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReturnCondition,
		&i.ConditionNotes,
		&i.FineWaived,
		&i.FineWaivedAt,
		&i.FineWaivedBy,
		&i.FineWaivedReason,
		&i.FinePaidAt,
		&i.CopyID,
		&i.Status,
		&i.RenewalCount,
		&i.LastRenewedAt,
		&i.LastRenewedBy,
	)
	return i, err
}

const returnBook = `-- name: ReturnBook :one
UPDATE transactions
SET returned_date = NOW(), fine_amount = $2, return_condition = $3, condition_notes = $4, status = 'completed', updated_at = NOW()
WHERE id = $1 AND returned_date IS NULL
RETURNING id, student_id, book_id, transaction_type, transaction_date, due_date, returned_date, librarian_id, fine_amount, fine_paid, notes, created_at, updated_at, return_condition, condition_notes, fine_waived, fine_waived_at, fine_waived_by, fine_waived_reason, fine_paid_at, copy_id, status, renewal_count, last_renewed_at, last_renewed_by
`

type ReturnBookParams struct {
	ID              int32          `db:"id" json:"id"`
	FineAmount      pgtype.Numeric `db:"fine_amount" json:"fine_amount"`
	ReturnCondition pgtype.Text    `db:"return_condition" json:"return_condition"`
	ConditionNotes  pgtype.Text    `db:"condition_notes" json:"condition_notes"`
}

func (q *Queries) ReturnBook(ctx context.Context, arg ReturnBookParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, returnBook,
		arg.ID,
		arg.FineAmount,
		arg.ReturnCondition,
		arg.ConditionNotes,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.DueDate,
		&i.ReturnedDate,
		&i.LibrarianID,
		&i.FineAmount,
		&i.FinePaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReturnCondition,
		&i.ConditionNotes,
		&i.FineWaived,
		&i.FineWaivedAt,
		&i.FineWaivedBy,
		&i.FineWaivedReason,
		&i.FinePaidAt,
		&i.CopyID,
		&i.Status,
		&i.RenewalCount,
		&i.LastRenewedAt,
		&i.LastRenewedBy,
	)
	return i, err
}

const searchTransactions = `-- name: SearchTransactions :many
SELECT t.id, t.student_id, t.book_id, t.transaction_type, t.transaction_date, t.due_date, t.returned_date, t.librarian_id, t.fine_amount, t.fine_paid, t.notes, t.created_at, t.updated_at, t.return_condition, t.condition_notes, t.fine_waived, t.fine_waived_at, t.fine_waived_by, t.fine_waived_reason, t.fine_paid_at, t.copy_id, t.status, t.renewal_count, t.last_renewed_at, t.last_renewed_by,
       s.first_name, s.last_name, s.student_id as student_code,
       b.title, b.author, b.book_id as book_code, b.cover_image_url,
       bc.barcode as copy_barcode, bc.condition as copy_condition,
       s.deleted_at as student_deleted_at,
       del_user.username as student_deleted_by_name
FROM transactions t
JOIN students s ON t.student_id = s.id
JOIN books b ON t.book_id = b.id
LEFT JOIN book_copies bc ON t.copy_id = bc.id
LEFT JOIN users del_user ON s.deleted_by = del_user.id
WHERE
    ($1::text IS NULL OR $1 = '' OR
     b.title ILIKE '%' || $1 || '%' OR
     b.author ILIKE '%' || $1 || '%' OR
     s.first_name ILIKE '%' || $1 || '%' OR
     s.last_name ILIKE '%' || $1 || '%' OR
     s.student_id ILIKE '%' || $1 || '%' OR
     bc.barcode ILIKE '%' || $1 || '%')
    AND ($2::int IS NULL OR t.student_id = $2)
    AND ($3::int IS NULL OR t.book_id = $3)
    AND ($4::text IS NULL OR $4 = '' OR t.transaction_type = $4)
    AND ($5::timestamp IS NULL OR t.transaction_date >= $5)
    AND ($6::timestamp IS NULL OR t.transaction_date <= $6)
ORDER BY
    CASE WHEN $7::text = 'transaction_date' AND $8::text = 'asc' THEN t.transaction_date END ASC,
    CASE WHEN $7::text = 'transaction_date' AND $8::text = 'desc' THEN t.transaction_date END DESC,
    CASE WHEN $7::text = 'due_date' AND $8::text = 'asc' THEN t.due_date END ASC,
    CASE WHEN $7::text = 'due_date' AND $8::text = 'desc' THEN t.due_date END DESC,
    CASE WHEN $7::text IS NULL OR $7 = '' THEN t.transaction_date END DESC
LIMIT $10 OFFSET $9
`

type SearchTransactionsParams struct {
	Query           pgtype.Text      `db:"query" json:"query"`
	FilterStudentID pgtype.Int4      `db:"filter_student_id" json:"filter_student_id"`
	FilterBookID    pgtype.Int4      `db:"filter_book_id" json:"filter_book_id"`
	FilterType      pgtype.Text      `db:"filter_type" json:"filter_type"`
	FromDate        pgtype.Timestamp `db:"from_date" json:"from_date"`
	ToDate          pgtype.Timestamp `db:"to_date" json:"to_date"`
	SortBy          pgtype.Text      `db:"sort_by" json:"sort_by"`
	SortOrder       pgtype.Text      `db:"sort_order" json:"sort_order"`
	Offset          int32            `db:"offset" json:"offset"`
	Limit           int32            `db:"limit" json:"limit"`
}

type SearchTransactionsRow struct {
	ID                   int32            `db:"id" json:"id"`
	StudentID            int32            `db:"student_id" json:"student_id"`
	BookID               int32            `db:"book_id" json:"book_id"`
	TransactionType      string           `db:"transaction_type" json:"transaction_type"`
	TransactionDate      pgtype.Timestamp `db:"transaction_date" json:"transaction_date"`
	DueDate              pgtype.Timestamp `db:"due_date" json:"due_date"`
	ReturnedDate         pgtype.Timestamp `db:"returned_date" json:"returned_date"`
	LibrarianID          pgtype.Int4      `db:"librarian_id" json:"librarian_id"`
	FineAmount           pgtype.Numeric   `db:"fine_amount" json:"fine_amount"`
	FinePaid             pgtype.Bool      `db:"fine_paid" json:"fine_paid"`
	Notes                pgtype.Text      `db:"notes" json:"notes"`
	CreatedAt            pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	ReturnCondition      pgtype.Text      `db:"return_condition" json:"return_condition"`
	ConditionNotes       pgtype.Text      `db:"condition_notes" json:"condition_notes"`
	FineWaived           pgtype.Bool      `db:"fine_waived" json:"fine_waived"`
	FineWaivedAt         pgtype.Timestamp `db:"fine_waived_at" json:"fine_waived_at"`
	FineWaivedBy         pgtype.Int4      `db:"fine_waived_by" json:"fine_waived_by"`
	FineWaivedReason     pgtype.Text      `db:"fine_waived_reason" json:"fine_waived_reason"`
	FinePaidAt           pgtype.Timestamp `db:"fine_paid_at" json:"fine_paid_at"`
	CopyID               pgtype.Int4      `db:"copy_id" json:"copy_id"`
	Status               pgtype.Text      `db:"status" json:"status"`
	RenewalCount         pgtype.Int4      `db:"renewal_count" json:"renewal_count"`
	LastRenewedAt        pgtype.Timestamp `db:"last_renewed_at" json:"last_renewed_at"`
	LastRenewedBy        pgtype.Int4      `db:"last_renewed_by" json:"last_renewed_by"`
	FirstName            string           `db:"first_name" json:"first_name"`
	LastName             string           `db:"last_name" json:"last_name"`
	StudentCode          string           `db:"student_code" json:"student_code"`
	Title                string           `db:"title" json:"title"`
	Author               string           `db:"author" json:"author"`
	BookCode             string           `db:"book_code" json:"book_code"`
	CoverImageUrl        pgtype.Text      `db:"cover_image_url" json:"cover_image_url"`
	CopyBarcode          pgtype.Text      `db:"copy_barcode" json:"copy_barcode"`
	CopyCondition        pgtype.Text      `db:"copy_condition" json:"copy_condition"`
	StudentDeletedAt     pgtype.Timestamp `db:"student_deleted_at" json:"student_deleted_at"`
	StudentDeletedByName pgtype.Text      `db:"student_deleted_by_name" json:"student_deleted_by_name"`
}

func (q *Queries) SearchTransactions(ctx context.Context, arg SearchTransactionsParams) ([]SearchTransactionsRow, error) {
	rows, err := q.db.Query(ctx, searchTransactions,
		arg.Query,
		arg.FilterStudentID,
		arg.FilterBookID,
		arg.FilterType,
		arg.FromDate,
		arg.ToDate,
		arg.SortBy,
		arg.SortOrder,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTransactionsRow{}
	for rows.Next() {
		var i SearchTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.StudentID,
			&i.BookID,
			&i.TransactionType,
			&i.TransactionDate,
			&i.DueDate,
			&i.ReturnedDate,
			&i.LibrarianID,
			&i.FineAmount,
			&i.FinePaid,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReturnCondition,
			&i.ConditionNotes,
			&i.FineWaived,
			&i.FineWaivedAt,
			&i.FineWaivedBy,
			&i.FineWaivedReason,
			&i.FinePaidAt,
			&i.CopyID,
			&i.Status,
			&i.RenewalCount,
			&i.LastRenewedAt,
			&i.LastRenewedBy,
			&i.FirstName,
			&i.LastName,
			&i.StudentCode,
			&i.Title,
			&i.Author,
			&i.BookCode,
			&i.CoverImageUrl,
			&i.CopyBarcode,
			&i.CopyCondition,
			&i.StudentDeletedAt,
			&i.StudentDeletedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionFine = `-- name: UpdateTransactionFine :exec
UPDATE transactions
SET fine_amount = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateTransactionFineParams struct {
	ID         int32          `db:"id" json:"id"`
	FineAmount pgtype.Numeric `db:"fine_amount" json:"fine_amount"`
}

func (q *Queries) UpdateTransactionFine(ctx context.Context, arg UpdateTransactionFineParams) error {
	_, err := q.db.Exec(ctx, updateTransactionFine, arg.ID, arg.FineAmount)
	return err
}

const updateTransactionReturn = `-- name: UpdateTransactionReturn :one
UPDATE transactions
SET returned_date = NOW(), fine_amount = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, student_id, book_id, transaction_type, transaction_date, due_date, returned_date, librarian_id, fine_amount, fine_paid, notes, created_at, updated_at, return_condition, condition_notes, fine_waived, fine_waived_at, fine_waived_by, fine_waived_reason, fine_paid_at, copy_id, status, renewal_count, last_renewed_at, last_renewed_by
`

type UpdateTransactionReturnParams struct {
	ID         int32          `db:"id" json:"id"`
	FineAmount pgtype.Numeric `db:"fine_amount" json:"fine_amount"`
}

func (q *Queries) UpdateTransactionReturn(ctx context.Context, arg UpdateTransactionReturnParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionReturn, arg.ID, arg.FineAmount)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.BookID,
		&i.TransactionType,
		&i.TransactionDate,
		&i.DueDate,
		&i.ReturnedDate,
		&i.LibrarianID,
		&i.FineAmount,
		&i.FinePaid,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReturnCondition,
		&i.ConditionNotes,
		&i.FineWaived,
		&i.FineWaivedAt,
		&i.FineWaivedBy,
		&i.FineWaivedReason,
		&i.FinePaidAt,
		&i.CopyID,
		&i.Status,
		&i.RenewalCount,
		&i.LastRenewedAt,
		&i.LastRenewedBy,
	)
	return i, err
}
