// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS(
    SELECT 1 FROM users
    WHERE email = $1 AND deleted_at IS NULL AND ($2::int IS NULL OR id != $2)
)
`

type CheckEmailExistsParams struct {
	Email   string `db:"email" json:"email"`
	Column2 int32  `db:"column_2" json:"column_2"`
}

func (q *Queries) CheckEmailExists(ctx context.Context, arg CheckEmailExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkEmailExists, arg.Email, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT EXISTS(
    SELECT 1 FROM users
    WHERE username = $1 AND deleted_at IS NULL AND ($2::int IS NULL OR id != $2)
)
`

type CheckUsernameExistsParams struct {
	Username string `db:"username" json:"username"`
	Column2  int32  `db:"column_2" json:"column_2"`
}

func (q *Queries) CheckUsernameExists(ctx context.Context, arg CheckUsernameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUsernameExists, arg.Username, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAdminUsers = `-- name: CountAdminUsers :one
SELECT COUNT(*) FROM users
WHERE role = 'admin' AND is_active = true AND deleted_at IS NULL
`

func (q *Queries) CountAdminUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdminUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllUsers = `-- name: CountAllUsers :one

SELECT COUNT(*) FROM users WHERE deleted_at IS NULL
`

// =====================================================
// User Invites Queries
// =====================================================
// Count all users including inactive ones (for setup check)
func (q *Queries) CountAllUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingInvites = `-- name: CountPendingInvites :one
SELECT COUNT(*) FROM user_invites WHERE accepted_at IS NULL
`

func (q *Queries) CountPendingInvites(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingInvites)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSearchUsers = `-- name: CountSearchUsers :one
SELECT COUNT(*) FROM users
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR $1 = '' OR
       username ILIKE '%' || $1 || '%' OR
       email ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR $2 = '' OR role = $2)
  AND ($3::text IS NULL OR $3 = '' OR is_active = ($3 = 'true'))
`

type CountSearchUsersParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Column2 string `db:"column_2" json:"column_2"`
	Column3 string `db:"column_3" json:"column_3"`
}

func (q *Queries) CountSearchUsers(ctx context.Context, arg CountSearchUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSearchUsers, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
WHERE deleted_at IS NULL
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFirstAdmin = `-- name: CreateFirstAdmin :one
INSERT INTO users (username, email, password_hash, role, is_active)
VALUES ($1, $2, $3, 'admin', true) RETURNING id, username, email, password_hash, role, is_active, last_login, deleted_at, created_at, updated_at, invited_by
`

type CreateFirstAdminParams struct {
	Username     string      `db:"username" json:"username"`
	Email        string      `db:"email" json:"email"`
	PasswordHash pgtype.Text `db:"password_hash" json:"password_hash"`
}

// For first-run setup when no users exist
func (q *Queries) CreateFirstAdmin(ctx context.Context, arg CreateFirstAdminParams) (User, error) {
	row := q.db.QueryRow(ctx, createFirstAdmin, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InvitedBy,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, username, email, password_hash, role, is_active, last_login, deleted_at, created_at, updated_at, invited_by
`

type CreateUserParams struct {
	Username     string      `db:"username" json:"username"`
	Email        string      `db:"email" json:"email"`
	PasswordHash pgtype.Text `db:"password_hash" json:"password_hash"`
	Role         pgtype.Text `db:"role" json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InvitedBy,
	)
	return i, err
}

const createUserInvite = `-- name: CreateUserInvite :one
INSERT INTO user_invites (email, name, role, invite_token, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, email, name, role, invite_token, invited_by, expires_at, accepted_at, user_id, created_at, updated_at
`

type CreateUserInviteParams struct {
	Email       string           `db:"email" json:"email"`
	Name        string           `db:"name" json:"name"`
	Role        string           `db:"role" json:"role"`
	InviteToken string           `db:"invite_token" json:"invite_token"`
	InvitedBy   int32            `db:"invited_by" json:"invited_by"`
	ExpiresAt   pgtype.Timestamp `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateUserInvite(ctx context.Context, arg CreateUserInviteParams) (UserInvite, error) {
	row := q.db.QueryRow(ctx, createUserInvite,
		arg.Email,
		arg.Name,
		arg.Role,
		arg.InviteToken,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i UserInvite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.InviteToken,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserWithoutPassword = `-- name: CreateUserWithoutPassword :one
INSERT INTO users (username, email, role, is_active, invited_by)
VALUES ($1, $2, $3, true, $4) RETURNING id, username, email, password_hash, role, is_active, last_login, deleted_at, created_at, updated_at, invited_by
`

type CreateUserWithoutPasswordParams struct {
	Username  string      `db:"username" json:"username"`
	Email     string      `db:"email" json:"email"`
	Role      pgtype.Text `db:"role" json:"role"`
	InvitedBy pgtype.Int4 `db:"invited_by" json:"invited_by"`
}

func (q *Queries) CreateUserWithoutPassword(ctx context.Context, arg CreateUserWithoutPasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserWithoutPassword,
		arg.Username,
		arg.Email,
		arg.Role,
		arg.InvitedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InvitedBy,
	)
	return i, err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM user_invites WHERE id = $1
`

func (q *Queries) DeleteInvite(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteInvite, id)
	return err
}

const getInviteByEmail = `-- name: GetInviteByEmail :one
SELECT id, email, name, role, invite_token, invited_by, expires_at, accepted_at, user_id, created_at, updated_at FROM user_invites WHERE email = $1 AND accepted_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetInviteByEmail(ctx context.Context, email string) (UserInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByEmail, email)
	var i UserInvite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.InviteToken,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInviteByID = `-- name: GetInviteByID :one
SELECT ui.id, ui.email, ui.name, ui.role, ui.invite_token, ui.invited_by, ui.expires_at, ui.accepted_at, ui.user_id, ui.created_at, ui.updated_at, u.username as inviter_name FROM user_invites ui
JOIN users u ON ui.invited_by = u.id
WHERE ui.id = $1
`

type GetInviteByIDRow struct {
	ID          int32            `db:"id" json:"id"`
	Email       string           `db:"email" json:"email"`
	Name        string           `db:"name" json:"name"`
	Role        string           `db:"role" json:"role"`
	InviteToken string           `db:"invite_token" json:"invite_token"`
	InvitedBy   int32            `db:"invited_by" json:"invited_by"`
	ExpiresAt   pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	AcceptedAt  pgtype.Timestamp `db:"accepted_at" json:"accepted_at"`
	UserID      pgtype.Int4      `db:"user_id" json:"user_id"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	InviterName string           `db:"inviter_name" json:"inviter_name"`
}

func (q *Queries) GetInviteByID(ctx context.Context, id int32) (GetInviteByIDRow, error) {
	row := q.db.QueryRow(ctx, getInviteByID, id)
	var i GetInviteByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.InviteToken,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InviterName,
	)
	return i, err
}

const getInviteByToken = `-- name: GetInviteByToken :one
SELECT id, email, name, role, invite_token, invited_by, expires_at, accepted_at, user_id, created_at, updated_at FROM user_invites WHERE invite_token = $1 AND accepted_at IS NULL
`

func (q *Queries) GetInviteByToken(ctx context.Context, inviteToken string) (UserInvite, error) {
	row := q.db.QueryRow(ctx, getInviteByToken, inviteToken)
	var i UserInvite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.InviteToken,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, role, is_active, last_login, deleted_at, created_at, updated_at, invited_by FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InvitedBy,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, role, is_active, last_login, deleted_at, created_at, updated_at, invited_by FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InvitedBy,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, role, is_active, last_login, deleted_at, created_at, updated_at, invited_by FROM users
WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InvitedBy,
	)
	return i, err
}

const listPendingInvites = `-- name: ListPendingInvites :many
SELECT ui.id, ui.email, ui.name, ui.role, ui.invite_token, ui.invited_by, ui.expires_at, ui.accepted_at, ui.user_id, ui.created_at, ui.updated_at, u.username as inviter_name FROM user_invites ui
JOIN users u ON ui.invited_by = u.id
WHERE ui.accepted_at IS NULL
ORDER BY ui.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPendingInvitesParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListPendingInvitesRow struct {
	ID          int32            `db:"id" json:"id"`
	Email       string           `db:"email" json:"email"`
	Name        string           `db:"name" json:"name"`
	Role        string           `db:"role" json:"role"`
	InviteToken string           `db:"invite_token" json:"invite_token"`
	InvitedBy   int32            `db:"invited_by" json:"invited_by"`
	ExpiresAt   pgtype.Timestamp `db:"expires_at" json:"expires_at"`
	AcceptedAt  pgtype.Timestamp `db:"accepted_at" json:"accepted_at"`
	UserID      pgtype.Int4      `db:"user_id" json:"user_id"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	InviterName string           `db:"inviter_name" json:"inviter_name"`
}

func (q *Queries) ListPendingInvites(ctx context.Context, arg ListPendingInvitesParams) ([]ListPendingInvitesRow, error) {
	rows, err := q.db.Query(ctx, listPendingInvites, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingInvitesRow{}
	for rows.Next() {
		var i ListPendingInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Role,
			&i.InviteToken,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InviterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, role, is_active, last_login, deleted_at, created_at, updated_at, invited_by FROM users
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.LastLogin,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InvitedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInviteAccepted = `-- name: MarkInviteAccepted :one
UPDATE user_invites SET accepted_at = NOW(), user_id = $2, updated_at = NOW()
WHERE id = $1 RETURNING id, email, name, role, invite_token, invited_by, expires_at, accepted_at, user_id, created_at, updated_at
`

type MarkInviteAcceptedParams struct {
	ID     int32       `db:"id" json:"id"`
	UserID pgtype.Int4 `db:"user_id" json:"user_id"`
}

func (q *Queries) MarkInviteAccepted(ctx context.Context, arg MarkInviteAcceptedParams) (UserInvite, error) {
	row := q.db.QueryRow(ctx, markInviteAccepted, arg.ID, arg.UserID)
	var i UserInvite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.InviteToken,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, username, email, password_hash, role, is_active, last_login, deleted_at, created_at, updated_at, invited_by FROM users
WHERE deleted_at IS NULL
  AND ($1::text IS NULL OR $1 = '' OR
       username ILIKE '%' || $1 || '%' OR
       email ILIKE '%' || $1 || '%')
  AND ($2::text IS NULL OR $2 = '' OR role = $2)
  AND ($3::text IS NULL OR $3 = '' OR is_active = ($3 = 'true'))
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type SearchUsersParams struct {
	Column1 string `db:"column_1" json:"column_1"`
	Column2 string `db:"column_2" json:"column_2"`
	Column3 string `db:"column_3" json:"column_3"`
	Limit   int32  `db:"limit" json:"limit"`
	Offset  int32  `db:"offset" json:"offset"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, searchUsers,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.IsActive,
			&i.LastLogin,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InvitedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = NOW() WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           int32       `db:"id" json:"id"`
	PasswordHash pgtype.Text `db:"password_hash" json:"password_hash"`
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateInviteToken = `-- name: UpdateInviteToken :one
UPDATE user_invites SET invite_token = $2, expires_at = $3, updated_at = NOW()
WHERE id = $1 RETURNING id, email, name, role, invite_token, invited_by, expires_at, accepted_at, user_id, created_at, updated_at
`

type UpdateInviteTokenParams struct {
	ID          int32            `db:"id" json:"id"`
	InviteToken string           `db:"invite_token" json:"invite_token"`
	ExpiresAt   pgtype.Timestamp `db:"expires_at" json:"expires_at"`
}

func (q *Queries) UpdateInviteToken(ctx context.Context, arg UpdateInviteTokenParams) (UserInvite, error) {
	row := q.db.QueryRow(ctx, updateInviteToken, arg.ID, arg.InviteToken, arg.ExpiresAt)
	var i UserInvite
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.InviteToken,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = $2, email = $3, password_hash = $4, role = $5, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, username, email, password_hash, role, is_active, last_login, deleted_at, created_at, updated_at, invited_by
`

type UpdateUserParams struct {
	ID           int32       `db:"id" json:"id"`
	Username     string      `db:"username" json:"username"`
	Email        string      `db:"email" json:"email"`
	PasswordHash pgtype.Text `db:"password_hash" json:"password_hash"`
	Role         pgtype.Text `db:"role" json:"role"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InvitedBy,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserPasswordParams struct {
	ID           int32       `db:"id" json:"id"`
	PasswordHash pgtype.Text `db:"password_hash" json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET email = COALESCE($2, email),
    role = COALESCE($3, role),
    is_active = COALESCE($4, is_active),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, username, email, password_hash, role, is_active, last_login, deleted_at, created_at, updated_at, invited_by
`

type UpdateUserProfileParams struct {
	ID       int32       `db:"id" json:"id"`
	Email    string      `db:"email" json:"email"`
	Role     pgtype.Text `db:"role" json:"role"`
	IsActive pgtype.Bool `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.Email,
		arg.Role,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InvitedBy,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users
SET is_active = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, username, email, password_hash, role, is_active, last_login, deleted_at, created_at, updated_at, invited_by
`

type UpdateUserStatusParams struct {
	ID       int32       `db:"id" json:"id"`
	IsActive pgtype.Bool `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.IsActive)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InvitedBy,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (username, email, password_hash, role, is_active)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (username)
DO UPDATE SET
    email = EXCLUDED.email,
    password_hash = EXCLUDED.password_hash,
    role = EXCLUDED.role,
    is_active = EXCLUDED.is_active,
    updated_at = NOW()
RETURNING id, username, email, password_hash, role, is_active, last_login, deleted_at, created_at, updated_at, invited_by
`

type UpsertUserParams struct {
	Username     string      `db:"username" json:"username"`
	Email        string      `db:"email" json:"email"`
	PasswordHash pgtype.Text `db:"password_hash" json:"password_hash"`
	Role         pgtype.Text `db:"role" json:"role"`
	IsActive     pgtype.Bool `db:"is_active" json:"is_active"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsActive,
		&i.LastLogin,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InvitedBy,
	)
	return i, err
}
