run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  goimports:
    local-prefixes: github.com/ngenohkevin/lms
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  
  disable:
    - deadcode    # deprecated since v1.49.0, replaced by unused
    - structcheck # deprecated since v1.49.0, replaced by unused
    - varcheck    # deprecated since v1.49.0, replaced by unused
    - errname
    - errorlint
    - forbidigo
    - forcetypeassert
    - goerr113
    - gofumpt
    - goheader
    - gomodguard
    - importas
    - makezero
    - nlreturn
    - paralleltest
    - predeclared
    - promlinter
    - revive
    - tagliatelle
    - testpackage
    - thelper
    - wrapcheck
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd

  exclude-use-default: false
  exclude:
    - 'declaration of "(err|ctx)" shadows declaration at'